// HSAD k6 browser 스크립트용 selector 모음
// shared-configs/tid/ JSON 파일 기반 [data-tid="..."] selector
// 네임스페이스: LOGIN / BUSINESS / WEB / SHARED_UI
export const SELECTORS = {

    // =========================================================
    // LOGIN (tid 미적용 - CSS selector 직접 사용)
    // =========================================================
    LOGIN: {
        EMAIL_INPUT: 'input[id="email"]',
        PASSWORD_INPUT: 'input[id="password"]',
        SUBMIT_BUTTON: 'button[type="submit"]',
        LOGOUT: 'img[alt="이동"]',
    },

    // =========================================================
    // BUSINESS
    // =========================================================
    BUSINESS: {

        AD_REVIEW: {
            BUTTON: '[data-tid="9de9a3cc"]',
        },

        AD_POST_REVIEW: {
            BUTTON: '[data-tid="12667a6a"]',
            BUTTON_ATTACH_FILE: '[data-tid="9da02279"]',
            INPUT: '[data-tid="deb32926"]',
        },

        ADVICE: {
            BUTTON: '[data-tid="681b905c"]',
            BUTTON_1: '[data-tid="53adc555"]',
            BUTTON_2: '[data-tid="b915e3d6"]',
            BUTTON_3: '[data-tid="79561403"]',
            BUTTON_4: '[data-tid="6ec53a84"]',
            BUTTON_5: '[data-tid="e5e40799"]',
            BUTTON_6: '[data-tid="7a5a1d34"]',
            BUTTON_CLICK_DELETE: '[data-tid="804ab98e"]',
            BUTTON_CLICK_EXCEL_DOWNLOAD: '[data-tid="59172ffe"]',
            BUTTON_CLICK_PREVIEW: '[data-tid="f428609d"]',
            BUTTON_CLICK_REQUEST_CANCEL: '[data-tid="e4263213"]',
            BUTTON_CLICK_VIEWER_OR_DOWNLOAD: '[data-tid="31df8d00"]',
            BUTTON_CREATE: '[data-tid="726adf23"]',
            BUTTON_DOCX_IS_LOADING: '[data-tid="2b10a143"]',
            BUTTON_EDIT_CLICK: '[data-tid="b528025b"]',
            BUTTON_IS_OPEN: '[data-tid="532c4cc3"]',
            BUTTON_OPEN_DISABLE_EDITOR_MODAL: '[data-tid="6930de72"]',
            BUTTON_OPEN_DOWNLOAD_MODAL: '[data-tid="5276b0e9"]',
            BUTTON_PDF_IS_LOADING: '[data-tid="5be445a2"]',
            BUTTON_ROUTE_ADVICE_LIST: '[data-tid="bcd4d134"]',
            BUTTON_ROUTE_DRAFT: '[data-tid="ba82a05b"]',
            BUTTON_SAVE_CLICK: '[data-tid="1edabf88"]',
            BUTTON_SEND_LEGAL_ADVICE_TO_REQUESTER: '[data-tid="0358177d"]',
            BUTTON_TEMP_SAVE: '[data-tid="4fd7e8b0"]',
            DATEPICKER: '[data-tid="aeb780b3"]',
            INPUT: '[data-tid="c45ca4f2"]',
            INPUT_FILE_UPLOAD: '[data-tid="141f18d9"]',
            INPUT_TITLE_SEARCH: '[data-tid="92c31d8f"]',
            PAGINATION: '[data-tid="27801ac7"]',
            RADIO: '[data-tid="34680ab0"]',
            RADIO_1: '[data-tid="380970f5"]',
            RADIO_2: '[data-tid="88bd442d"]',
            RADIO_3: '[data-tid="79aa2f33"]',
            SELECT: '[data-tid="26fb56d8"]',
            TEXTAREA: '[data-tid="d61766c9"]',
            TEXTAREA_1: '[data-tid="31083cc9"]',
            TEXTAREA_2: '[data-tid="27fbaf59"]',
        },

        AI: {
            BUTTON_STEP_ONE: '[data-tid="eb09fcbc"]',
            INPUT: '[data-tid="d4f32ecd"]',
            SELECT: '[data-tid="38f0eb27"]',
        },

        BLOG: {
            BUTTON: '[data-tid="6cfba917"]',
            BUTTON_CLICK_BTN: '[data-tid="5362a9f1"]',
            BUTTON_CLICK_SHARE_BUTTON: '[data-tid="2d9cc096"]',
        },

        BULK: {
            BUTTON: '[data-tid="d9f133ee"]',
            BUTTON_1: '[data-tid="8898dd50"]',
            BUTTON_2: '[data-tid="005cfc99"]',
            BUTTON_3: '[data-tid="5b8c4261"]',
            BUTTON_4: '[data-tid="e2cbbd38"]',
            BUTTON_5: '[data-tid="68a7526d"]',
            BUTTON_CLICK: '[data-tid="ed915f47"]',
            BUTTON_CLICK_SIGN_EXCEL_DOWNLOAD: '[data-tid="9110874e"]',
            BUTTON_CLOSE: '[data-tid="4064f48d"]',
            BUTTON_CLOSE_1: '[data-tid="e9a0db9f"]',
            BUTTON_CONFIRM_BUTTON: '[data-tid="a8e6b0a5"]',
            BUTTON_DELETE: '[data-tid="00e4c717"]',
            BUTTON_DOWNLOAD: '[data-tid="d8c5c464"]',
            BUTTON_ESIGN_CANCEL: '[data-tid="c93da1f2"]',
            BUTTON_GO_TO_BULK_MAIN: '[data-tid="5a60059d"]',
            BUTTON_GO_TO_LIST: '[data-tid="e3192a88"]',
            BUTTON_NEXT: '[data-tid="70ee490d"]',
            BUTTON_PREV: '[data-tid="9a23c26e"]',
            BUTTON_REMOVE_FILE: '[data-tid="f33a6793"]',
            BUTTON_SELECT_ALL: '[data-tid="8d50b1b1"]',
            BUTTON_SUBMIT: '[data-tid="6437e902"]',
            CHECKBOX: '[data-tid="6a8fa758"]',
            CHECKBOX_1: '[data-tid="e71ee118"]',
            INPUT: '[data-tid="3388df63"]',
            INPUT_FILE_INPUT: '[data-tid="5475f7a4"]',
            INPUT_TITLE_SEARCH: '[data-tid="84288d84"]',
            PAGINATION: '[data-tid="764234a9"]',
            SELECT: '[data-tid="d71f1df2"]',
            TEXTAREA: '[data-tid="74d32744"]',
        },

        CLM: {
            BUTTON: '[data-tid="12b68a3f"]',
            BUTTON_1: '[data-tid="3b83c390"]',
            BUTTON_2: '[data-tid="b917fe7c"]',
            BUTTON_3: '[data-tid="31c4af24"]',
            BUTTON_4: '[data-tid="54d491f3"]',
            BUTTON_5: '[data-tid="199de4f2"]',
            BUTTON_6: '[data-tid="833497cb"]',
            BUTTON_7: '[data-tid="e21e1b79"]',
            BUTTON_8: '[data-tid="d6ab7faf"]',
            BUTTON_9: '[data-tid="6ec93370"]',
            BUTTON_10: '[data-tid="d36b35d9"]',
            BUTTON_11: '[data-tid="fcdec591"]',
            BUTTON_12: '[data-tid="0418a92b"]',
            BUTTON_13: '[data-tid="2ae04180"]',
            BUTTON_14: '[data-tid="f5accd18"]',
            BUTTON_15: '[data-tid="b4eb97b6"]',
            BUTTON_16: '[data-tid="3aa857ec"]',
            BUTTON_17: '[data-tid="f17b9fe8"]',
            BUTTON_APPROVAL_REQUEST: '[data-tid="93eadda6"]',
            BUTTON_BLACKLIST_SPECIAL_APPROVE: '[data-tid="b064103f"]',
            BUTTON_BLACKLIST_SPECIAL_REJECT: '[data-tid="5b3972db"]',
            BUTTON_CANCEL: '[data-tid="bd22e1ba"]',
            BUTTON_CHANGE: '[data-tid="c054ea38"]',
            BUTTON_CLICK: '[data-tid="9502094d"]',
            BUTTON_CLICK_ADD_TEAM: '[data-tid="5e004f75"]',
            BUTTON_CLICK_AI_CHECK: '[data-tid="215148b5"]',
            BUTTON_CLICK_ASSIGN: '[data-tid="88c0041d"]',
            BUTTON_CLICK_CANCEL_FINAL_APPROVAL: '[data-tid="8d1305ac"]',
            BUTTON_CLICK_CANCEL_FINAL_APPROVAL_1: '[data-tid="224d85ad"]',
            BUTTON_CLICK_CHANGE_ASSIGNER: '[data-tid="4ca79faf"]',
            BUTTON_CLICK_COMPLETE_LEGAL: '[data-tid="d5745346"]',
            BUTTON_CLICK_CREATE_BULK: '[data-tid="bc445522"]',
            BUTTON_CLICK_CREATE_EXCEL_DOWNLOAD: '[data-tid="6d8d3171"]',
            BUTTON_CLICK_DELETE: '[data-tid="83aa002c"]',
            BUTTON_CLICK_DOWNLOAD_FILE: '[data-tid="3b2fa005"]',
            BUTTON_CLICK_DOWNLOAD_OR_VIEWER: '[data-tid="dd373805"]',
            BUTTON_CLICK_ESIGN: '[data-tid="bc97150d"]',
            BUTTON_CLICK_PREVIEW: '[data-tid="43acb37e"]',
            BUTTON_CLICK_REMOVE: '[data-tid="e7dd6889"]',
            BUTTON_CLICK_SIGN_EXCEL_DOWNLOAD: '[data-tid="a9929fa9"]',
            BUTTON_CLICK_VIEWER: '[data-tid="fdf169e7"]',
            BUTTON_CLOSE: '[data-tid="30c93575"]',
            BUTTON_CLOSE_1: '[data-tid="19a03311"]',
            BUTTON_CLOSE_MODAL: '[data-tid="6d30ce1f"]',
            BUTTON_CONFIRM: '[data-tid="9a7c08eb"]',
            BUTTON_CREATE: '[data-tid="180e8fb0"]',
            BUTTON_EMPTY_LIST_N_KEYWORD: '[data-tid="9f8b4180"]',
            BUTTON_FINAL_APPROVAL_REQUEST: '[data-tid="08095903"]',
            BUTTON_FINAL_APPROVAL_REQUEST_1: '[data-tid="42312cb9"]',
            BUTTON_GO_TO_LIST: '[data-tid="3116ad1c"]',
            BUTTON_IS_LOADING: '[data-tid="e8d2d899"]',
            BUTTON_LEGAL_AGAIN: '[data-tid="3b04df1f"]',
            BUTTON_LEGAL_AGAIN_1: '[data-tid="a3643231"]',
            BUTTON_MANUAL_REGISTER: '[data-tid="1fd6644e"]',
            BUTTON_OPEN_JOB_NUMBER_MODAL: '[data-tid="20g1s9fs"]',
            BUTTON_OPEN_CLEAN_DOWNLOAD_MODAL: '[data-tid="b6e28533"]',
            BUTTON_OPEN_DOWNLOAD_MODAL: '[data-tid="ebb7a933"]',
            BUTTON_OPEN_MODAL: '[data-tid="0d523ebb"]',
            BUTTON_OPEN_WATER_MARK_MODAL: '[data-tid="6a0d9ae2"]',
            BUTTON_PARALLEL_APPROVE: '[data-tid="0e8cee85"]',
            BUTTON_PARALLEL_COMPLETE: '[data-tid="ec6f4aa4"]',
            BUTTON_PARALLEL_RESEND: '[data-tid="c293a292"]',
            BUTTON_REMOVE: '[data-tid="47271431"]',
            BUTTON_REMOVE_1: '[data-tid="5c5a7158"]',
            BUTTON_REVIEW_REQUEST_CANCEL: '[data-tid="7ef2e07d"]',
            BUTTON_SAVE: '[data-tid="69c770b9"]',
            BUTTON_SUBMIT: '[data-tid="53643b41"]',
            BUTTON_TOGGLE_PREVIEW: '[data-tid="57d1f7b2"]',
            BUTTON_TOGGLE_SELECT: '[data-tid="e43345c8"]',
            BUTTON_UPDATE_DRAFT: '[data-tid="7e7cb559"]',
            DATEPICKER: '[data-tid="a4baeb71"]',
            DATEPICKER_1: '[data-tid="d1275d4d"]',
            DATEPICKER_2: '[data-tid="10f59f4e"]',
            INPUT: '[data-tid="1eaa717d"]',
            INPUT_1: '[data-tid="4a4b4ae6"]',
            INPUT_2: '[data-tid="99e7dcd2"]',
            INPUT_CONTENT: '[data-tid="21997440"]',
            INPUT_FILE_UPLOAD: '[data-tid="1abaffa4"]',
            INPUT_SEARCH: '[data-tid="5b2d6d29"]',
            INPUT_SEARCH_1: '[data-tid="fd00b597"]',
            INPUT_SEARCH_DOCUMENT: '[data-tid="c885af6e"]',
            INPUT_TITLE_SEARCH: '[data-tid="50d8659a"]',
            PAGINATION: '[data-tid="320cebc4"]',
            RADIO: '[data-tid="21e37a72"]',
            RADIO_1: '[data-tid="6394c905"]',
            RADIO_2: '[data-tid="8bb724ed"]',
            RADIO_3: '[data-tid="4f2bf1e1"]',
            RADIO_4: '[data-tid="6b61a508"]',
            RADIO_5: '[data-tid="ccd55b3b"]',
            RADIO_6: '[data-tid="d61fc8e1"]',
            RADIO_7: '[data-tid="b4684956"]',
            RADIO_8: '[data-tid="ca2fa99f"]',
            RADIO_9: '[data-tid="c3105745"]',
            RADIO_10: '[data-tid="60768ab3"]',
            RADIO_11: '[data-tid="268a7239"]',
            SELECT: '[data-tid="c4cfcb4d"]',
            SELECT_1: '[data-tid="f9843ed3"]',
            SELECT_2: '[data-tid="37c455ed"]',
            SELECT_3: '[data-tid="5f9956c7"]',
            SELECT_4: '[data-tid="eba673a5"]',
            SELECT_5: '[data-tid="aae48250"]',
            SELECT_6: '[data-tid="64537eaa"]',
            SELECT_7: '[data-tid="1311359b"]',
            SELECT_8: '[data-tid="5d385bbe"]',
            TEXTAREA: '[data-tid="9dc95143"]',
            TEXTAREA_1: '[data-tid="de769f3f"]',
        },

        COMMON: {
            BUTTON_CLICK: '[data-tid="d18be363"]',
            BUTTON_CLICK_TOGGLE: '[data-tid="8900d31b"]',
            INPUT_CONTRACT_FILE_UPLOAD: '[data-tid="7626cc8b"]',
            INPUT_TITLE_SEARCH: '[data-tid="b51ca43c"]',
        },

        DASHBOARD: {
            BUTTON: '[data-tid="9b8c8513"]',
            BUTTON_CLICK_MORE: '[data-tid="1d9dafff"]',
            BUTTON_CLOSE_MODAL: '[data-tid="8dbacbb5"]',
            CHECKBOX: '[data-tid="1aac1e31"]',
            DATEPICKER: '[data-tid="27f8537e"]',
        },

        DEV: {
            BUTTON: '[data-tid="4857860d"]',
            BUTTON_1: '[data-tid="c2454bea"]',
            BUTTON_2: '[data-tid="e6394109"]',
            BUTTON_3: '[data-tid="34ed7fe2"]',
            BUTTON_4: '[data-tid="a96da0e8"]',
            BUTTON_5: '[data-tid="90c111f0"]',
            BUTTON_6: '[data-tid="969792bb"]',
            BUTTON_7: '[data-tid="94c0bfa6"]',
            BUTTON_8: '[data-tid="ded1f14d"]',
            BUTTON_9: '[data-tid="ea0a8ffd"]',
        },

        DOCUMENT_COMPARE: {
            BUTTON: '[data-tid="aa00c091"]',
            BUTTON_1: '[data-tid="10f4dea0"]',
            BUTTON_CLICK_COMPARE: '[data-tid="c1136259"]',
            BUTTON_HISTORY_CLEAR: '[data-tid="43e15405"]',
            BUTTON_HISTORY_CLEAR_1: '[data-tid="535c2f4b"]',
            INPUT: '[data-tid="c20c2f69"]',
            PAGINATION: '[data-tid="f885e19f"]',
            PAGINATION_1: '[data-tid="68e06fef"]',
            RADIO: '[data-tid="989ea3d1"]',
            RADIO_1: '[data-tid="a0eeb820"]',
            RADIO_2: '[data-tid="4a6b1058"]',
        },

        DRIVE: {
            BUTTON: '[data-tid="dde025c0"]',
            BUTTON_1: '[data-tid="bf76b1a2"]',
        },

        INQUIRY: {
            BUTTON: '[data-tid="9e9e4912"]',
            BUTTON_1: '[data-tid="7e1cbc7b"]',
            BUTTON_ATTACH_FILE: '[data-tid="ef3238ca"]',
            BUTTON_CREATE_HISTORY: '[data-tid="7a458eb8"]',
            BUTTON_SEND: '[data-tid="508fe967"]',
            BUTTON_SUBMIT: '[data-tid="48fa6922"]',
            BUTTON_SUBMIT_1: '[data-tid="6b249a40"]',
            INPUT: '[data-tid="cf3bd226"]',
            INPUT_1: '[data-tid="cd0f41f4"]',
            INPUT_2: '[data-tid="0b2cd802"]',
            INPUT_3: '[data-tid="c87c94b2"]',
            INPUT_4: '[data-tid="8313c570"]',
            INPUT_5: '[data-tid="365d8f78"]',
            INPUT_6: '[data-tid="fd4479f1"]',
            INPUT_7: '[data-tid="2f35593f"]',
            SELECT: '[data-tid="202994a8"]',
            SELECT_1: '[data-tid="2cad5ec8"]',
            TEXTAREA: '[data-tid="1b1e841e"]',
            TEXTAREA_1: '[data-tid="f98f5338"]',
        },

        INTERNAL_NOTICE: {
            BUTTON: '[data-tid="28721735"]',
            BUTTON_CLICK_CANCEL: '[data-tid="73c74524"]',
            BUTTON_CLICK_CREATE: '[data-tid="ec285b79"]',
            BUTTON_CLICK_DELETE_BUTTON: '[data-tid="aeac9cb3"]',
            BUTTON_CLICK_EDIT_BUTTON: '[data-tid="3f619b4c"]',
            BUTTON_CLICK_LIST_BUTTON: '[data-tid="09ac9893"]',
            BUTTON_CLICK_PREVIEW: '[data-tid="a17d915d"]',
            BUTTON_CLICK_UPDATE: '[data-tid="e374aee3"]',
            INPUT: '[data-tid="4d97e397"]',
            PAGINATION: '[data-tid="2a287d3a"]',
        },

        LAW: {
            BUTTON: '[data-tid="79e31b8c"]',
            BUTTON_1: '[data-tid="9d501510"]',
            BUTTON_CLICK_REFRESH_ICON: '[data-tid="9475d26b"]',
            BUTTON_CLICK_TAB: '[data-tid="ef02b6be"]',
            BUTTON_OPEN_MODAL_LAW_ALARM_SETTING: '[data-tid="16a511be"]',
            CHECKBOX: '[data-tid="7d283aef"]',
            CHECKBOX_1: '[data-tid="6a3598c6"]',
            DATEPICKER: '[data-tid="481ab3d0"]',
            RADIO: '[data-tid="d0eede83"]',
            RADIO_1: '[data-tid="3364d20c"]',
        },

        LEGAL_DRAFT: {
            BUTTON: '[data-tid="3a86ba84"]',
            BUTTON_ATTACH_FILE: '[data-tid="204c5ad7"]',
            BUTTON_OPEN_EXTERNAL: '[data-tid="489f130f"]',
            INPUT: '[data-tid="ecc49360"]',
        },

        LEGAL_INQUIRY: {
            BUTTON: '[data-tid="050badb9"]',
            BUTTON_ATTACH_FILE: '[data-tid="f4f9466b"]',
            INPUT: '[data-tid="ccf53de7"]',
        },

        LITIGATION: {
            BUTTON: '[data-tid="48efe758"]',
            BUTTON_1: '[data-tid="c4937c0e"]',
            BUTTON_2: '[data-tid="b7b20565"]',
            BUTTON_3: '[data-tid="8a84f82f"]',
            BUTTON_4: '[data-tid="988f9123"]',
            BUTTON_CLICK: '[data-tid="25702d70"]',
            BUTTON_CLICK_CREATE_SCHEDULE: '[data-tid="976ae131"]',
            BUTTON_CLICK_DOWNLOAD_EXCEL: '[data-tid="78b0832f"]',
            BUTTON_CLICK_EXCEL_DOWNLOAD: '[data-tid="49c42273"]',
            BUTTON_CLICK_GO_FORM_PAGE: '[data-tid="1c17a19d"]',
            BUTTON_CLICK_LOAD_LITIGATION: '[data-tid="0742719b"]',
            BUTTON_CLICK_OPEN_COMMENT_ROW: '[data-tid="40f832de"]',
            BUTTON_CLICK_OPEN_DELETE_CONFIRM: '[data-tid="76de46b6"]',
            BUTTON_CLICK_SUBMIT: '[data-tid="821d068b"]',
            BUTTON_CLICK_TEMP_SAVE: '[data-tid="1fb9dd2f"]',
            BUTTON_CLOSE: '[data-tid="b55275ac"]',
            BUTTON_CLOSE_1: '[data-tid="b5b734ea"]',
            BUTTON_CLOSE_COMMENT_ROW: '[data-tid="5a80d220"]',
            BUTTON_COMPLETE_LITIGATION: '[data-tid="9fe7c241"]',
            BUTTON_DELETE: '[data-tid="ec173001"]',
            BUTTON_DRAFT_SUBMIT: '[data-tid="0d939bdf"]',
            BUTTON_LITIGATION_DISABLED: '[data-tid="f3c093cd"]',
            BUTTON_ROUTE_ADVICE_LIST: '[data-tid="cab1cd66"]',
            BUTTON_ROUTE_PAGE: '[data-tid="44039c35"]',
            BUTTON_SAVE_MODIFY_INFO: '[data-tid="630c5a0e"]',
            CHECKBOX: '[data-tid="beeb0c1e"]',
            DATEPICKER: '[data-tid="02e6733c"]',
            INPUT: '[data-tid="c191eca4"]',
            INPUT_1: '[data-tid="62e2c29a"]',
            INPUT_2: '[data-tid="fd398349"]',
            INPUT_3: '[data-tid="17c9e9bb"]',
            INPUT_4: '[data-tid="d73d9698"]',
            INPUT_5: '[data-tid="fd3318c8"]',
            INPUT_6: '[data-tid="56049338"]',
            INPUT_FILE_UPLOAD: '[data-tid="ccc13182"]',
            PAGINATION: '[data-tid="997bacef"]',
            RADIO: '[data-tid="3ddb4432"]',
            RADIO_1: '[data-tid="586c2977"]',
            RADIO_2: '[data-tid="0e97fc18"]',
            RADIO_3: '[data-tid="3599c8fb"]',
            SELECT: '[data-tid="dd837bbc"]',
            SELECT_1: '[data-tid="1472f29e"]',
            SELECT_2: '[data-tid="61ecd5b9"]',
            SELECT_3: '[data-tid="fcebcd28"]',
            SELECT_COURT: '[data-tid="d9b85967"]',
        },

        LOG: {
            BUTTON: '[data-tid="3d74b8fb"]',
            DATEPICKER: '[data-tid="1e23b54c"]',
            DATEPICKER_1: '[data-tid="095f3f9d"]',
            INPUT: '[data-tid="af14b302"]',
            PAGINATION: '[data-tid="1872891c"]',
            SELECT: '[data-tid="3f2f71eb"]',
            SELECT_1: '[data-tid="6348fc73"]',
        },

        MOBILE: {
            BUTTON_MOVE_TO_RESET_PASSWORD: '[data-tid="006b405b"]',
            BUTTON_SUBMIT: '[data-tid="b678409e"]',
            INPUT_BUSINESS_REMEMBER_USER_EMAIL_CHECKBOX_MOBILE: '[data-tid="46a3cc4e"]',
        },

        MODAL: {
            BUTTON: '[data-tid="ebefaeb4"]',
            BUTTON_1: '[data-tid="9576907f"]',
            BUTTON_2: '[data-tid="8a6fb87b"]',
            BUTTON_CANCEL_JOB_NUMBER: '[data-tid="0fe6e0d1"]',
            BUTTON_CHANGE: '[data-tid="aa6a3642"]',
            BUTTON_CLICK: '[data-tid="7b646af4"]',
            BUTTON_CLICK_CANCEL: '[data-tid="a642219f"]',
            BUTTON_CLICK_CLOSE: '[data-tid="5ff7474c"]',
            BUTTON_CLICK_CLOSE_1: '[data-tid="7bd1894b"]',
            BUTTON_CLICK_CONFIRM: '[data-tid="c806cbc3"]',
            BUTTON_CLICK_CONFIRM_1: '[data-tid="f9cde575"]',
            BUTTON_CLICK_INVITE: '[data-tid="e55dbc1d"]',
            BUTTON_CLICK_LOAD: '[data-tid="4dea8767"]',
            BUTTON_CLICK_RETRY: '[data-tid="9bc892b2"]',
            BUTTON_CLICK_SAVE: '[data-tid="b3e744ae"]',
            BUTTON_CLICK_SAVE_NOTIFICATION: '[data-tid="38fe4e50"]',
            BUTTON_CLOSE: '[data-tid="fedd10bf"]',
            BUTTON_CLOSE_1: '[data-tid="3c511207"]',
            BUTTON_CLOSE_JOB_NUMBER_MODAL: '[data-tid="6c54c85c"]',
            BUTTON_COLLAPSE_ALL: '[data-tid="93c88fe7"]',
            BUTTON_COMPARE_SUBMIT: '[data-tid="a693a448"]',
            BUTTON_CONFIRM: '[data-tid="1a0817b4"]',
            BUTTON_DELETE: '[data-tid="b7f1f830"]',
            BUTTON_DETAIL: '[data-tid="42e32331"]',
            BUTTON_EXPAND_ALL: '[data-tid="ba9c5ec6"]',
            BUTTON_KEYWORD_SUBMIT: '[data-tid="5d27b826"]',
            BUTTON_MOVE_DOWN: '[data-tid="dadf2339"]',
            BUTTON_MOVE_UP: '[data-tid="dab3e773"]',
            BUTTON_OPEN_MODAL_LAW_ALARM_SETTING: '[data-tid="d3b99da1"]',
            BUTTON_REMOVE: '[data-tid="28f01699"]',
            BUTTON_RETRY: '[data-tid="c8187956"]',
            BUTTON_SAVE_JOB_NUMBER: '[data-tid="2161219a"]',
            BUTTON_SEARCH_JOB_NUMBER: '[data-tid="11ef1969"]',
            BUTTON_SUBMIT: '[data-tid="08cad8a6"]',
            BUTTON_TOGGLE: '[data-tid="65cf46c6"]',
            BUTTON_U_TEAM: '[data-tid="2e92709f"]',
            BUTTON_U_TEAM_NAME: '[data-tid="81dca728"]',
            BUTTON_ZOOM_IN: '[data-tid="7c6108a8"]',
            BUTTON_ZOOM_OUT: '[data-tid="a45716e4"]',
            CHECKBOX: '[data-tid="c36398e7"]',
            CHECKBOX_1: '[data-tid="a53589bf"]',
            INPUT: '[data-tid="f49b8e47"]',
            INPUT_1: '[data-tid="739f6b9d"]',
            INPUT_2: '[data-tid="ad59cbd7"]',
            INPUT_3: '[data-tid="f894c1b0"]',
            INPUT_4: '[data-tid="39cd5363"]',
            INPUT_5: '[data-tid="f1965398"]',
            INPUT_6: '[data-tid="85cd841a"]',
            INPUT_7: '[data-tid="1ec563a7"]',
            INPUT_8: '[data-tid="641e45e9"]',
            INPUT_DO_NOT_SHOW_AGAIN: '[data-tid="89f3e73c"]',
            INPUT_FILE: '[data-tid="04146334"]',
            INPUT_JOB_NAME: '[data-tid="5e940d17"]',
            INPUT_JOB_NO: '[data-tid="84bf7669"]',
            INPUT_SEARCH: '[data-tid="ce7fd17b"]',
            INPUT_SEARCH_CONTACT: '[data-tid="9421e40c"]',
            INPUT_TITLE_SEARCH: '[data-tid="8f941071"]',
            PAGINATION: '[data-tid="fc999215"]',
            PAGINATION_JOB_NUMBER: '[data-tid="10e881ed"]',
            RADIO: '[data-tid="312cc1b9"]',
            RADIO_1: '[data-tid="d9dd6fc2"]',
            RADIO_2: '[data-tid="e3600f34"]',
            RADIO_3: '[data-tid="eacf476a"]',
            RADIO_4: '[data-tid="c4e1accf"]',
            RADIO_5: '[data-tid="8d9bb5f5"]',
            RADIO_6: '[data-tid="746833e0"]',
            SELECT: '[data-tid="c829a9e2"]',
            SELECT_1: '[data-tid="a9ef7fd5"]',
            TEXTAREA: '[data-tid="a96ecc36"]',
        },

        NOTICE: {
            BUTTON: '[data-tid="708db741"]',
            BUTTON_CLICK_LIST_BUTTON: '[data-tid="3278162c"]',
            PAGINATION: '[data-tid="cdd414bb"]',
        },

        PC: {
            BUTTON: '[data-tid="da3d4e02"]',
            BUTTON_1: '[data-tid="b55d4a05"]',
            BUTTON_CANCEL_EDIT_NAME: '[data-tid="b759254f"]',
            BUTTON_CLICK_CHECK_AUTH: '[data-tid="331a2a2c"]',
            BUTTON_CLICK_DELETE: '[data-tid="8f816574"]',
            BUTTON_CLICK_DELETE_DEPARTMENT: '[data-tid="432e973c"]',
            BUTTON_CLICK_EDIT_DEPARTMENT: '[data-tid="a1ce3776"]',
            BUTTON_CLICK_INVITE: '[data-tid="f74fb7f1"]',
            BUTTON_CLICK_MOVE_CFS: '[data-tid="dde2c2f8"]',
            BUTTON_CLICK_NAME: '[data-tid="960e0155"]',
            BUTTON_CLICK_REGISTER: '[data-tid="44f0d65c"]',
            BUTTON_CLICK_REMOVE_CFS: '[data-tid="31ceabea"]',
            BUTTON_CLICK_SEND_AUTH: '[data-tid="0adf6163"]',
            BUTTON_CLOSE: '[data-tid="74925ebf"]',
            BUTTON_CLOSE_1: '[data-tid="85a854e9"]',
            BUTTON_CLOSE_MODAL: '[data-tid="53cb2583"]',
            BUTTON_CLOSE_MODAL_1: '[data-tid="ea8f7627"]',
            BUTTON_COLLAPSE_ALL: '[data-tid="8928990d"]',
            BUTTON_CREATE_TEAM: '[data-tid="82f5b915"]',
            BUTTON_DELETE: '[data-tid="23ac9294"]',
            BUTTON_EXPAND_ALL: '[data-tid="733687b1"]',
            BUTTON_IS_USER_NODE: '[data-tid="da19cc18"]',
            BUTTON_MOVE_TO_RESET_PASSWORD: '[data-tid="c660e9d8"]',
            BUTTON_OPEN_2FA_MODAL: '[data-tid="74a51a3e"]',
            BUTTON_OPEN_MANAGE_DEPART_MENT: '[data-tid="9246af00"]',
            BUTTON_OPEN_MODAL: '[data-tid="97e98a44"]',
            BUTTON_OPEN_MODAL_1: '[data-tid="e2af7030"]',
            BUTTON_OPEN_MOVE_MODAL: '[data-tid="9acc6036"]',
            BUTTON_SAVE: '[data-tid="171e9983"]',
            BUTTON_SAVE_NAME: '[data-tid="41460141"]',
            BUTTON_SHOW_ALL_MEMBER: '[data-tid="4b166d4a"]',
            BUTTON_SHOW_INVITE_MODAL: '[data-tid="2a6550d9"]',
            BUTTON_SSO_LOGIN: '[data-tid="f3a8c2e1"]',
            BUTTON_SUBMIT: '[data-tid="7b7d3f69"]',
            CHECKBOX: '[data-tid="5a86b11e"]',
            CHECKBOX_1: '[data-tid="c9002387"]',
            CHECKBOX_2: '[data-tid="eb9bd0a3"]',
            INPUT: '[data-tid="499a6556"]',
            INPUT_1: '[data-tid="6eefdd0b"]',
            INPUT_2: '[data-tid="b8f6fcc5"]',
            INPUT_3: '[data-tid="32748916"]',
            INPUT_4: '[data-tid="d7cea234"]',
            INPUT_5: '[data-tid="648dae71"]',
            INPUT_6: '[data-tid="c68e17e9"]',
            INPUT_7: '[data-tid="396e4220"]',
            INPUT_BUSINESS_REMEMBER_USER_EMAIL_CHECKBOX_PC: '[data-tid="e1b48975"]',
            INPUT_FILE: '[data-tid="674e21d2"]',
            INPUT_FILE_UPLOAD: '[data-tid="85042a05"]',
            INPUT_SEARCH: '[data-tid="f6beb6f9"]',
            INPUT_TITLE_SEARCH: '[data-tid="7125e91a"]',
            PAGINATION: '[data-tid="0c995bd9"]',
            RADIO: '[data-tid="42257f01"]',
            RADIO_1: '[data-tid="3213160e"]',
            RADIO_2: '[data-tid="97275bcd"]',
            RADIO_3: '[data-tid="de3aff47"]',
            RADIO_4: '[data-tid="61266d14"]',
            RADIO_5: '[data-tid="0cc45879"]',
            RADIO_6: '[data-tid="4fadeba5"]',
            SELECT: '[data-tid="991a33b9"]',
            SELECT_1: '[data-tid="e924747a"]',
            SELECT_2: '[data-tid="602abc54"]',
            SELECT_3: '[data-tid="36ef0d00"]',
            SELECT_4: '[data-tid="bc039245"]',
            SELECT_5: '[data-tid="d83bebfc"]',
            SELECT_6: '[data-tid="bfcb772f"]',
            SELECT_7: '[data-tid="5cf8ff0a"]',
            SELECT_8: '[data-tid="fe10f584"]',
            SELECT_9: '[data-tid="2ac0d857"]',
            SELECT_10: '[data-tid="d1dbe040"]',
            SELECT_11: '[data-tid="bb23e505"]',
            SELECT_12: '[data-tid="49f87a27"]',
            SELECT_13: '[data-tid="a318216c"]',
            SELECT_14: '[data-tid="44aed4f7"]',
        },

        PROJECT: {
            BUTTON: '[data-tid="b14d4a2f"]',
            BUTTON_CREATE: '[data-tid="9d2da031"]',
            CHECKBOX: '[data-tid="fd0cc329"]',
            CHECKBOX_1: '[data-tid="159a2b0c"]',
            INPUT: '[data-tid="bfe313c9"]',
            INPUT_TITLE_SEARCH: '[data-tid="2b14a141"]',
            PAGINATION: '[data-tid="b6e047af"]',
            SELECT: '[data-tid="77889e93"]',
            SELECT_1: '[data-tid="f75b4ca5"]',
            SELECT_2: '[data-tid="4fbd74fb"]',
        },

        RESET_PASSWORD: {
            BUTTON_CLICK_CODE_CONFIRM_BUTTON: '[data-tid="c0cf24b5"]',
            BUTTON_CLICK_LOGIN: '[data-tid="9fc19ad3"]',
            BUTTON_CLICK_NEXT_STEP: '[data-tid="2b173daf"]',
            BUTTON_CLICK_SEND_CODE: '[data-tid="4c17900e"]',
            BUTTON_CLICK_SUBMIT: '[data-tid="44b8fadc"]',
            INPUT: '[data-tid="45c42ba5"]',
            INPUT_1: '[data-tid="69c9b355"]',
            INPUT_2: '[data-tid="af25718d"]',
        },

        SEAL: {
            BUTTON: '[data-tid="eb37816c"]',
            BUTTON_1: '[data-tid="a403a5ca"]',
            BUTTON_2: '[data-tid="b2552e1c"]',
            BUTTON_APPROVE: '[data-tid="76b05bcf"]',
            BUTTON_CHANGE: '[data-tid="ad5d4d16"]',
            BUTTON_CLICK_EDIT_BTN: '[data-tid="5c3f29e6"]',
            BUTTON_CLOSE: '[data-tid="3ff409fc"]',
            BUTTON_REJECT: '[data-tid="0cbe812f"]',
            BUTTON_SUBMIT: '[data-tid="e6a0c5e4"]',
            DATEPICKER: '[data-tid="fed835ac"]',
            INPUT: '[data-tid="1ef27346"]',
            INPUT_1: '[data-tid="0f3ca62d"]',
            INPUT_2: '[data-tid="382eeb7a"]',
            RADIO: '[data-tid="4e0c0187"]',
            RADIO_1: '[data-tid="66d69fdd"]',
            RADIO_2: '[data-tid="ab004070"]',
            RADIO_3: '[data-tid="bcb0c66d"]',
            RADIO_4: '[data-tid="b7cb38e6"]',
            RADIO_5: '[data-tid="6a4c32e9"]',
            SELECT: '[data-tid="f0df791f"]',
            TEXTAREA: '[data-tid="d05826b2"]',
        },

        SETUP: {
            BUTTON: '[data-tid="5ee46f9e"]',
            BUTTON_1: '[data-tid="a770d644"]',
            BUTTON_CLICK_ADD: '[data-tid="ef209783"]',
            BUTTON_CLICK_CREATE: '[data-tid="de8679f2"]',
            BUTTON_CLICK_SAVE: '[data-tid="e5228f3f"]',
            BUTTON_DELETE: '[data-tid="3100c574"]',
            BUTTON_SUBMIT: '[data-tid="541d4197"]',
            CHECKBOX: '[data-tid="840152a2"]',
            CHECKBOX_1: '[data-tid="0ad05af3"]',
            INPUT: '[data-tid="f1e367e8"]',
            RADIO: '[data-tid="1b9c5e0f"]',
            RADIO_1: '[data-tid="65cb1d44"]',
            RADIO_2: '[data-tid="9b1fb3ab"]',
            RADIO_3: '[data-tid="3ffbe9b0"]',
            RADIO_4: '[data-tid="6691df7e"]',
            RADIO_5: '[data-tid="7b5d9ba5"]',
            RADIO_6: '[data-tid="7a97af2b"]',
            RADIO_7: '[data-tid="5f65797e"]',
            RADIO_8: '[data-tid="9f188b65"]',
            RADIO_9: '[data-tid="5277ecbb"]',
            RADIO_10: '[data-tid="bbbd1b0a"]',
            RADIO_11: '[data-tid="3558a02a"]',
            SELECT: '[data-tid="c940580b"]',
            SELECT_1: '[data-tid="9b050dab"]',
            SELECT_2: '[data-tid="9bd103cb"]',
            SELECT_3: '[data-tid="b89367c7"]',
            SELECT_MAX_SESSION_MOBILE: '[data-tid="4a154f2f"]',
            SELECT_MAX_SESSION_PC: '[data-tid="7ea4032d"]',
            SELECT_SELECTED_DAY: '[data-tid="de2a486b"]',
            SELECT_SELECTED_HOUR: '[data-tid="4f2f5e6c"]',
        },

        SIGNUP: {
            BUTTON: '[data-tid="2651e793"]',
            BUTTON_CLICK_SIGNUP: '[data-tid="d2cdaa43"]',
            BUTTON_SUBMIT_AUTH: '[data-tid="e2799fc4"]',
            INPUT: '[data-tid="5733e024"]',
            INPUT_1: '[data-tid="781502c1"]',
        },

        STATISTICS: {
            BUTTON: '[data-tid="d9a6ec3d"]',
            PAGINATION: '[data-tid="a683533d"]',
            RADIO: '[data-tid="d7a502f9"]',
            RADIO_1: '[data-tid="a4bc3899"]',
            RADIO_2: '[data-tid="96b05ff7"]',
            RADIO_3: '[data-tid="a9389871"]',
            SELECT: '[data-tid="4c93b593"]',
            SELECT_1: '[data-tid="b329521c"]',
            SELECT_2: '[data-tid="69905b3b"]',
            SELECT_3: '[data-tid="393f5368"]',
            SELECT_4: '[data-tid="3215bf40"]',
            SELECT_5: '[data-tid="6c296a4c"]',
            SELECT_6: '[data-tid="78204ef9"]',
        },

        TEAM_STANDARD_CONTRACT: {
            BUTTON: '[data-tid="32c8b8a9"]',
            BUTTON_1: '[data-tid="971ceff4"]',
            BUTTON_CLICK_SAVE_BTN: '[data-tid="9bdfa1e2"]',
            BUTTON_SUBMIT: '[data-tid="7a931b93"]',
            INPUT: '[data-tid="f21d5170"]',
            INPUT_1: '[data-tid="52cafeeb"]',
            INPUT_TITLE_SEARCH: '[data-tid="a7454078"]',
            RADIO: '[data-tid="29be50d2"]',
            SELECT: '[data-tid="a89030cf"]',
            SELECT_1: '[data-tid="0c5928e4"]',
        },

        TEAMS: {
            BUTTON: '[data-tid="af1a3d69"]',
            BUTTON_1: '[data-tid="e62aaf43"]',
            BUTTON_2: '[data-tid="eeac8055"]',
            INPUT: '[data-tid="f1353144"]',
        },

        TEMPLATE: {
            BUTTON: '[data-tid="410e8df9"]',
            BUTTON_1: '[data-tid="bb823751"]',
            BUTTON_2: '[data-tid="0a8e5588"]',
            BUTTON_CLICK_DELETE: '[data-tid="f653fd0f"]',
            BUTTON_CLICK_EDIT: '[data-tid="b856ce7b"]',
            BUTTON_TOGGLE_MENU: '[data-tid="87c2fa49"]',
        },

        UI: {
            BUTTON: '[data-tid="a6c5826f"]',
            BUTTON_1: '[data-tid="bf0c6dc0"]',
            BUTTON_DECREASE_MONTH: '[data-tid="5030ab02"]',
            BUTTON_INCREASE_MONTH: '[data-tid="e1261689"]',
            BUTTON_TOGGLE_VISIBLE: '[data-tid="f6b7885e"]',
            INPUT: '[data-tid="82a09d72"]',
            INPUT_1: '[data-tid="0aef4344"]',
            INPUT_SEARCH: '[data-tid="939b9bc8"]',
            SELECT: '[data-tid="08ade09c"]',
            SELECT_1: '[data-tid="6e2a09ef"]',
            TEXTAREA: '[data-tid="e56ccf47"]',
        },
    },

    // =========================================================
    // WEB
    // =========================================================
    WEB: {

        ERROR: {
            BUTTON: '[data-tid="37dffc30"]',
        },

        ESIGN: {
            BUTTON: '[data-tid="51f89476"]',
            BUTTON_1: '[data-tid="7ed5f9d4"]',
            BUTTON_2: '[data-tid="4f2dd8ab"]',
            BUTTON_3: '[data-tid="d288e13d"]',
            BUTTON_CLICK_CALLBACK: '[data-tid="5d5e6074"]',
            BUTTON_NEXT_CLICK_CALLBACK: '[data-tid="93b8e91a"]',
            BUTTON_PREVIOUS_CLICK_CALLBACK: '[data-tid="747c5b4c"]',
            INPUT: '[data-tid="c7197697"]',
            INPUT_1: '[data-tid="cff2d231"]',
            INPUT_2: '[data-tid="211d984d"]',
            INPUT_3: '[data-tid="5f548335"]',
            INPUT_4: '[data-tid="7fe4c7db"]',
            INPUT_5: '[data-tid="32855fff"]',
            INPUT_6: '[data-tid="98da9038"]',
            INPUT_7: '[data-tid="827ccdd3"]',
            INPUT_FILE: '[data-tid="71f186c6"]',
            TEXTAREA: '[data-tid="fe4cdf16"]',
        },

        MAGAZINE_FLOATING_BUTTONS: {
            BUTTON: '[data-tid="187e0750"]',
            BUTTON_1: '[data-tid="ae8a125b"]',
            BUTTON_2: '[data-tid="dd593ba1"]',
            BUTTON_3: '[data-tid="5a576c06"]',
            BUTTON_4: '[data-tid="0247fb23"]',
            BUTTON_CLICK_RELATIVE_DOCUMENT: '[data-tid="3ff5e3ee"]',
            BUTTON_CLICK_RELATIVE_DOCUMENT_1: '[data-tid="d8fd473e"]',
            BUTTON_CLICK_SHARE: '[data-tid="86f3f95d"]',
        },

        MAGAZINE_RELATIVE_DOCUMENTS: {
            BUTTON_CLICK_CLOSE: '[data-tid="a1e9b524"]',
            BUTTON_CLICK_CLOSE_1: '[data-tid="610b43d5"]',
        },

        MAIN: {
            BUTTON: '[data-tid="6c8f8d5f"]',
            BUTTON_1: '[data-tid="f4f45ed7"]',
            BUTTON_2: '[data-tid="6712a46b"]',
            BUTTON_3: '[data-tid="7914cecb"]',
            BUTTON_4: '[data-tid="825c5c3d"]',
            BUTTON_5: '[data-tid="a80c125d"]',
            BUTTON_6: '[data-tid="39a15149"]',
            BUTTON_7: '[data-tid="e077f830"]',
            BUTTON_8: '[data-tid="2a75bc72"]',
            BUTTON_9: '[data-tid="e3c7390c"]',
            BUTTON_10: '[data-tid="75b1c5d2"]',
            BUTTON_11: '[data-tid="b6051d82"]',
            BUTTON_12: '[data-tid="d002b6ad"]',
            BUTTON_51: '[data-tid="6d63a711"]',
            BUTTON_52: '[data-tid="b4c6aba2"]',
            BUTTON_100: '[data-tid="c3410439"]',
            BUTTON_1000: '[data-tid="4e6fdee0"]',
            BUTTON_AI: '[data-tid="6cf41137"]',
            BUTTON_CHAT_GLD: '[data-tid="f0f745b5"]',
            BUTTON_CLICK: '[data-tid="986a477e"]',
            BUTTON_CLICK_1: '[data-tid="90ad95d2"]',
            BUTTON_CLICK_BENEFIT: '[data-tid="80be71e4"]',
            BUTTON_CLICK_CERTIFICATE: '[data-tid="c6d395aa"]',
            BUTTON_CLICK_CERTIFICATE_1: '[data-tid="f82da493"]',
            BUTTON_CLICK_NEXT: '[data-tid="457f0123"]',
            BUTTON_CLICK_PLUS: '[data-tid="e138b020"]',
            BUTTON_CLICK_PREV: '[data-tid="9989b526"]',
            BUTTON_CLICK_RECEIVE: '[data-tid="b6288e2f"]',
            BUTTON_CLICK_RECEIVE_1: '[data-tid="2d288e5d"]',
            BUTTON_CLICK_RELOAD: '[data-tid="851a94ed"]',
            BUTTON_CLICK_REMOVE: '[data-tid="90352e92"]',
            BUTTON_CLICK_REMOVE_1: '[data-tid="6618f415"]',
            BUTTON_CLICK_SHARE: '[data-tid="8aa2acd6"]',
            BUTTON_CLICK_SHARE_1: '[data-tid="5f093084"]',
            BUTTON_CLICK_VIDEO_LIST: '[data-tid="2076d707"]',
            BUTTON_CLICK_VIDEO_LIST_1: '[data-tid="b7caed7e"]',
            BUTTON_CLOSE: '[data-tid="24ce3ef8"]',
            BUTTON_GIVE_7_DAYS_FREE_VOUCHER: '[data-tid="be04257e"]',
            BUTTON_HASH_TAG: '[data-tid="10b9f660"]',
            BUTTON_MOVE_CEO_CERTIFICATE: '[data-tid="e6ae8467"]',
            BUTTON_MOVE_CEO_CERTIFICATE_1: '[data-tid="b20f98a5"]',
            BUTTON_NBSP: '[data-tid="000b480e"]',
            BUTTON_NEXT: '[data-tid="7c4000b9"]',
            BUTTON_PREVIOUS: '[data-tid="a30c30bd"]',
            BUTTON_SIGNUP: '[data-tid="48983a94"]',
            BUTTON_SUBMIT: '[data-tid="6dd64d0d"]',
            BUTTON_SUBMIT_1: '[data-tid="a793b65a"]',
            BUTTON_TITLE_SEARCH: '[data-tid="1332cdff"]',
            INPUT: '[data-tid="455165ea"]',
            INPUT_1: '[data-tid="b7465a04"]',
            INPUT_2: '[data-tid="5841026e"]',
            INPUT_3: '[data-tid="49210ccc"]',
            INPUT_4: '[data-tid="87dc15dd"]',
            INPUT_5: '[data-tid="ca9ecc19"]',
            INPUT_6: '[data-tid="b2fab77c"]',
            INPUT_7: '[data-tid="c2527beb"]',
            INPUT_8: '[data-tid="bd230f37"]',
            INPUT_EMAIL: '[data-tid="c9ec98d1"]',
            INPUT_EMAIL_1: '[data-tid="fa6c7e74"]',
            INPUT_SEARCH: '[data-tid="a341e3c2"]',
            INPUT_TITLE: '[data-tid="77358a35"]',
            INPUT_TODAY_CHECKBOX: '[data-tid="b6dbfb3c"]',
            PAGINATION: '[data-tid="a1dfb05a"]',
            SELECT: '[data-tid="7019df59"]',
            SELECT_1: '[data-tid="4155955b"]',
            TEXTAREA: '[data-tid="bc234efd"]',
        },

        MODALS: {
            BUTTON_CLOSE: '[data-tid="d59488c2"]',
            BUTTON_INQUIRY_CLICK: '[data-tid="78105e38"]',
        },

        OVERLAY: {
            BUTTON_SUBMIT: '[data-tid="2b770063"]',
            BUTTON_SUBMIT_1: '[data-tid="14502422"]',
            INPUT: '[data-tid="b48c32b9"]',
        },

        PAGES: {
            BUTTON: '[data-tid="53178cd5"]',
            BUTTON_1: '[data-tid="db0cc297"]',
        },

        PRESS: {
            BUTTON: '[data-tid="cc4bac5b"]',
            BUTTON_IS_FETCHING: '[data-tid="dac843b1"]',
            PAGINATION: '[data-tid="17aa26f9"]',
            SELECT: '[data-tid="e9259708"]',
            SELECT_1: '[data-tid="5ac7b6aa"]',
        },

        TABLELISTS: {
            INPUT_FILE_UPLOAD: '[data-tid="5505bdd4"]',
        },
    },

    // =========================================================
    // SHARED_UI
    // =========================================================
    SHARED_UI: {

        BUSINESS: {
            BUTTON: '[data-tid="0d747b6e"]',
            BUTTON_1: '[data-tid="74b3663e"]',
            BUTTON_CLICK_OPEN_MENU_MODAL: '[data-tid="bbb411ab"]',
            BUTTON_CLICK_SHARE: '[data-tid="e6b0cd8f"]',
            BUTTON_CLICK_SHARE_1: '[data-tid="252a5364"]',
            BUTTON_CLOSE: '[data-tid="466c955a"]',
        },

        COMPONENTS: {
            BUTTON: '[data-tid="c946b59b"]',
            BUTTON_1: '[data-tid="90df18ec"]',
            BUTTON_2: '[data-tid="0932dd57"]',
            BUTTON_CLICK_BACK_STEP: '[data-tid="89492c5a"]',
            BUTTON_CLICK_BTN: '[data-tid="dbf4c6b4"]',
            BUTTON_CLICK_CHECKED: '[data-tid="a3d3f427"]',
            BUTTON_CLICK_CONFIRM: '[data-tid="d31c7db2"]',
            BUTTON_CLICK_DOWNLOAD: '[data-tid="7cb753fe"]',
            BUTTON_CLICK_RADIO_ITEM: '[data-tid="0e72b104"]',
            BUTTON_CLICK_SEARCH: '[data-tid="f7e1579a"]',
            BUTTON_CLICK_SELECT_DATA: '[data-tid="9011593c"]',
            BUTTON_CLICK_SELECT_OPTION: '[data-tid="f4b9f144"]',
            BUTTON_CLICK_SUBMIT: '[data-tid="b0873fde"]',
            BUTTON_CLICK_SUBMIT_BTN: '[data-tid="e5eb7ee6"]',
            BUTTON_CLICK_TOGGLE: '[data-tid="9dd36413"]',
            BUTTON_CLICK_TOGGLE_OPEN: '[data-tid="c038d836"]',
            BUTTON_CLOSE: '[data-tid="38f433ad"]',
            BUTTON_CLOSE_MODAL: '[data-tid="4b7c4bd9"]',
            BUTTON_CONFIRM: '[data-tid="14aba8bc"]',
            BUTTON_DECREASE_MONTH: '[data-tid="15ace69b"]',
            BUTTON_DELETE: '[data-tid="2f8e854c"]',
            BUTTON_ICON: '[data-tid="8368e80c"]',
            BUTTON_INCREASE_MONTH: '[data-tid="1d3ee126"]',
            BUTTON_IS_LOADING_CHILDREN: '[data-tid="19d1e81b"]',
            BUTTON_REMOVE: '[data-tid="408a7913"]',
            BUTTON_SELECT_OPTION: '[data-tid="51fbeeed"]',
            BUTTON_SUBMIT: '[data-tid="5169a4a3"]',
            BUTTON_TOGGLE_VISIBLE: '[data-tid="0557ade0"]',
            DATEPICKER: '[data-tid="4ca70030"]',
            DATEPICKER_1: '[data-tid="d0e5cd3b"]',
            INPUT: '[data-tid="359ffc54"]',
            INPUT_1: '[data-tid="6681b660"]',
            INPUT_2: '[data-tid="2dd10181"]',
            INPUT_3: '[data-tid="880f872c"]',
            INPUT_4: '[data-tid="5d5745af"]',
            INPUT_5: '[data-tid="a291f0fd"]',
            INPUT_SEARCH: '[data-tid="93dcced6"]',
            RADIO: '[data-tid="dbbb9f69"]',
            RADIO_1: '[data-tid="846e28b1"]',
            SELECT: '[data-tid="719d7ce2"]',
            SELECT_1: '[data-tid="73cd92e0"]',
            SELECT_2: '[data-tid="4d445e4e"]',
            SELECT_3: '[data-tid="9af1b4a5"]',
            TEXTAREA: '[data-tid="0c6a0f14"]',
        },

        MODALS: {
            BUTTON: '[data-tid="b88e1095"]',
            BUTTON_1: '[data-tid="7fa30a21"]',
            BUTTON_2: '[data-tid="780c2ec0"]',
            BUTTON_3: '[data-tid="79cd2c55"]',
            BUTTON_4: '[data-tid="1a183ee7"]',
            BUTTON_5: '[data-tid="45d5061c"]',
            BUTTON_14: '[data-tid="de3af7f6"]',
            BUTTON_ALL_AGREE: '[data-tid="6ce8f0b5"]',
            BUTTON_CLICK: '[data-tid="969f2900"]',
            BUTTON_CLICK_ACTION: '[data-tid="d5c8e8a8"]',
            BUTTON_CLICK_ACTION_1: '[data-tid="55c68977"]',
            BUTTON_CLICK_CANCEL: '[data-tid="dacb7ad2"]',
            BUTTON_CLICK_CHECK_PHONE_AUTH_CODE: '[data-tid="2f52a8cc"]',
            BUTTON_CLICK_CLEAR_BTN: '[data-tid="4a2fab97"]',
            BUTTON_CLICK_CLOSE: '[data-tid="856a8a0f"]',
            BUTTON_CLICK_CLOSE_1: '[data-tid="43e742f4"]',
            BUTTON_CLICK_COMPLETE_BUTTON: '[data-tid="e89a2763"]',
            BUTTON_CLICK_CONFIRM: '[data-tid="add3cf53"]',
            BUTTON_CLICK_DETAIL_BUTTON: '[data-tid="22bfd975"]',
            BUTTON_CLICK_DOWNLOAD: '[data-tid="480b94e2"]',
            BUTTON_CLICK_HIDE_BUTTON: '[data-tid="32ddbc80"]',
            BUTTON_CLICK_LOGIN_BUTTON: '[data-tid="60867958"]',
            BUTTON_CLICK_NEXT_STEP: '[data-tid="49834dd1"]',
            BUTTON_CLICK_NOTICE: '[data-tid="2da389e7"]',
            BUTTON_CLICK_PREVIOUS: '[data-tid="a8f0c508"]',
            BUTTON_CLICK_RESULT: '[data-tid="47b731d4"]',
            BUTTON_CLICK_SAVE_BUTTON: '[data-tid="a5564a92"]',
            BUTTON_CLICK_SET_MANAGE_DOCS: '[data-tid="1cbce1cc"]',
            BUTTON_CLICK_SETTING_WATERMARK: '[data-tid="cd8cce98"]',
            BUTTON_CLOSE: '[data-tid="7b297c53"]',
            BUTTON_CLOSE_1: '[data-tid="891b0e9a"]',
            BUTTON_CLOSE_MODAL: '[data-tid="8f66bdbd"]',
            BUTTON_CONFIRM: '[data-tid="10ca662b"]',
            BUTTON_DOWNLOAD: '[data-tid="c4e24d82"]',
            BUTTON_DOWNLOAD_WITH_WATERMARK: '[data-tid="67154546"]',
            BUTTON_MODAL_CLOSE: '[data-tid="d6eb6f8e"]',
            BUTTON_MODAL_CLOSE_1: '[data-tid="998af835"]',
            BUTTON_NBSP: '[data-tid="972cc3bc"]',
            BUTTON_NBSP_1: '[data-tid="f62e146c"]',
            BUTTON_PHONE_NUMBER_AUTH: '[data-tid="8bef6af2"]',
            BUTTON_PURCHASE: '[data-tid="ae81d126"]',
            BUTTON_RESET: '[data-tid="7321354a"]',
            BUTTON_SUBMIT: '[data-tid="531b11f7"]',
            BUTTON_SUCCESS: '[data-tid="9b854161"]',
            BUTTON_USE_PERMISSION: '[data-tid="eea1ae2f"]',
            BUTTON_USE_PERMISSION_1: '[data-tid="486fe7e1"]',
            CHECKBOX: '[data-tid="24156783"]',
            DATEPICKER: '[data-tid="155d4ed8"]',
            INPUT: '[data-tid="b520abef"]',
            INPUT_1: '[data-tid="8f8c57ad"]',
            INPUT_2: '[data-tid="4d293422"]',
            INPUT_3: '[data-tid="63b358cd"]',
            INPUT_4: '[data-tid="8bafe4be"]',
            INPUT_EMAIL: '[data-tid="e3bfad95"]',
            INPUT_NAME: '[data-tid="657b3666"]',
            INPUT_REAFFIRM: '[data-tid="d6f6f2ba"]',
            INPUT_SEARCH: '[data-tid="f46daf09"]',
            INPUT_SEARCH_MANAGER: '[data-tid="f0b99044"]',
            INPUT_WORD: '[data-tid="8690e4c0"]',
            PAGINATION: '[data-tid="a2626b49"]',
            RADIO: '[data-tid="ce274cf3"]',
            RADIO_1: '[data-tid="5d9639bd"]',
            SELECT: '[data-tid="fdb19ea0"]',
            SELECT_1: '[data-tid="1b791bf0"]',
        },

        POLARIS: {
            BUTTON: '[data-tid="b95b3d69"]',
            BUTTON_1: '[data-tid="370ca3a9"]',
            BUTTON_2: '[data-tid="7e541d81"]',
            BUTTON_3: '[data-tid="adea11ea"]',
            BUTTON_CANCEL: '[data-tid="530006cf"]',
            BUTTON_CLICK: '[data-tid="e9efc148"]',
            BUTTON_CLICK_CLOSE: '[data-tid="cb0b2886"]',
            BUTTON_CLICK_FAVORITE: '[data-tid="5423930a"]',
            BUTTON_CLICK_FAVORITE_1: '[data-tid="c4ef6b90"]',
            BUTTON_CLICK_GO_BACK: '[data-tid="2d0f4a9f"]',
            BUTTON_CLICK_GUID: '[data-tid="2177ca57"]',
            BUTTON_CLICK_GUIDE: '[data-tid="0fda7a5c"]',
            BUTTON_CLICK_HISTORY_BTN: '[data-tid="fcae3c1b"]',
            BUTTON_CLICK_LAWYER_REVIEW: '[data-tid="9846d3b8"]',
            BUTTON_CLICK_RETURN_AUTODOC: '[data-tid="ff2ddd82"]',
            BUTTON_CLICK_SAVE: '[data-tid="092dfd79"]',
            BUTTON_CLICK_SETTING_WATERMARK: '[data-tid="4ccf4640"]',
            BUTTON_CLICK_SIGN: '[data-tid="e063b1a3"]',
            BUTTON_CLOSE: '[data-tid="f75765b7"]',
            BUTTON_CLOSE_DOCX_TEXT: '[data-tid="8c7168c7"]',
            BUTTON_COMPOSE_PDF: '[data-tid="04619260"]',
            BUTTON_CONFIRM: '[data-tid="09d75759"]',
            BUTTON_EXPORT_DOCX: '[data-tid="1024fbd1"]',
            BUTTON_EXPORT_HTML: '[data-tid="7cc66f4c"]',
            BUTTON_EXPORT_HWP: '[data-tid="923f9831"]',
            BUTTON_EXPORT_PDF: '[data-tid="cbf5815d"]',
            BUTTON_EXPORT_TEXT: '[data-tid="5a80b098"]',
            BUTTON_OPEN_DOWNLOAD_MODAL: '[data-tid="4fc1edfb"]',
            BUTTON_OPEN_HISTORY_MODAL: '[data-tid="68db712f"]',
            BUTTON_OPEN_HTML_STRING_MODAL: '[data-tid="52782af6"]',
            BUTTON_OPEN_SHARE_MODAL: '[data-tid="0ecaf682"]',
            BUTTON_PRINT: '[data-tid="e3168d6f"]',
            BUTTON_REQUEST_CLM: '[data-tid="613ff13f"]',
            BUTTON_SUBMIT_STRING_HTML: '[data-tid="7471f3ee"]',
            BUTTON_SUBMIT_STRING_HTML_SEPARATE_TABLE: '[data-tid="3ad9c9b2"]',
            BUTTON_TOGGLE_FOLD: '[data-tid="3b098989"]',
            BUTTON_TOGGLE_LOG_PANEL: '[data-tid="538ade10"]',
            BUTTON_TOGGLE_MEMO: '[data-tid="9341cd3e"]',
            BUTTON_TOGGLE_VIEW_XML: '[data-tid="78a7a943"]',
            INPUT: '[data-tid="090c32d3"]',
            INPUT_1: '[data-tid="7dccffc5"]',
            INPUT_FILE: '[data-tid="157dc984"]',
            INPUT_FILE_SEAL: '[data-tid="3c2439c3"]',
            INPUT_FILE_UPLOAD: '[data-tid="02436c92"]',
            RADIO: '[data-tid="83e9c94a"]',
            RADIO_1: '[data-tid="5627f699"]',
            SELECT: '[data-tid="1875619c"]',
            SELECT_1: '[data-tid="82372e1b"]',
            TEXTAREA: '[data-tid="1e1ea743"]',
            TEXTAREA_1: '[data-tid="16bb9b3a"]',
        },

        VIEWER: {
            BUTTON_ZOOM_IN: '[data-tid="6bfa0d74"]',
            BUTTON_ZOOM_OUT: '[data-tid="f069b013"]',
            INPUT: '[data-tid="87c66e7e"]',
        },

        WOORI: {
            BUTTON_CLOSE: '[data-tid="509bea1b"]',
            BUTTON_CLOSE_1: '[data-tid="09b9e907"]',
        },
    },
};
