// HSAD k6 browser 스크립트용 selector 모음
// shared-configs/tid/ JSON 파일 기반 [data-tid="..."] selector
// 네임스페이스: LOGIN / BUSINESS / WEB / SHARED_UI
export const SELECTORS = {

    // =========================================================
    // LOGIN
    // 고객사 SSO 화면은 data-tid가 없으므로 CUSTOMER_SSO에 외부 화면용 selector를 분리한다.
    // 우리 서비스 내부는 SERVICE부터 data-tid 기반 확인을 사용한다.
    // =========================================================
    LOGIN: {
        CUSTOMER_SSO: {
            EMAIL_INPUT: 'input[type="email"], input[name="email"], input[id="email"], input[name="username"], input[id="username"]',
            PASSWORD_INPUT: 'input[type="password"]',
            SUBMIT_BUTTON: 'button[type="submit"], input[type="submit"]',
        },
        SERVICE: {
            EMAIL_INPUT: 'input[id="email"]',
            PASSWORD_INPUT: 'input[id="password"]',
            SUBMIT_BUTTON: 'button[type="submit"]',
            LOGOUT: 'img[alt="이동"]',
            READY: '[data-tid]',
        },
        EMAIL_INPUT: 'input[id="email"]',
        PASSWORD_INPUT: 'input[id="password"]',
        SUBMIT_BUTTON: 'button[type="submit"]',
        LOGOUT: 'img[alt="이동"]',
    },

    // =========================================================
    // BUSINESS
    // =========================================================
    BUSINESS: {

        AD_REVIEW: {
            LOADING: '[data-tid="9de9a3cc"]',
        },

        AD_POST_REVIEW: {
            BUTTON: '[data-tid="12667a6a"]',
            ATTACH: '[data-tid="9da02279"]',
            ATTACH_1: '[data-tid="deb32926"]',
        },

        ADVICE: {
            NEW_REQUEST_BUTTON: '//button[text()="신규 자문 요청" and not(@disabled)]',
            CATEGORY_ARROW: '//img[@alt="arrow"]',
            BUTTON_RESEND: '[data-tid="681b905c"]',
            BUTTON_SUSPEND_ADVICE: '[data-tid="53adc555"]',
            BUTTON_COMPLETE_ADVICE: '[data-tid="b915e3d6"]',
            BUTTON_SEND_TO_REQUESTOR: '[data-tid="79561403"]',
            BUTTON_COMPLETE_ADVICE_1: '[data-tid="6ec53a84"]',
            BUTTON_SUSPEND_ADVICE_1: '[data-tid="e5e40799"]',
            BUTTON_SUSPEND_ADVICE_2: '[data-tid="7a5a1d34"]',
            BUTTON_DELETE: '[data-tid="804ab98e"]',
            BUTTON_EXCEL_DOWNLOAD: '[data-tid="59172ffe"]',
            BUTTON_CLICK_PREVIEW: '[data-tid="f428609d"]',
            BUTTON_CANCEL_REQUEST: '[data-tid="e4263213"]',
            BUTTON_CLICK_VIEWER_OR_DOWNLOAD: '[data-tid="31df8d00"]',
            BUTTON_DELETE_1: '[data-tid="726adf23"]',
            BUTTON_DOCX_IS_LOADING: '[data-tid="2b10a143"]',
            BUTTON_SAVE_COMPLETE: '[data-tid="b528025b"]',
            BUTTON_IS_OPEN: '[data-tid="532c4cc3"]',
            BUTTON_DISABLE_EDITOR: '[data-tid="6930de72"]',
            BUTTON_DOWNLOAD: '[data-tid="5276b0e9"]',
            BUTTON_PDF_IS_LOADING: '[data-tid="5be445a2"]',
            BUTTON_LIST: '[data-tid="bcd4d134"]',
            PAGE_TITLE: '[data-tid="ba82a05b"]',
            BUTTON_SAVE_COMPLETE_1: '[data-tid="1edabf88"]',
            BUTTON_SEND_TO_MANAGER: '[data-tid="0358177d"]',
            BUTTON_LIST_1: '[data-tid="4fd7e8b0"]',
            DATE_PLACEHOLDER: '[data-tid="aeb780b3"]',
            BUTTON_ADD: '[data-tid="c45ca4f2"]',
            LABEL_CHANGE: '[data-tid="141f18d9"]',
            INPUT_TITLE_SEARCH: '[data-tid="92c31d8f"]',
            PAGINATION: '[data-tid="27801ac7"]',
            LABEL_ATTACHMENT_METHOD: '[data-tid="34680ab0"]',
            RADIO_LOAD_FROM_CONTRACT: '[data-tid="380970f5"]',
            RADIO_EDITOR_USE: '[data-tid="88bd442d"]',
            RADIO_EDITOR_DISABLE: '[data-tid="79aa2f33"]',
            SELECT_CATEGORY_PLACEHOLDER: '[data-tid="26fb56d8"]',
            CONTENTS_PLACEHOLDER: '[data-tid="d61766c9"]',
            LABEL_FACTS: '[data-tid="31083cc9"]',
            LABEL_NOTE: '[data-tid="27fbaf59"]',
        },

        AI: {
            BUTTON_START_AI_REVIEW: '[data-tid="eb09fcbc"]',
            LABEL_FILE_SELECT: '[data-tid="d4f32ecd"]',
            LABEL_CONTRACT_TYPE: '[data-tid="38f0eb27"]',
        },

        BLOG: {
            BUTTON: '[data-tid="6cfba917"]',
            BUTTON_CLICK_BTN: '[data-tid="5362a9f1"]',
            BUTTON_CLICK_SHARE_BUTTON: '[data-tid="2d9cc096"]',
        },

        BULK: {
            TOTAL_BUTTON: '[data-tid="d9f133ee"]',
            CANCEL_REQUEST_BUTTON: '[data-tid="8898dd50"]',
            PARTICIPANT_INFO_TITLE: '[data-tid="005cfc99"]',
            RENAME_BUTTON: '[data-tid="5b8c4261"]',
            RENAME_BUTTON_1: '[data-tid="e2cbbd38"]',
            PREV_BUTTON: '[data-tid="68a7526d"]',
            BUTTON_CLICK: '[data-tid="ed915f47"]',
            DOWNLOAD_EXCEL_BUTTON: '[data-tid="9110874e"]',
            MODAL_TITLE: '[data-tid="4064f48d"]',
            CANCEL_BUTTON: '[data-tid="e9a0db9f"]',
            PHONE_LABEL: '[data-tid="a8e6b0a5"]',
            DELETE_BUTTON: '[data-tid="00e4c717"]',
            DOWNLOAD_FILE_BUTTON: '[data-tid="d8c5c464"]',
            CANCEL_BUTTON_1: '[data-tid="c93da1f2"]',
            BULK_TRANSFER_LABEL: '[data-tid="5a60059d"]',
            LIST_BUTTON: '[data-tid="e3192a88"]',
            PREV_BUTTON_1: '[data-tid="70ee490d"]',
            PREV_BUTTON_2: '[data-tid="9a23c26e"]',
            BUTTON_REMOVE_FILE: '[data-tid="f33a6793"]',
            SELECT_ALL_LABEL: '[data-tid="8d50b1b1"]',
            CANCEL_BUTTON_2: '[data-tid="6437e902"]',
            DELETE_CONFIRM: '[data-tid="6a8fa758"]',
            CHECKBOX1: '[data-tid="e71ee118"]',
            SEARCH_PLACEHOLDER: '[data-tid="3388df63"]',
            DROPZONE_PLACEHOLDER: '[data-tid="5475f7a4"]',
            DELETE_BUTTON_1: '[data-tid="84288d84"]',
            PAGINATION: '[data-tid="764234a9"]',
            TOTAL_LABEL: '[data-tid="d71f1df2"]',
            REASON_PLACEHOLDER: '[data-tid="74d32744"]',
        },

        CLM: {
            BUTTON_APPROVAL: '[data-tid="12b68a3f"]',
            BUTTON_APPROVAL_1: '[data-tid="3b83c390"]',
            BUTTON_AGREEMENT: '[data-tid="b917fe7c"]',
            BUTTON_RECIPIENT: '[data-tid="31c4af24"]',
            BUTTON_RECIPIENT_1: '[data-tid="54d491f3"]',
            BUTTON_RECIPIENT_2: '[data-tid="199de4f2"]',
            NO: '[data-tid="833497cb"]',
            MORE: '[data-tid="e21e1b79"]',
            LABEL: '[data-tid="d6ab7faf"]',
            BUTTON9: '[data-tid="6ec93370"]',
            LABEL_1: '[data-tid="d36b35d9"]',
            BUTTON11: '[data-tid="fcdec591"]',
            BUTTON12: '[data-tid="0418a92b"]',
            BUTTON13: '[data-tid="2ae04180"]',
            BUTTON14: '[data-tid="f5accd18"]',
            BUTTON15: '[data-tid="b4eb97b6"]',
            BUTTON16: '[data-tid="3aa857ec"]',
            BUTTON17: '[data-tid="f17b9fe8"]',
            COMPLETE_REVIEW_BUTTON: '[data-tid="93eadda6"]',
            BLACKLIST_SPECIAL_APPROVE_BUTTON: '[data-tid="b064103f"]',
            BLACKLIST_SPECIAL_REJECT_BUTTON: '[data-tid="5b3972db"]',
            CANCEL_BUTTON: '[data-tid="bd22e1ba"]',
            BUTTON_CHANGE: '[data-tid="c054ea38"]',
            CONNECT_BUTTON: '[data-tid="9502094d"]',
            ADD_TEAM_BUTTON: '[data-tid="5e004f75"]',
            CHECKLIST_LABEL: '[data-tid="215148b5"]',
            ASSIGN_BUTTON: '[data-tid="88c0041d"]',
            BUTTON_CLICK_CANCEL_FINAL_APPROVAL: '[data-tid="8d1305ac"]',
            BUTTON_CLICK_CANCEL_FINAL_APPROVAL1: '[data-tid="224d85ad"]',
            ASSIGNER_CHANGE_BUTTON: '[data-tid="4ca79faf"]',
            COMPLETE_REVIEW_BUTTON_1: '[data-tid="d5745346"]',
            START_BUTTON: '[data-tid="bc445522"]',
            FOR_BULK_GENERATE_BUTTON: '[data-tid="6d8d3171"]',
            DELETE_BUTTON: '[data-tid="83aa002c"]',
            DOWNLOAD: '[data-tid="3b2fa005"]',
            PREVIEW: '[data-tid="dd373805"]',
            ESIGN_BADGE: '[data-tid="bc97150d"]',
            PREVIEW_BUTTON: '[data-tid="43acb37e"]',
            BUTTON_CLICK_REMOVE: '[data-tid="e7dd6889"]',
            FOR_BULK_SIGN_BUTTON: '[data-tid="a9929fa9"]',
            VIEW_CONTRACT_BODY: '[data-tid="fdf169e7"]',
            CONFIRM_SAVE_DISUSE: '[data-tid="30c93575"]',
            DONE_DISUSE: '[data-tid="19a03311"]',
            SAVED_MESSAGE: '[data-tid="6d30ce1f"]',
            CANCEL_BUTTON_1: '[data-tid="9a7c08eb"]',
            NEW_REVIEW_REQUEST_BUTTON: '[data-tid="180e8fb0"]',
            BUTTON_EMPTY_LIST_N_KEYWORD: '[data-tid="9f8b4180"]',
            BUTTON_FINAL_APPROVAL_REQUEST: '[data-tid="08095903"]',
            LABEL_2: '[data-tid="42312cb9"]',
            PAGE_TITLE: '[data-tid="3116ad1c"]',
            DOWNLOAD_EXCEL: '[data-tid="e8d2d899"]',
            LABEL_3: '[data-tid="3b04df1f"]',
            BUTTON_LEGAL_AGAIN1: '[data-tid="a3643231"]',
            SEARCH_BUTTON: '[data-tid="1fd6644e"]',
            BUTTON_OPEN_JOB_NUMBER_MODAL: '[data-tid="20g1s9fs"]',
            CLEAN_DOWNLOAD_BUTTON: '[data-tid="b6e28533"]',
            DOWNLOAD_BUTTON: '[data-tid="ebb7a933"]',
            SEARCH_BUTTON_1: '[data-tid="0d523ebb"]',
            WATERMARK_BUTTON: '[data-tid="6a0d9ae2"]',
            LEGAL_APPROVAL_BUTTON: '[data-tid="0e8cee85"]',
            REVIEW_COMPLETE_BUTTON: '[data-tid="ec6f4aa4"]',
            RESEND_TO_DEPARTMENT_BUTTON: '[data-tid="c293a292"]',
            REMOVE_TEAM_ARIA_LABEL: '[data-tid="47271431"]',
            ASSIGNER_CHANGE_BUTTON_1: '[data-tid="5c5a7158"]',
            BUTTON_REVIEW_REQUEST_CANCEL: '[data-tid="7ef2e07d"]',
            SAVE_BUTTON: '[data-tid="69c770b9"]',
            LIST_BUTTON: '[data-tid="53643b41"]',
            PREVIEW_1: '[data-tid="57d1f7b2"]',
            SELECT_ERP_ESIGN_LABEL: '[data-tid="e43345c8"]',
            LIST_LINK: '[data-tid="7e7cb559"]',
            DATE_PLACEHOLDER: '[data-tid="a4baeb71"]',
            DATE_PLACEHOLDER_1: '[data-tid="d1275d4d"]',
            DATEPICKER2: '[data-tid="10f59f4e"]',
            SEARCH_PLACEHOLDER: '[data-tid="1eaa717d"]',
            AMOUNT_PLACEHOLDER: '[data-tid="4a4b4ae6"]',
            PAYMENT_SCHEDULE_UNDECIDED: '[data-tid="99e7dcd2"]',
            SEARCH_PLACEHOLDER_1: '[data-tid="21997440"]',
            CHANGE_CONTRACT: '[data-tid="1abaffa4"]',
            TITLE: '[data-tid="5b2d6d29"]',
            TITLE_1: '[data-tid="fd00b597"]',
            DOCUMENT_NAME_PLACEHOLDER: '[data-tid="c885af6e"]',
            INPUT_TITLE_SEARCH: '[data-tid="50d8659a"]',
            PAGINATION: '[data-tid="320cebc4"]',
            USE_LABEL: '[data-tid="21e37a72"]',
            USE_LABEL_1: '[data-tid="6394c905"]',
            GOV_DOC_OPTION: '[data-tid="8bb724ed"]',
            APPROVAL_LINE_CATEGORY_LABEL: '[data-tid="4f2bf1e1"]',
            FINAL_APPROVAL_LINE_OPTION: '[data-tid="6b61a508"]',
            RADIO5: '[data-tid="ccd55b3b"]',
            AUTO_RENEWAL: '[data-tid="d61fc8e1"]',
            AUTO_RENEWAL_1: '[data-tid="b4684956"]',
            ATTACHMENT_METHOD_LABEL: '[data-tid="ca2fa99f"]',
            LOAD_FROM_MY_CONTRACT: '[data-tid="c3105745"]',
            RADIO10: '[data-tid="60768ab3"]',
            RADIO11: '[data-tid="268a7239"]',
            MAJOR_CATEGORY_PLACEHOLDER: '[data-tid="c4cfcb4d"]',
            SUB_CATEGORY_PLACEHOLDER: '[data-tid="f9843ed3"]',
            MINOR_CATEGORY_PLACEHOLDER: '[data-tid="37c455ed"]',
            PRIOR_NOTICE_PREFIX: '[data-tid="5f9956c7"]',
            RENEWAL_CYCLE_PREFIX: '[data-tid="eba673a5"]',
            PERIOD_PLACEHOLDER: '[data-tid="aae48250"]',
            SELECT6: '[data-tid="64537eaa"]',
            KEYWORD_LABEL: '[data-tid="1311359b"]',
            KEYWORD_PLACEHOLDER: '[data-tid="5d385bbe"]',
            REASON_LABEL: '[data-tid="9dc95143"]',
            DESCRIPTION: '[data-tid="de769f3f"]',
            // footer-safe-area 확인 버튼
            FOOTER_CONFIRM_BUTTON: '//div[contains(@class,"footer-safe-area")]//button[text()="확인"]',
            // 계약 구분 라디오
            DRAFT_TYPE_NEW_LABEL: '//label[.//div[text()="신규"]]',
            DRAFT_TYPE_CHANGE_LABEL: '//label[.//div[text()="변경"]]',
            DRAFT_TYPE_STOP_LABEL: '//label[.//div[text()="해지"]]',
            // 편집기 사용 여부
            EDITOR_USE_LABEL: '//label[.//div[text()="사용"]]',
            EDITOR_NOT_USE_LABEL: '//label[.//div[text()="사용 안 함"]]',
            // 계약서 첨부 방식
            ATTACH_BY_FILE_LABEL: '//label[.//div[text()="파일로 첨부하기"]]',
            ATTACH_FROM_MY_LABEL: '//label[.//div[text()="My계약서에서 불러오기"]]',
            FILE_UPLOAD_ICON: 'img[alt="파일 업로드"]',
            LOAD_ICON: 'img[alt="불러오기 아이콘"]',
            // 보안 여부
            SECURITY_ALL_LABEL: '//label[.//div[text()="전체 공개"]]',
            SECURITY_REFER_LABEL: '//label[.//div[text()="참조인"]]',
            SECURITY_PRIVATE_LABEL: '//label[.//div[text()="비공개"]]',
            // 검토 진행 여부
            REVIEW_NEEDED_LABEL: '//label[.//div[text()="검토 필요"]]',
            REVIEW_NOT_NEEDED_LABEL: '//label[.//div[text()="검토 불필요"]]',
            // 결재 / 요청
            ADD_APPROVER_ICON: 'img[alt="결재자 추가하기"]',
            CONTRACT_REVIEW_REQUEST_BTN: '//div[text()="계약서 검토 요청"]',
            // 계약명 입력
            CONTRACT_NAME_INPUT: 'input[placeholder="계약명을 입력해 주세요"]',
            // 관련 계약
            RELATED_CONTRACT_SEARCH_BTN: '//div[text()="관련 계약 찾아보기"]',
            // 목록 행 / 선택 버튼
            FIRST_ROW: '(//tr[contains(@class,"cursor-pointer")])[1]',
            FIRST_SELECT_BUTTON: '(//button[text()="선택"])[1]',
        },

        COMMON: {
            BUTTON_CLICK: '[data-tid="d18be363"]',
            NO_APPROVER_GUIDE: '[data-tid="8900d31b"]',
            INPUT_CONTRACT_FILE_UPLOAD: '[data-tid="7626cc8b"]',
            CATEGORY_PLACEHOLDER: '[data-tid="b51ca43c"]',
        },

        DASHBOARD: {
            ASSIGN_BUTTON: '[data-tid="9b8c8513"]',
            MORE: '[data-tid="1d9dafff"]',
            CANCEL_BUTTON: '[data-tid="8dbacbb5"]',
            CHECKBOX: '[data-tid="1aac1e31"]',
            DATEPICKER: '[data-tid="27f8537e"]',
            SETTING: 'img[alt="setting"]',
            CLOSE: 'img[alt="close"]',
            GNB: 'img[alt="네비게이션 열기/접기 버튼"]',
        },

        DEV: {
            BUTTON: '[data-tid="4857860d"]',
            BUTTON1: '[data-tid="c2454bea"]',
            BUTTON2: '[data-tid="e6394109"]',
            BUTTON3: '[data-tid="34ed7fe2"]',
            BUTTON4: '[data-tid="a96da0e8"]',
            BUTTON5: '[data-tid="90c111f0"]',
            BUTTON6: '[data-tid="969792bb"]',
            BUTTON7: '[data-tid="94c0bfa6"]',
            BUTTON8: '[data-tid="ded1f14d"]',
            BUTTON9: '[data-tid="ea0a8ffd"]',
        },

        DOCUMENT_COMPARE: {
            SELECT_BUTTON: '[data-tid="aa00c091"]',
            SELECT_BUTTON_1: '[data-tid="10f4dea0"]',
            COMPARE_BUTTON: '[data-tid="c1136259"]',
            CHANGE_CONTRACT_BUTTON: '[data-tid="43e15405"]',
            BOTH_CONTRACTS_REQUIRED: '[data-tid="535c2f4b"]',
            LOAD_BUTTON: '[data-tid="c20c2f69"]',
            PAGINATION: '[data-tid="f885e19f"]',
            PAGINATION1: '[data-tid="68e06fef"]',
            RADIO_FILE_UPLOAD: '[data-tid="989ea3d1"]',
            RADIO_MY_CONTRACT: '[data-tid="a0eeb820"]',
            RADIO_REVIEW_REQUEST: '[data-tid="4a6b1058"]',
        },

        DRIVE: {
            LOADING: '[data-tid="dde025c0"]',
            BUTTON1: '[data-tid="bf76b1a2"]',
        },

        INQUIRY: {
            REMOVE_FILE_ARIA_LABEL: '[data-tid="9e9e4912"]',
            REMOVE_FILE_ARIA_LABEL_1: '[data-tid="7e1cbc7b"]',
            ATTACH_FILE: '[data-tid="ef3238ca"]',
            TITLE: '[data-tid="7a458eb8"]',
            ATTACH_FILE_1: '[data-tid="508fe967"]',
            AGREE_TEXT: '[data-tid="48fa6922"]',
            AGREE_TEXT_1: '[data-tid="6b249a40"]',
            NAME_PLACEHOLDER: '[data-tid="cf3bd226"]',
            INPUT1: '[data-tid="cd0f41f4"]',
            EMAIL_LABEL: '[data-tid="0b2cd802"]',
            INPUT3: '[data-tid="c87c94b2"]',
            NAME_PLACEHOLDER_1: '[data-tid="8313c570"]',
            INPUT5: '[data-tid="365d8f78"]',
            EMAIL_LABEL_1: '[data-tid="fd4479f1"]',
            INPUT7: '[data-tid="2f35593f"]',
            EMAIL_DIRECT_INPUT: '[data-tid="202994a8"]',
            EMAIL_DIRECT_INPUT_1: '[data-tid="2cad5ec8"]',
            PLACEHOLDER: '[data-tid="1b1e841e"]',
            CONTENT_LABEL: '[data-tid="f98f5338"]',
        },

        INTERNAL_NOTICE: {
            PAGE_TITLE: '[data-tid="28721735"]',
            CANCEL_BUTTON: '[data-tid="73c74524"]',
            SAVE_BUTTON: '[data-tid="ec285b79"]',
            EDIT_BUTTON: '[data-tid="aeac9cb3"]',
            PAGE_TITLE_1: '[data-tid="3f619b4c"]',
            DELETE_BUTTON: '[data-tid="09ac9893"]',
            PREVIEW_BUTTON: '[data-tid="a17d915d"]',
            CANCEL_BUTTON_1: '[data-tid="e374aee3"]',
            INPUT: '[data-tid="4d97e397"]',
            PAGINATION: '[data-tid="2a287d3a"]',
        },

        LAW: {
            DATE_FORMAT: '[data-tid="79e31b8c"]',
            DATE_FORMAT_1: '[data-tid="9d501510"]',
            MY_INTERESTED_LAWS_LABEL: '[data-tid="9475d26b"]',
            BUTTON_CLICK_TAB: '[data-tid="ef02b6be"]',
            PAGE_TITLE: '[data-tid="16a511be"]',
            PROMULGATED_ACTS_LABEL: '[data-tid="7d283aef"]',
            PROMULGATED_ACTS_LABEL_1: '[data-tid="6a3598c6"]',
            DATEPICKER: '[data-tid="481ab3d0"]',
            RADIO: '[data-tid="d0eede83"]',
            RADIO1: '[data-tid="3364d20c"]',
        },

        LEGAL_DRAFT: {
            BUTTON: '[data-tid="3a86ba84"]',
            ATTACH: '[data-tid="204c5ad7"]',
            OPEN_EXTERNAL: '[data-tid="489f130f"]',
            ATTACH_1: '[data-tid="ecc49360"]',
        },

        LEGAL_INQUIRY: {
            BUTTON: '[data-tid="050badb9"]',
            ATTACH: '[data-tid="f4f9466b"]',
            ATTACH_1: '[data-tid="ccf53de7"]',
        },

        LITIGATION: {
            NEW_DRAFT_BUTTON: '//button[text()="신규 송무 등록" and not(@disabled)]',
            VIEW_CASE_DETAIL_BUTTON: '[data-tid="48efe758"]',
            MONTH_BUTTON: '[data-tid="c4937c0e"]',
            WEEK_BUTTON: '[data-tid="b7b20565"]',
            ATTACHMENTS_TITLE: '[data-tid="8a84f82f"]',
            MODIFY_BUTTON: '[data-tid="988f9123"]',
            BUTTON_CLICK: '[data-tid="25702d70"]',
            EXCEL_DOWNLOAD_BUTTON: '[data-tid="976ae131"]',
            EXCEL_DOWNLOAD_BUTTON_1: '[data-tid="78b0832f"]',
            EXCEL_DOWNLOAD_BUTTON_2: '[data-tid="49c42273"]',
            DELETE_BUTTON: '[data-tid="1c17a19d"]',
            RETRIEVE_BUTTON: '[data-tid="0742719b"]',
            BUTTON_CLICK_OPEN_COMMENT_ROW: '[data-tid="40f832de"]',
            DELETE_BUTTON_1: '[data-tid="76de46b6"]',
            CLOSE_BUTTON: '[data-tid="821d068b"]',
            LIST_BUTTON: '[data-tid="1fb9dd2f"]',
            CASE_SCHEDULE_TITLE: '[data-tid="b55275ac"]',
            CLOSE_BUTTON_1: '[data-tid="b5b734ea"]',
            ADD_COMMENT_BUTTON: '[data-tid="5a80d220"]',
            CLOSE_BUTTON_2: '[data-tid="9fe7c241"]',
            BUTTON_DELETE: '[data-tid="ec173001"]',
            TEMP_SAVE_BUTTON: '[data-tid="0d939bdf"]',
            ATTACHMENTS_INPUT_LABEL: '[data-tid="f3c093cd"]',
            LIST_BUTTON_1: '[data-tid="cab1cd66"]',
            LIST_BUTTON_2: '[data-tid="44039c35"]',
            DETAIL_INFO_LABEL: '[data-tid="630c5a0e"]',
            MY_REQUESTS_CHECKBOX: '[data-tid="beeb0c1e"]',
            DATE_PICKER_FORMAT: '[data-tid="02e6733c"]',
            CASE_TITLE_LABEL: '[data-tid="c191eca4"]',
            OUTSIDE_COUNSEL_TITLE: '[data-tid="62e2c29a"]',
            ADD_BUTTON: '[data-tid="fd398349"]',
            OUTCOME_LABEL: '[data-tid="17c9e9bb"]',
            CC_RECIPIENTS_INPUT_LABEL: '[data-tid="d73d9698"]',
            DEFENDANT_AMOUNT_INPUT_LABEL: '[data-tid="fd3318c8"]',
            EVIDENCE_INPUT_LABEL: '[data-tid="56049338"]',
            UPLOAD_FILE_BUTTON: '[data-tid="ccc13182"]',
            PAGINATION: '[data-tid="997bacef"]',
            DAY_BUTTON: '[data-tid="3ddb4432"]',
            MY_SCHEDULE_RADIO: '[data-tid="586c2977"]',
            MY_SCHEDULE_RADIO_1: '[data-tid="0e97fc18"]',
            OUTSIDE_COUNSEL_INPUT_LABEL: '[data-tid="3599c8fb"]',
            TYPE_LABEL: '[data-tid="dd837bbc"]',
            DESCRIPTION_LABEL: '[data-tid="1472f29e"]',
            CASE_TYPE_SELECT_PLACEHOLDER: '[data-tid="61ecd5b9"]',
            DEFENDANT_LABEL: '[data-tid="fcebcd28"]',
            COURT_SELECT_PLACEHOLDER: '[data-tid="d9b85967"]',
        },

        LOG: {
            VIEW_DETAIL: '[data-tid="3d74b8fb"]',
            START_DATE_PLACEHOLDER: '[data-tid="1e23b54c"]',
            END_DATE_PLACEHOLDER: '[data-tid="095f3f9d"]',
            SEARCH_PLACEHOLDER: '[data-tid="af14b302"]',
            PAGINATION: '[data-tid="1872891c"]',
            SELECT: '[data-tid="3f2f71eb"]',
            SELECT1: '[data-tid="6348fc73"]',
        },

        MOBILE: {
            REMEMBER_EMAIL_LABEL: '[data-tid="006b405b"]',
            LOGIN_BUTTON: '[data-tid="b678409e"]',
            REMEMBER_EMAIL_LABEL_1: '[data-tid="46a3cc4e"]',
        },

        MODAL: {
            CANCEL: '[data-tid="ebefaeb4"]',
            CANCEL_1: '[data-tid="9576907f"]',
            REMOVE_CHIP_ARIA_LABEL: '[data-tid="8a6fb87b"]',
            CANCEL_BUTTON: '[data-tid="0fe6e0d1"]',
            BUTTON_CHANGE: '[data-tid="aa6a3642"]',
            BUTTON_CLICK: '[data-tid="7b646af4"]',
            CANCEL_2: '[data-tid="a642219f"]',
            CANCEL_3: '[data-tid="5ff7474c"]',
            CANCEL_BUTTON_1: '[data-tid="7bd1894b"]',
            CLOSE_ARIA_LABEL: '[data-tid="c806cbc3"]',
            CONFIRM_BUTTON: '[data-tid="f9cde575"]',
            CLOSE: '[data-tid="e55dbc1d"]',
            IMAGE_PLACEHOLDER: '[data-tid="4dea8767"]',
            CANCEL_BUTTON_2: '[data-tid="9bc892b2"]',
            CANCEL_BUTTON_3: '[data-tid="b3e744ae"]',
            CANCEL_BTN: '[data-tid="38fe4e50"]',
            CLOSE_ARIA_LABEL_1: '[data-tid="fedd10bf"]',
            CANCEL_4: '[data-tid="3c511207"]',
            CLOSE_ARIA_LABEL_2: '[data-tid="6c54c85c"]',
            EXPAND_ALL_BUTTON: '[data-tid="93c88fe7"]',
            COMPARE_BUTTON: '[data-tid="a693a448"]',
            CANCEL_5: '[data-tid="1a0817b4"]',
            CANCEL_BUTTON_4: '[data-tid="b7f1f830"]',
            CLOSE_BUTTON: '[data-tid="42e32331"]',
            ALL_DEPARTMENTS_LABEL: '[data-tid="ba9c5ec6"]',
            SEARCH_PLACEHOLDER: '[data-tid="5d27b826"]',
            BUTTON_MOVE_DOWN: '[data-tid="dadf2339"]',
            BUTTON_MOVE_UP: '[data-tid="dab3e773"]',
            NOTIFICATION_SETTINGS_BTN: '[data-tid="d3b99da1"]',
            REMOVE_ARIA_LABEL: '[data-tid="28f01699"]',
            UPLOAD_FAILED_RETRY_MESSAGE: '[data-tid="c8187956"]',
            CANCEL_BUTTON_5: '[data-tid="2161219a"]',
            JOB_NAME: '[data-tid="11ef1969"]',
            CANCEL_BUTTON_6: '[data-tid="08cad8a6"]',
            BUTTON_TOGGLE: '[data-tid="65cf46c6"]',
            SEARCH_EMPTY_LABEL: '[data-tid="2e92709f"]',
            BUTTON_U_TEAM_NAME: '[data-tid="81dca728"]',
            EMPTY_PREVIEW: '[data-tid="7c6108a8"]',
            BUTTON_ZOOM_OUT: '[data-tid="a45716e4"]',
            CHECKBOX: '[data-tid="c36398e7"]',
            CHECKBOX1: '[data-tid="a53589bf"]',
            SEARCH_PLACEHOLDER_1: '[data-tid="f49b8e47"]',
            REPLACE_BUTTON: '[data-tid="739f6b9d"]',
            PURPOSE_LABEL: '[data-tid="ad59cbd7"]',
            DO_NOT_SHOW_AGAIN: '[data-tid="89f3e73c"]',
            LOAD: '[data-tid="04146334"]',
            JOB_NAME_1: '[data-tid="5e940d17"]',
            JOB_NO: '[data-tid="84bf7669"]',
            INPUT_SEARCH: '[data-tid="ce7fd17b"]',
            SEARCH_PLACEHOLDER_2: '[data-tid="9421e40c"]',
            SEARCH_PLACEHOLDER_3: '[data-tid="8f941071"]',
            ERROR_MESSAGE: '[data-tid="fc999215"]',
            PAGINATION_JOB_NUMBER: '[data-tid="10e881ed"]',
            NOTIFICATION_LABEL: '[data-tid="312cc1b9"]',
            YES_OPTION: '[data-tid="d9dd6fc2"]',
            YES_OPTION_1: '[data-tid="e3600f34"]',
            SEAL_APPROVE_PERMISSION: '[data-tid="eacf476a"]',
            FINANCIAL_REVIEW_PERMISSION: '[data-tid="c4e1accf"]',
            COMPLIANCE_PERMISSION: '[data-tid="8d9bb5f5"]',
            LOG_MANAGE_PERMISSION: '[data-tid="746833e0"]',
            MDM_ADER_CD: '[data-tid="c829a9e2"]',
            SELECT1: '[data-tid="a9ef7fd5"]',
            CONTENT_PLACEHOLDER: '[data-tid="a96ecc36"]',
        },

        NOTICE: {
            BUTTON: '[data-tid="708db741"]',
            PAGE_TITLE: '[data-tid="3278162c"]',
            PAGINATION: '[data-tid="cdd414bb"]',
        },

        PC: {
            NEW_REGISTER_BUTTON: '[data-tid="da3d4e02"]',
            DELETE_HEADER: '[data-tid="b55d4a05"]',
            SAVE_BUTTON: '[data-tid="b759254f"]',
            CONFIRM_BUTTON: '[data-tid="331a2a2c"]',
            DELETE_BUTTON: '[data-tid="8f816574"]',
            EDIT_ORG_NAME_MENU: '[data-tid="432e973c"]',
            MOVE_MENU: '[data-tid="a1ce3776"]',
            CLOSE_BUTTON: '[data-tid="f74fb7f1"]',
            MOVE_BUTTON: '[data-tid="dde2c2f8"]',
            BUTTON_CLICK_NAME: '[data-tid="960e0155"]',
            REGISTER_BUTTON: '[data-tid="44f0d65c"]',
            DELETE_BUTTON_1: '[data-tid="31ceabea"]',
            VERIFICATION_COMPLETE_BUTTON: '[data-tid="0adf6163"]',
            LOGGED_IN_FROM_OTHER_DEVICE: '[data-tid="74925ebf"]',
            CANCEL_BUTTON: '[data-tid="85a854e9"]',
            MODAL_TITLE: '[data-tid="53cb2583"]',
            CLOSE_BUTTON_1: '[data-tid="ea8f7627"]',
            EXPAND_ORG_BUTTON: '[data-tid="8928990d"]',
            CREATE_SUB_ORG_MENU: '[data-tid="82f5b915"]',
            CANCEL_BUTTON_1: '[data-tid="23ac9294"]',
            ORG_MANAGEMENT_TITLE: '[data-tid="733687b1"]',
            BUTTON_IS_USER_NODE: '[data-tid="da19cc18"]',
            REMEMBER_EMAIL_LABEL: '[data-tid="c660e9d8"]',
            TWO_FACTOR_ENABLED: '[data-tid="74a51a3e"]',
            VIEW_ALL_BUTTON: '[data-tid="9246af00"]',
            LOGIN_LIST_LABEL: '[data-tid="97e98a44"]',
            CURRENT_DEVICE: '[data-tid="e2af7030"]',
            CREATE_SUB_ORG_MENU_1: '[data-tid="9acc6036"]',
            CANCEL_BUTTON_2: '[data-tid="171e9983"]',
            SAVE_BUTTON_1: '[data-tid="41460141"]',
            VIEW_ALL_BUTTON_1: '[data-tid="4b166d4a"]',
            BUTTON_SHOW_INVITE_MODAL: '[data-tid="2a6550d9"]',
            SUBTITLE: '[data-tid="f3a8c2e1"]',
            LIST_BUTTON: '[data-tid="7b7d3f69"]',
            DEFAULT_CC_SETTING_LABEL: '[data-tid="5a86b11e"]',
            CC_CONTRACT_REVIEW: '[data-tid="c9002387"]',
            CC_EXECUTED_CONTRACT: '[data-tid="eb9bd0a3"]',
            POSITION_TITLE_LABEL: '[data-tid="499a6556"]',
            TITLE_PLACEHOLDER: '[data-tid="6eefdd0b"]',
            INPUT2: '[data-tid="b8f6fcc5"]',
            PASSWORD_LABEL: '[data-tid="32748916"]',
            NEW_PASSWORD_TITLE: '[data-tid="d7cea234"]',
            CONFIRM_PASSWORD_TITLE: '[data-tid="648dae71"]',
            SIGNUP_PATH_LABEL: '[data-tid="c68e17e9"]',
            FILE_PASSWORD_PLACEHOLDER: '[data-tid="396e4220"]',
            REMEMBER_EMAIL_LABEL_1: '[data-tid="e1b48975"]',
            UPLOAD_CORPORATE_SEAL_BUTTON: '[data-tid="674e21d2"]',
            INPUT_FILE_UPLOAD: '[data-tid="85042a05"]',
            NEW_REGISTER_BUTTON_1: '[data-tid="f6beb6f9"]',
            DELETE_BUTTON_2: '[data-tid="7125e91a"]',
            PAGINATION: '[data-tid="0c995bd9"]',
            LEGAL_ASSIGN_PERM_LABEL: '[data-tid="42257f01"]',
            LEGAL_REVIEW_PERM_LABEL: '[data-tid="3213160e"]',
            SEAL_APPROVE_PERM_LABEL: '[data-tid="97275bcd"]',
            FINANCE_REVIEW_PERM_LABEL: '[data-tid="de3aff47"]',
            COMPLIANCE_PERM_LABEL: '[data-tid="61266d14"]',
            LOG_MANAGE_PERM_LABEL: '[data-tid="0cc45879"]',
            CC_SETTING_PERM_LABEL: '[data-tid="4fadeba5"]',
            SELECT_PLACEHOLDER: '[data-tid="991a33b9"]',
            PER_ITEM_OPTION: '[data-tid="e924747a"]',
            PER_ITEM_OPTION_1: '[data-tid="602abc54"]',
            ALL_RECEIVE_OPTION: '[data-tid="36ef0d00"]',
            REFUSE_OPTION: '[data-tid="bc039245"]',
            REFUSE_OPTION_1: '[data-tid="d83bebfc"]',
            PER_ITEM_OPTION_2: '[data-tid="bfcb772f"]',
            PER_ITEM_OPTION_3: '[data-tid="5cf8ff0a"]',
            ALL_RECEIVE_OPTION_1: '[data-tid="fe10f584"]',
            REFUSE_OPTION_2: '[data-tid="2ac0d857"]',
            REFUSE_OPTION_3: '[data-tid="d1dbe040"]',
            PER_ITEM_OPTION_4: '[data-tid="bb23e505"]',
            PER_ITEM_OPTION_5: '[data-tid="49f87a27"]',
            ALL_RECEIVE_OPTION_2: '[data-tid="a318216c"]',
            REFUSE_OPTION_4: '[data-tid="44aed4f7"]',
        },

        PROJECT: {
            COMMENT_PLACEHOLDER: '[data-tid="b14d4a2f"]',
            REGISTER_BUTTON: '[data-tid="9d2da031"]',
            COL_MANAGEMENT_NO: '[data-tid="fd0cc329"]',
            CHECKBOX1: '[data-tid="159a2b0c"]',
            SEARCH_PLACEHOLDER: '[data-tid="bfe313c9"]',
            SEARCH_PLACEHOLDER_1: '[data-tid="2b14a141"]',
            PAGINATION: '[data-tid="b6e047af"]',
            CATEGORY_LABEL: '[data-tid="77889e93"]',
            SUB_CATEGORY_PLACEHOLDER: '[data-tid="f75b4ca5"]',
            MINOR_CATEGORY_PLACEHOLDER: '[data-tid="4fbd74fb"]',
        },

        RESET_PASSWORD: {
            CONFIRM_BUTTON: '[data-tid="c0cf24b5"]',
            LOGIN_BUTTON: '[data-tid="9fc19ad3"]',
            NEXT_BUTTON: '[data-tid="2b173daf"]',
            BUTTON_CLICK_SEND_CODE: '[data-tid="4c17900e"]',
            RESET_BUTTON: '[data-tid="44b8fadc"]',
            EMAIL_PLACEHOLDER: '[data-tid="45c42ba5"]',
            PHONE_PLACEHOLDER: '[data-tid="69c9b355"]',
            CODE_PLACEHOLDER: '[data-tid="af25718d"]',
        },

        SEAL: {
            RECIPIENT_BUTTON: '[data-tid="eb37816c"]',
            RECIPIENT_BUTTON_1: '[data-tid="a403a5ca"]',
            REAPPLY_DESCRIPTION: '[data-tid="b2552e1c"]',
            REJECT_BUTTON: '[data-tid="76b05bcf"]',
            CHANGE_APPROVER_BUTTON: '[data-tid="ad5d4d16"]',
            PAGE_TITLE: '[data-tid="5c3f29e6"]',
            CANCEL_BUTTON: '[data-tid="3ff409fc"]',
            REJECT_BUTTON_1: '[data-tid="0cbe812f"]',
            CANCEL_BUTTON_1: '[data-tid="e6a0c5e4"]',
            DATEPICKER: '[data-tid="fed835ac"]',
            ADD_LABEL: '[data-tid="1ef27346"]',
            CONTRACT_NAME: '[data-tid="0f3ca62d"]',
            COPIES_AND_SEAL_COUNT: '[data-tid="382eeb7a"]',
            CONTRACT_ATTACH_METHOD: '[data-tid="4e0c0187"]',
            LOAD_REVIEW_REQUEST_OPTION: '[data-tid="66d69fdd"]',
            RELEASE_STATUS: '[data-tid="ab004070"]',
            NOT_RELEASED: '[data-tid="bcb0c66d"]',
            SEAL_CERTIFICATE: '[data-tid="b7cb38e6"]',
            NOT_USED: '[data-tid="6a4c32e9"]',
            CURRENT_APPROVER_LABEL: '[data-tid="f0df791f"]',
            PURPOSE: '[data-tid="d05826b2"]',
        },

        SETUP: {
            PAGE_TITLE: '[data-tid="5ee46f9e"]',
            MODIFY_BUTTON: '[data-tid="a770d644"]',
            ADD_BUTTON: '[data-tid="ef209783"]',
            CANCEL_BUTTON: '[data-tid="de8679f2"]',
            SAVE_BUTTON: '[data-tid="e5228f3f"]',
            BUTTON_DELETE: '[data-tid="3100c574"]',
            LIST_BUTTON: '[data-tid="541d4197"]',
            CHECKBOX: '[data-tid="840152a2"]',
            CHECKBOX1: '[data-tid="0ad05af3"]',
            MIDDLE_CATEGORY_PLACEHOLDER: '[data-tid="f1e367e8"]',
            APPROVAL_LINE_CATEGORY_LABEL: '[data-tid="1b9c5e0f"]',
            FINAL_APPROVAL_LINE_OPTION: '[data-tid="65cb1d44"]',
            REQUESTER_OPTION: '[data-tid="9b1fb3ab"]',
            ADVICE_MANAGER_OPTION: '[data-tid="3ffbe9b0"]',
            DOCUMENT_SECURITY_STATUS_TOOLTIP: '[data-tid="6691df7e"]',
            PUBLIC: '[data-tid="7b5d9ba5"]',
            PUBLIC_1: '[data-tid="7a97af2b"]',
            PUBLIC_2: '[data-tid="5f65797e"]',
            PUBLIC_3: '[data-tid="9f188b65"]',
            PUBLIC_4: '[data-tid="5277ecbb"]',
            PUBLIC_5: '[data-tid="bbbd1b0a"]',
            ENABLED_OPTION: '[data-tid="3558a02a"]',
            NONE_OPTION: '[data-tid="c940580b"]',
            DOCUMENT_SECURITY_STATUS_LABEL: '[data-tid="9b050dab"]',
            DAY_PLACEHOLDER: '[data-tid="9bd103cb"]',
            HOUR_OPTION: '[data-tid="b89367c7"]',
            SESSION_COUNT_OPTION: '[data-tid="4a154f2f"]',
            SESSION_COUNT_OPTION_1: '[data-tid="7ea4032d"]',
            CUSTOM_OPTION: '[data-tid="de2a486b"]',
            DAY_OPTION: '[data-tid="4f2f5e6c"]',
        },

        SIGNUP: {
            GET_CERTIFIED_BUTTON: '[data-tid="2651e793"]',
            SIGN_UP_BUTTON: '[data-tid="d2cdaa43"]',
            CONFIRM_BUTTON: '[data-tid="e2799fc4"]',
            PHONE_PLACEHOLDER: '[data-tid="5733e024"]',
            CERT_CODE_PLACEHOLDER: '[data-tid="781502c1"]',
        },

        STATISTICS: {
            EXECUTIVE_ONLY: '[data-tid="d9a6ec3d"]',
            PAGINATION: '[data-tid="a683533d"]',
            MONTHLY: '[data-tid="d7a502f9"]',
            MONTHLY_1: '[data-tid="a4bc3899"]',
            MONTHLY_2: '[data-tid="96b05ff7"]',
            RADIO3: '[data-tid="a9389871"]',
            NO_YEAR_DATA: '[data-tid="4c93b593"]',
            NO_YEAR_DATA_1: '[data-tid="b329521c"]',
            MONTH_PLACEHOLDER: '[data-tid="69905b3b"]',
            MONTH_PLACEHOLDER_1: '[data-tid="393f5368"]',
            MONTH_PLACEHOLDER_2: '[data-tid="3215bf40"]',
            SELECT5: '[data-tid="6c296a4c"]',
            SELECT6: '[data-tid="78204ef9"]',
        },

        TEAM_STANDARD_CONTRACT: {
            NEW_REGISTER_BUTTON: '[data-tid="32c8b8a9"]',
            BUTTON1: '[data-tid="971ceff4"]',
            BACK_TO_LIST_BUTTON: '[data-tid="9bdfa1e2"]',
            BACK_TO_LIST_BUTTON_1: '[data-tid="7a931b93"]',
            UNSUPPORTED_FILE_FORMAT_ALERT: '[data-tid="f21d5170"]',
            CHECKLIST_INPUT_PLACEHOLDER: '[data-tid="52cafeeb"]',
            DOCUMENT_NAME_PLACEHOLDER: '[data-tid="a7454078"]',
            RADIO: '[data-tid="29be50d2"]',
            DEPARTMENT_PLACEHOLDER: '[data-tid="a89030cf"]',
            DEPARTMENT_PLACEHOLDER_1: '[data-tid="0c5928e4"]',
        },

        TEAMS: {
            PAGE_TITLE: '[data-tid="af1a3d69"]',
            FLEX_INTEGRATION_BUTTON: '[data-tid="e62aaf43"]',
            SYNC_SECTION_TITLE: '[data-tid="eeac8055"]',
            TOKEN_INPUT_PLACEHOLDER: '[data-tid="f1353144"]',
        },

        TEMPLATE: {
            BUTTON: '[data-tid="410e8df9"]',
            DEFAULT_VALUE_BUTTON: '[data-tid="bb823751"]',
            UNSET_BUTTON: '[data-tid="0a8e5588"]',
            EDIT_BUTTON: '[data-tid="f653fd0f"]',
            EDIT_BUTTON_1: '[data-tid="b856ce7b"]',
            BUTTON_TOGGLE_MENU: '[data-tid="87c2fa49"]',
        },

        UI: {
            BUTTON: '[data-tid="a6c5826f"]',
            BUTTON1: '[data-tid="bf0c6dc0"]',
            BUTTON_DECREASE_MONTH: '[data-tid="5030ab02"]',
            BUTTON_INCREASE_MONTH: '[data-tid="e1261689"]',
            BUTTON_TOGGLE_VISIBLE: '[data-tid="f6b7885e"]',
            INPUT: '[data-tid="82a09d72"]',
            INPUT1: '[data-tid="0aef4344"]',
            SEARCH_PLACEHOLDER: '[data-tid="939b9bc8"]',
            SELECT: '[data-tid="08ade09c"]',
            SELECT1: '[data-tid="6e2a09ef"]',
            TEXTAREA: '[data-tid="e56ccf47"]',
        },
    },

    // =========================================================
    // WEB
    // =========================================================
    WEB: {

        ERROR: {
            BUTTON: '[data-tid="37dffc30"]',
        },

        ESIGN: {
            BUTTON: '[data-tid="51f89476"]',
            EXIT_BUTTON: '[data-tid="7ed5f9d4"]',
            EXIT_BUTTON_1: '[data-tid="4f2dd8ab"]',
            EXIT_BUTTON_2: '[data-tid="d288e13d"]',
            NEXT_BUTTON: '[data-tid="5d5e6074"]',
            BUTTON_NEXT_CLICK_CALLBACK: '[data-tid="93b8e91a"]',
            PREVIOUS_BUTTON: '[data-tid="747c5b4c"]',
            DOCUMENT_NAME_LABEL: '[data-tid="c7197697"]',
            SIGNATURE_REQUESTER_LABEL: '[data-tid="cff2d231"]',
            SIGNATURE_REQUESTER_LABEL_1: '[data-tid="211d984d"]',
            BASIC_INFO_LABEL: '[data-tid="5f548335"]',
            EMAIL_PLACEHOLDER: '[data-tid="7fe4c7db"]',
            PHONE_PLACEHOLDER: '[data-tid="32855fff"]',
            INPUT6: '[data-tid="98da9038"]',
            SIGNATURE_DEADLINE_LABEL: '[data-tid="827ccdd3"]',
            INPUT_FILE: '[data-tid="71f186c6"]',
            COMMENT_PLACEHOLDER: '[data-tid="fe4cdf16"]',
        },

        MAGAZINE_FLOATING_BUTTONS: {
            BUTTON: '[data-tid="187e0750"]',
            BUTTON1: '[data-tid="ae8a125b"]',
            BUTTON2: '[data-tid="dd593ba1"]',
            BUTTON3: '[data-tid="5a576c06"]',
            BUTTON4: '[data-tid="0247fb23"]',
            BUTTON_CLICK_RELATIVE_DOCUMENT: '[data-tid="3ff5e3ee"]',
            BUTTON_CLICK_RELATIVE_DOCUMENT1: '[data-tid="d8fd473e"]',
            BUTTON_CLICK_SHARE: '[data-tid="86f3f95d"]',
        },

        MAGAZINE_RELATIVE_DOCUMENTS: {
            BUTTON_CLICK_CLOSE: '[data-tid="a1e9b524"]',
            BUTTON_CLICK_CLOSE1: '[data-tid="610b43d5"]',
        },

        MAIN: {
            BUTTON: '[data-tid="6c8f8d5f"]',
            BUTTON1: '[data-tid="f4f45ed7"]',
            BUTTON2: '[data-tid="6712a46b"]',
            BUTTON3: '[data-tid="7914cecb"]',
            BUTTON4: '[data-tid="825c5c3d"]',
            BUTTON5: '[data-tid="a80c125d"]',
            BUTTON6: '[data-tid="39a15149"]',
            BUTTON7: '[data-tid="e077f830"]',
            BUTTON8: '[data-tid="2a75bc72"]',
            BUTTON9: '[data-tid="e3c7390c"]',
            BUTTON10: '[data-tid="75b1c5d2"]',
            BUTTON11: '[data-tid="b6051d82"]',
            BUTTON12: '[data-tid="d002b6ad"]',
            BUTTON51: '[data-tid="6d63a711"]',
            BUTTON52: '[data-tid="b4c6aba2"]',
            BUTTON100: '[data-tid="c3410439"]',
            BUTTON1000: '[data-tid="4e6fdee0"]',
            BUTTON_AI: '[data-tid="6cf41137"]',
            BUTTON_CHAT_GLD: '[data-tid="f0f745b5"]',
            BUTTON_CLICK: '[data-tid="986a477e"]',
            BUTTON_CLICK1: '[data-tid="90ad95d2"]',
            BUTTON_CLICK_BENEFIT: '[data-tid="80be71e4"]',
            BUTTON_CLICK_CERTIFICATE: '[data-tid="c6d395aa"]',
            BUTTON_CLICK_CERTIFICATE1: '[data-tid="f82da493"]',
            BUTTON_CLICK_NEXT: '[data-tid="457f0123"]',
            BUTTON_CLICK_PLUS: '[data-tid="e138b020"]',
            BUTTON_CLICK_PREV: '[data-tid="9989b526"]',
            BUTTON_CLICK_RECEIVE: '[data-tid="b6288e2f"]',
            BUTTON_CLICK_RECEIVE1: '[data-tid="2d288e5d"]',
            BUTTON_CLICK_RELOAD: '[data-tid="851a94ed"]',
            BUTTON_CLICK_REMOVE: '[data-tid="90352e92"]',
            BUTTON_CLICK_REMOVE1: '[data-tid="6618f415"]',
            BUTTON_CLICK_SHARE: '[data-tid="8aa2acd6"]',
            BUTTON_CLICK_SHARE1: '[data-tid="5f093084"]',
            BUTTON_CLICK_VIDEO_LIST: '[data-tid="2076d707"]',
            BUTTON_CLICK_VIDEO_LIST1: '[data-tid="b7caed7e"]',
            BUTTON_CLOSE: '[data-tid="24ce3ef8"]',
            BUTTON_GIVE7_DAYS_FREE_VOUCHER: '[data-tid="be04257e"]',
            BUTTON_HASH_TAG: '[data-tid="10b9f660"]',
            BUTTON_MOVE_CEO_CERTIFICATE: '[data-tid="e6ae8467"]',
            BUTTON_MOVE_CEO_CERTIFICATE1: '[data-tid="b20f98a5"]',
            BUTTON_NBSP: '[data-tid="000b480e"]',
            BUTTON_NEXT: '[data-tid="7c4000b9"]',
            BUTTON_PREVIOUS: '[data-tid="a30c30bd"]',
            BUTTON_SIGNUP: '[data-tid="48983a94"]',
            BUTTON_SUBMIT: '[data-tid="6dd64d0d"]',
            BUTTON_SUBMIT1: '[data-tid="a793b65a"]',
            BUTTON_TITLE_SEARCH: '[data-tid="1332cdff"]',
            INPUT: '[data-tid="455165ea"]',
            INPUT1: '[data-tid="b7465a04"]',
            INPUT2: '[data-tid="5841026e"]',
            INPUT3: '[data-tid="49210ccc"]',
            INPUT4: '[data-tid="87dc15dd"]',
            INPUT5: '[data-tid="ca9ecc19"]',
            INPUT6: '[data-tid="b2fab77c"]',
            INPUT7: '[data-tid="c2527beb"]',
            INPUT8: '[data-tid="bd230f37"]',
            INPUT_EMAIL: '[data-tid="c9ec98d1"]',
            INPUT_EMAIL1: '[data-tid="fa6c7e74"]',
            INPUT_SEARCH: '[data-tid="a341e3c2"]',
            INPUT_TITLE: '[data-tid="77358a35"]',
            INPUT_TODAY_CHECKBOX: '[data-tid="b6dbfb3c"]',
            PAGINATION: '[data-tid="a1dfb05a"]',
            SELECT: '[data-tid="7019df59"]',
            SELECT1: '[data-tid="4155955b"]',
            TEXTAREA: '[data-tid="bc234efd"]',
        },

        MODALS: {
            BUTTON_CLOSE: '[data-tid="d59488c2"]',
            BUTTON_INQUIRY_CLICK: '[data-tid="78105e38"]',
        },

        OVERLAY: {
            BUTTON_SUBMIT: '[data-tid="2b770063"]',
            BUTTON_SUBMIT1: '[data-tid="14502422"]',
            INPUT: '[data-tid="b48c32b9"]',
        },

        PAGES: {
            BUTTON: '[data-tid="53178cd5"]',
            BUTTON1: '[data-tid="db0cc297"]',
        },

        PRESS: {
            BUTTON: '[data-tid="cc4bac5b"]',
            BUTTON_IS_FETCHING: '[data-tid="dac843b1"]',
            PAGINATION: '[data-tid="17aa26f9"]',
            SELECT: '[data-tid="e9259708"]',
            SELECT1: '[data-tid="5ac7b6aa"]',
        },

        TABLELISTS: {
            INPUT_FILE_UPLOAD: '[data-tid="5505bdd4"]',
        },
    },

    // =========================================================
    // SHARED_UI
    // =========================================================
    SHARED_UI: {

        BUSINESS: {
            BUTTON: '[data-tid="0d747b6e"]',
            BUTTON1: '[data-tid="74b3663e"]',
            BUTTON_CLICK_OPEN_MENU_MODAL: '[data-tid="bbb411ab"]',
            BUTTON_CLICK_SHARE: '[data-tid="e6b0cd8f"]',
            BUTTON_CLICK_SHARE1: '[data-tid="252a5364"]',
            BUTTON_CLOSE: '[data-tid="466c955a"]',
        },

        COMPONENTS: {
            VIEW_EMAIL_DETAIL: '[data-tid="c946b59b"]',
            BUTTON1: '[data-tid="90df18ec"]',
            BUTTON2: '[data-tid="0932dd57"]',
            BUTTON_CLICK_BACK_STEP: '[data-tid="89492c5a"]',
            BUTTON_CLICK_BTN: '[data-tid="dbf4c6b4"]',
            BUTTON_CLICK_CHECKED: '[data-tid="a3d3f427"]',
            BUTTON_CLICK_CONFIRM: '[data-tid="d31c7db2"]',
            VIEW_EMAIL_DETAIL_1: '[data-tid="7cb753fe"]',
            BUTTON_CLICK_RADIO_ITEM: '[data-tid="0e72b104"]',
            BUTTON_CLICK_SEARCH: '[data-tid="f7e1579a"]',
            BUTTON_CLICK_SELECT_DATA: '[data-tid="9011593c"]',
            BUTTON_CLICK_SELECT_OPTION: '[data-tid="f4b9f144"]',
            BUTTON_CLICK_SUBMIT: '[data-tid="b0873fde"]',
            BUTTON_CLICK_SUBMIT_BTN: '[data-tid="e5eb7ee6"]',
            BUTTON_CLICK_TOGGLE: '[data-tid="9dd36413"]',
            BUTTON_CLICK_TOGGLE_OPEN: '[data-tid="c038d836"]',
            DELETE_CONFIRM_MESSAGE: '[data-tid="38f433ad"]',
            BUTTON_CLOSE_MODAL: '[data-tid="4b7c4bd9"]',
            CANCEL_BUTTON: '[data-tid="14aba8bc"]',
            BUTTON_DECREASE_MONTH: '[data-tid="15ace69b"]',
            BUTTON_DELETE: '[data-tid="2f8e854c"]',
            BUTTON_ICON: '[data-tid="8368e80c"]',
            BUTTON_INCREASE_MONTH: '[data-tid="1d3ee126"]',
            BUTTON_IS_LOADING_CHILDREN: '[data-tid="19d1e81b"]',
            CANCEL_BUTTON_1: '[data-tid="408a7913"]',
            BUTTON_SELECT_OPTION: '[data-tid="51fbeeed"]',
            CONFIRM_BUTTON: '[data-tid="5169a4a3"]',
            BUTTON_TOGGLE_VISIBLE: '[data-tid="0557ade0"]',
            DATEPICKER: '[data-tid="4ca70030"]',
            DATEPICKER1: '[data-tid="d0e5cd3b"]',
            INPUT: '[data-tid="359ffc54"]',
            INPUT1: '[data-tid="6681b660"]',
            INPUT2: '[data-tid="2dd10181"]',
            INPUT3: '[data-tid="880f872c"]',
            INPUT4: '[data-tid="5d5745af"]',
            INPUT5: '[data-tid="a291f0fd"]',
            TOTAL_LABEL: '[data-tid="93dcced6"]',
            VISIBILITY_LABEL: '[data-tid="dbbb9f69"]',
            TEAM_ONLY_RADIO: '[data-tid="846e28b1"]',
            TOTAL_LABEL_1: '[data-tid="719d7ce2"]',
            SELECT1: '[data-tid="73cd92e0"]',
            SELECT2: '[data-tid="4d445e4e"]',
            SELECT3: '[data-tid="9af1b4a5"]',
            COMMENT_LABEL: '[data-tid="0c6a0f14"]',
        },

        MODALS: {
            CANCEL_BUTTON: '[data-tid="b88e1095"]',
            CANCEL_BUTTON_1: '[data-tid="7fa30a21"]',
            BUTTON2: '[data-tid="780c2ec0"]',
            BUTTON3: '[data-tid="79cd2c55"]',
            BUTTON4: '[data-tid="1a183ee7"]',
            BUTTON5: '[data-tid="45d5061c"]',
            BUTTON14: '[data-tid="de3af7f6"]',
            BUTTON_ALL_AGREE: '[data-tid="6ce8f0b5"]',
            BUTTON_CLICK: '[data-tid="969f2900"]',
            BUTTON_CLICK_ACTION: '[data-tid="d5c8e8a8"]',
            BUTTON_CLICK_ACTION1: '[data-tid="55c68977"]',
            BUTTON_CLICK_CANCEL: '[data-tid="dacb7ad2"]',
            BUTTON_CLICK_CHECK_PHONE_AUTH_CODE: '[data-tid="2f52a8cc"]',
            BUTTON_CLICK_CLEAR_BTN: '[data-tid="4a2fab97"]',
            INFO_LABEL: '[data-tid="856a8a0f"]',
            CONFIRM_BUTTON: '[data-tid="43e742f4"]',
            COMPLETE_BUTTON: '[data-tid="e89a2763"]',
            CANCEL_BUTTON_2: '[data-tid="add3cf53"]',
            CLOSE_BUTTON: '[data-tid="22bfd975"]',
            BUTTON_CLICK_DOWNLOAD: '[data-tid="480b94e2"]',
            DO_NOT_SHOW_AGAIN_BUTTON: '[data-tid="32ddbc80"]',
            BUTTON_CLICK_LOGIN_BUTTON: '[data-tid="60867958"]',
            BUTTON_CLICK_NEXT_STEP: '[data-tid="49834dd1"]',
            BUTTON_CLICK_NOTICE: '[data-tid="2da389e7"]',
            PREV_BUTTON: '[data-tid="a8f0c508"]',
            BUTTON_CLICK_RESULT: '[data-tid="47b731d4"]',
            CANCEL_BUTTON_3: '[data-tid="a5564a92"]',
            BUTTON_CLICK_SET_MANAGE_DOCS: '[data-tid="1cbce1cc"]',
            CANCEL_BUTTON_4: '[data-tid="cd8cce98"]',
            DO_NOT_SHOW_AGAIN_BUTTON_1: '[data-tid="7b297c53"]',
            CANCEL_BUTTON_5: '[data-tid="891b0e9a"]',
            CONTACT_SALES_MESSAGE: '[data-tid="8f66bdbd"]',
            BUTTON_CONFIRM: '[data-tid="10ca662b"]',
            PREVIEW_UNSUPPORTED_MESSAGE: '[data-tid="c4e24d82"]',
            BUTTON_DOWNLOAD_WITH_WATERMARK: '[data-tid="67154546"]',
            MODAL_TITLE: '[data-tid="d6eb6f8e"]',
            CLOSE_BUTTON_1: '[data-tid="998af835"]',
            BUTTON_NBSP: '[data-tid="972cc3bc"]',
            BUTTON_NBSP1: '[data-tid="f62e146c"]',
            BUTTON_PHONE_NUMBER_AUTH: '[data-tid="8bef6af2"]',
            BUTTON_PURCHASE: '[data-tid="ae81d126"]',
            BUTTON_RESET: '[data-tid="7321354a"]',
            DO_NOT_ASK_AGAIN_CHECKBOX: '[data-tid="531b11f7"]',
            TIME_BASED_NOTICE: '[data-tid="9b854161"]',
            BUTTON_USE_PERMISSION: '[data-tid="eea1ae2f"]',
            BUTTON_USE_PERMISSION1: '[data-tid="486fe7e1"]',
            CHECKBOX: '[data-tid="24156783"]',
            DATEPICKER: '[data-tid="155d4ed8"]',
            PAGE_TITLE: '[data-tid="b520abef"]',
            CODE_PLACEHOLDER: '[data-tid="8f8c57ad"]',
            INPUT2: '[data-tid="4d293422"]',
            INPUT3: '[data-tid="63b358cd"]',
            INPUT4: '[data-tid="8bafe4be"]',
            INPUT_EMAIL: '[data-tid="e3bfad95"]',
            INPUT_NAME: '[data-tid="657b3666"]',
            PASSWORD_PLACEHOLDER: '[data-tid="d6f6f2ba"]',
            INPUT_SEARCH: '[data-tid="f46daf09"]',
            SELECT_MANAGER_PLACEHOLDER: '[data-tid="f0b99044"]',
            SEARCH_PLACEHOLDER: '[data-tid="8690e4c0"]',
            PAGINATION: '[data-tid="a2626b49"]',
            USE_STATUS_LABEL: '[data-tid="ce274cf3"]',
            CHANGE_WATERMARK: '[data-tid="5d9639bd"]',
            SELECT: '[data-tid="fdb19ea0"]',
            SELECT1: '[data-tid="1b791bf0"]',
        },

        POLARIS: {
            BUTTON: '[data-tid="b95b3d69"]',
            BUTTON1: '[data-tid="370ca3a9"]',
            BUTTON2: '[data-tid="7e541d81"]',
            BUTTON3: '[data-tid="adea11ea"]',
            CONFIRM_MESSAGE: '[data-tid="530006cf"]',
            BUTTON_CLICK: '[data-tid="e9efc148"]',
            CANCEL_BUTTON: '[data-tid="cb0b2886"]',
            BUTTON_CLICK_FAVORITE: '[data-tid="5423930a"]',
            BUTTON_CLICK_FAVORITE1: '[data-tid="c4ef6b90"]',
            BACK_TO_AUTOFORM_BUTTON: '[data-tid="2d0f4a9f"]',
            BUTTON_CLICK_GUID: '[data-tid="2177ca57"]',
            BUTTON_CLICK_GUIDE: '[data-tid="0fda7a5c"]',
            CURRENT_VERSION_LABEL: '[data-tid="fcae3c1b"]',
            BUTTON_CLICK_LAWYER_REVIEW: '[data-tid="9846d3b8"]',
            BUTTON_CLICK_RETURN_AUTODOC: '[data-tid="ff2ddd82"]',
            BACK_TO_AUTOFORM_BUTTON_1: '[data-tid="092dfd79"]',
            CANCEL_BUTTON_1: '[data-tid="4ccf4640"]',
            BUTTON_CLICK_SIGN: '[data-tid="e063b1a3"]',
            DOWNLOAD_BUTTON: '[data-tid="f75765b7"]',
            BUTTON_CLOSE_DOCX_TEXT: '[data-tid="8c7168c7"]',
            BUTTON_COMPOSE_PDF: '[data-tid="04619260"]',
            CANCEL: '[data-tid="09d75759"]',
            BUTTON_EXPORT_DOCX: '[data-tid="1024fbd1"]',
            BUTTON_EXPORT_HTML: '[data-tid="7cc66f4c"]',
            BUTTON_EXPORT_HWP: '[data-tid="923f9831"]',
            BUTTON_EXPORT_PDF: '[data-tid="cbf5815d"]',
            BUTTON_EXPORT_TEXT: '[data-tid="5a80b098"]',
            BUTTON_OPEN_DOWNLOAD_MODAL: '[data-tid="4fc1edfb"]',
            BUTTON_OPEN_HISTORY_MODAL: '[data-tid="68db712f"]',
            BUTTON_OPEN_HTML_STRING_MODAL: '[data-tid="52782af6"]',
            BUTTON_OPEN_SHARE_MODAL: '[data-tid="0ecaf682"]',
            BUTTON_PRINT: '[data-tid="e3168d6f"]',
            SAVE_BUTTON: '[data-tid="613ff13f"]',
            BUTTON_SUBMIT_STRING_HTML: '[data-tid="7471f3ee"]',
            BUTTON_SUBMIT_STRING_HTML_SEPARATE_TABLE: '[data-tid="3ad9c9b2"]',
            BUTTON_TOGGLE_FOLD: '[data-tid="3b098989"]',
            PROGRESS_DETAIL_BUTTON: '[data-tid="538ade10"]',
            BUTTON_TOGGLE_MEMO: '[data-tid="9341cd3e"]',
            BUTTON_TOGGLE_VIEW_XML: '[data-tid="78a7a943"]',
            INPUT: '[data-tid="090c32d3"]',
            INPUT1: '[data-tid="7dccffc5"]',
            INPUT_FILE: '[data-tid="157dc984"]',
            INPUT_FILE_SEAL: '[data-tid="3c2439c3"]',
            INPUT_FILE_UPLOAD: '[data-tid="02436c92"]',
            USE_STATUS_LABEL: '[data-tid="83e9c94a"]',
            BULK_CHANGE_NOTICE: '[data-tid="5627f699"]',
            EMPTY_MESSAGE: '[data-tid="1875619c"]',
            SELECT1: '[data-tid="82372e1b"]',
            TEXTAREA: '[data-tid="1e1ea743"]',
            TEXTAREA1: '[data-tid="16bb9b3a"]',
        },

        VIEWER: {
            BUTTON_ZOOM_IN: '[data-tid="6bfa0d74"]',
            BUTTON_ZOOM_OUT: '[data-tid="f069b013"]',
            INPUT: '[data-tid="87c66e7e"]',
        },

        WOORI: {
            BUTTON_CLOSE: '[data-tid="509bea1b"]',
            BUTTON_CLOSE1: '[data-tid="09b9e907"]',
        },
    },
};
