// 로그인 등 공통 셀렉터 (k6 browser 스크립트용)
export const SELECTORS = {
    // 관리자(admin) 영역 셀렉터 (tid/admin/*.json 기반)
    ADMIN: {
        ADMIN: {
            BUTTON: '[data-tid="admin-admin-button"]',
        },
        AI_CHAT_LOG: {
            BUTTON_LIST: '[data-tid="admin-ai-chat-log-button-list"]',
            BUTTON_REGISTER: '[data-tid="admin-ai-chat-log-button-register"]',
            CHECKBOX: '[data-tid="admin-ai-chat-log-checkbox"]',
            CHECKBOX_1: '[data-tid="admin-ai-chat-log-checkbox1"]',
            INPUT_SEARCH: '[data-tid="admin-ai-chat-log-input-search"]',
            PAGINATION: '[data-tid="admin-ai-chat-log-pagination"]',
            TABLE_LIST: '[data-tid="admin-ai-chat-log-table-list"]',
        },
        AI_EXTERNAL_DATA: {
            BUTTON_CLOSE: '[data-tid="admin-ai-external-data-button-close"]',
            BUTTON_DELETE: '[data-tid="admin-ai-external-data-button-delete"]',
            BUTTON_EXTRACT_TEXT: '[data-tid="admin-ai-external-data-button-extract-text"]',
            BUTTON_GO_BACK: '[data-tid="admin-ai-external-data-button-go-back"]',
            BUTTON_LIST: '[data-tid="admin-ai-external-data-button-list"]',
            BUTTON_PREVIEW: '[data-tid="admin-ai-external-data-button-preview"]',
            BUTTON_REGISTER: '[data-tid="admin-ai-external-data-button-register"]',
            BUTTON_SUBMIT: '[data-tid="admin-ai-external-data-button-submit"]',
            BUTTON_VIEW: '[data-tid="admin-ai-external-data-button-view"]',
            CHECKBOX: '[data-tid="admin-ai-external-data-checkbox"]',
            CHECKBOX_1: '[data-tid="admin-ai-external-data-checkbox1"]',
            INPUT_CATEGORY: '[data-tid="admin-ai-external-data-input-category"]',
            INPUT_SEARCH: '[data-tid="admin-ai-external-data-input-search"]',
            INPUT_URL: '[data-tid="admin-ai-external-data-input-url"]',
            PAGINATION: '[data-tid="admin-ai-external-data-pagination"]',
            SWITCH: '[data-tid="admin-ai-external-data-switch"]',
            TABLE_LIST: '[data-tid="admin-ai-external-data-table-list"]',
        },
        AI_PRESET_CHAT: {
            BUTTON_AI_DRAFT: '[data-tid="admin-ai-preset-chat-button-ai-draft"]',
            BUTTON_CANCEL: '[data-tid="admin-ai-preset-chat-button-cancel"]',
            BUTTON_CLOSE: '[data-tid="admin-ai-preset-chat-button-close"]',
            BUTTON_REGISTER: '[data-tid="admin-ai-preset-chat-button-register"]',
            BUTTON_SAVE: '[data-tid="admin-ai-preset-chat-button-save"]',
            BUTTON_SUBMIT: '[data-tid="admin-ai-preset-chat-button-submit"]',
            INPUT: '[data-tid="admin-ai-preset-chat-input"]',
            INPUT_SEARCH: '[data-tid="admin-ai-preset-chat-input-search"]',
            PAGINATION: '[data-tid="admin-ai-preset-chat-pagination"]',
            TEXTAREA: '[data-tid="admin-ai-preset-chat-textarea"]',
        },
        AI_PROMPT_DETAIL_FORM: {
            BUTTON_ACTIVATE: '[data-tid="admin-ai-prompt-detail-form-button-activate"]',
            BUTTON_CANCEL: '[data-tid="admin-ai-prompt-detail-form-button-cancel"]',
            BUTTON_SUBMIT: '[data-tid="admin-ai-prompt-detail-form-button-submit"]',
            TEXTAREA_CONTENT: '[data-tid="admin-ai-prompt-detail-form-textarea-content"]',
        },
        AI_PROMPTS_TABLE: {
            BUTTON: '[data-tid="admin-ai-prompts-table-button"]',
            BUTTON_1: '[data-tid="admin-ai-prompts-table-button1"]',
            BUTTON_NEXT: '[data-tid="admin-ai-prompts-table-button-next"]',
            BUTTON_PREVIOUS: '[data-tid="admin-ai-prompts-table-button-previous"]',
            TABLE_LIST: '[data-tid="admin-ai-prompts-table-table-list"]',
        },
        AUTODOC: {
            BUTTON: '[data-tid="admin-autodoc-button"]',
            BUTTON_1: '[data-tid="admin-autodoc-button1"]',
            BUTTON_CATEGORY_MANAGEMENT: '[data-tid="admin-autodoc-button-category-management"]',
            BUTTON_CLOSE: '[data-tid="admin-autodoc-button-close"]',
            BUTTON_REFRESH: '[data-tid="admin-autodoc-button-refresh"]',
            BUTTON_REGISTER: '[data-tid="admin-autodoc-button-register"]',
            BUTTON_REGISTER_CATEGORY: '[data-tid="admin-autodoc-button-register-category"]',
            BUTTON_SAVE: '[data-tid="admin-autodoc-button-save"]',
            BUTTON_TOGGLE_CHAT: '[data-tid="admin-autodoc-button-toggle-chat"]',
            BUTTON_TOGGLE_CHAT_1: '[data-tid="admin-autodoc-button-toggle-chat1"]',
            BUTTON_UPDATE_RECOMMEND: '[data-tid="admin-autodoc-button-update-recommend"]',
            INPUT: '[data-tid="admin-autodoc-input"]',
            INPUT_SEARCH: '[data-tid="admin-autodoc-input-search"]',
            PAGINATION: '[data-tid="admin-autodoc-pagination"]',
            SELECT: '[data-tid="admin-autodoc-select"]',
            TABLE_LIST: '[data-tid="admin-autodoc-table-list"]',
        },
        DASHBOARD: {
            EXCEL: '[data-tid="admin-dashboard-button-excel-download"]',
            DATEPICKER: '[data-tid="admin-dashboard-datepicker"]',
            PAGINATION: '[data-tid="admin-dashboard-pagination"]',
            SELECT: '[data-tid="admin-dashboard-select"]', // 조회 단위 : 년 (분기 선택)
            SELECT_1: '[data-tid="admin-dashboard-select1"]', // 조회 단위 : 분기
            SELECT_2: '[data-tid="admin-dashboard-select2"]', // 조회 단위 년 (반기 선택)
            SELECT_3: '[data-tid="admin-dashboard-select3"]', //조회 단위 : 반기
            SELECT_4: '[data-tid="admin-dashboard-select4"]', //조회 단위 : 기간
            SELECT_CATEGORY: '[data-tid="admin-dashboard-select-category"]', // 구분
            SELECT_DATA_SELECT: '[data-tid="admin-dashboard-select-data-select"]', // 데이터 선택 
            SELECT_QUERY_UNIT: '[data-tid="admin-dashboard-select-query-unit"]', // 조회 단위
            TABLE_LIST: '[data-tid="admin-dashboard-table-list"]',
        },
        DOCUMENT_UPDATE_REPORT: {
            BUTTON: '[data-tid="admin-document-update-report-button"]',
            BUTTON_1: '[data-tid="admin-document-update-report-button1"]',
            BUTTON_CLOSE: '[data-tid="admin-document-update-report-button-close"]',
            BUTTON_CONFIRM: '[data-tid="admin-document-update-report-button-confirm"]',
            BUTTON_HISTORY_CLICK: '[data-tid="admin-document-update-report-button-history-click"]',
            BUTTON_VIEW_ORIGINAL: '[data-tid="admin-document-update-report-button-view-original"]',
            CHECKBOX: '[data-tid="admin-document-update-report-checkbox"]',
            CHECKBOX_1: '[data-tid="admin-document-update-report-checkbox1"]',
            DATEPICKER: '[data-tid="admin-document-update-report-datepicker"]',
            PAGINATION: '[data-tid="admin-document-update-report-pagination"]',
        },
        FILTERING: {
            BUTTON_CLOSE: '[data-tid="admin-filtering-button-close"]',
            BUTTON_REGISTER_CLICK: '[data-tid="admin-filtering-button-register-click"]',
            BUTTON_SUBMIT: '[data-tid="admin-filtering-button-submit"]',
            INPUT: '[data-tid="admin-filtering-input"]',
            INPUT_1: '[data-tid="admin-filtering-input1"]',
            INPUT_SEARCH: '[data-tid="admin-filtering-input-search"]',
            PAGINATION: '[data-tid="admin-filtering-pagination"]',
            SWITCH: '[data-tid="admin-filtering-switch"]',
            TABLE_LIST: '[data-tid="admin-filtering-table-list"]',
        },
        IP_MANAGEMENT: {
            INPUT_SEARCH: '[data-tid="admin-ip-management-input-search"]',
            TABLE_LIST: '[data-tid="admin-ip-management-table-list"]',
        },
        MEMBERS: {
            BUTTON: '[data-tid="admin-members-button"]',
            BUTTON_1: '[data-tid="admin-members-button1"]',
            BUTTON_GO_TO_LIST: '[data-tid="admin-members-button-go-to-list"]',
            BUTTON_SAVE: '[data-tid="admin-members-button-save"]',
            BUTTON_SELECT_TRANSFEREE: '[data-tid="admin-members-button-select-transferee"]',
            BUTTON_SELECT_TRANSFEROR: '[data-tid="admin-members-button-select-transferor"]',
        },
        MEMBERS_TABLE: {
            BUTTON_HANDOVER_CLICK: '[data-tid="admin-members-table-button-handover-click"]',
            INPUT_SEARCH: '[data-tid="admin-members-table-input-search"]',
            PAGINATION: '[data-tid="admin-members-table-pagination"]',
            SELECT_APPROVAL_STATUS: '[data-tid="admin-members-table-select-approval-status"]',
            SELECT_ROLE: '[data-tid="admin-members-table-select-role"]',
            TABLE_LIST: '[data-tid="admin-members-table-table-list"]',
        },
        NAVBAR: {
            BUTTON_LOGOUT: '[data-tid="admin-navbar-button-logout"]',
            BUTTON_TOGGLE_LOCALE: '[data-tid="admin-navbar-button-toggle-locale"]',
        },
        NOTICE: {
            REGISTER: '[data-tid="admin-notice-button-notice-filters-register-btn"]',
            INPUT_SEARCH: '[data-tid="admin-notice-input-search"]',
            SEARCH: 'button[id="search-btn"]', //검색 버튼
        },
        PENDING_APPROVAL: {
            BUTTON_CHECK_APPROVAL: '[data-tid="admin-pending-approval-button-check-approval"]',
        },
        QNA: {
            BUTTON_LIST: '[data-tid="admin-qna-button-list"]',
            BUTTON_SAVE: '[data-tid="admin-qna-button-save"]',
            EDITOR: '[data-tid="admin-qna-editor"]',
            EDITOR_1: '[data-tid="admin-qna-editor1"]',
            INPUT_SEARCH: '[data-tid="admin-qna-input-search"]',
            SELECT_ANSWER_STATUS: '[data-tid="admin-qna-select-answer-status"]',
        },
        TERMS: {
            BUTTON_LIST: '[data-tid="admin-terms-button-list"]',
            BUTTON_REGISTER: '[data-tid="admin-terms-button-register"]',
            BUTTON_SEARCH: '[data-tid="admin-terms-button-search"]',
            BUTTON_SUBMIT: '[data-tid="admin-terms-button-submit"]',
            DATEPICKER: '[data-tid="admin-terms-datepicker"]',
            DATEPICKER_REVISION_DATE: '[data-tid="admin-terms-datepicker-revision-date"]',
            DATEPICKER_START: '[data-tid="admin-terms-datepicker-start"]',
            EDITOR_CONTENT: '[data-tid="admin-terms-editor-content"]',
            PAGINATION: '[data-tid="admin-terms-pagination"]',
            RADIO_IS_VISIBLE: '[data-tid="admin-terms-radio-is-visible"]',
            RADIO_VISIBILITY_N: '[data-tid="admin-terms-radio-visibility-n"]',
            TABLE_LIST: '[data-tid="admin-terms-table-list"]',
        },
        USER_ACTIVITY_TABLE: {
            BUTTON: '[data-tid="admin-user-activity-table-button"]',
            INPUT_SEARCH: '[data-tid="admin-user-activity-table-input-search"]',
            PAGINATION: '[data-tid="admin-user-activity-table-pagination"]',
            SELECT_EVENT: '[data-tid="admin-user-activity-table-select-event"]',
            SELECT_STATUS: '[data-tid="admin-user-activity-table-select-status"]',
            TABLE_LIST: '[data-tid="admin-user-activity-table-table-list"]',
        },
        USER_DETAIL_PANEL: {
            BUTTON_AUTO_APPROVE: '[data-tid="admin-user-detail-panel-button-auto-approve"]',
            BUTTON_CLOSE: '[data-tid="admin-user-detail-panel-button-close"]',
            BUTTON_SAVE: '[data-tid="admin-user-detail-panel-button-save"]',
            CHECKBOX: '[data-tid="admin-user-detail-panel-checkbox"]',
            RADIO: '[data-tid="admin-user-detail-panel-radio"]',
            RADIO_1: '[data-tid="admin-user-detail-panel-radio1"]',
            RADIO_2: '[data-tid="admin-user-detail-panel-radio2"]',
        },
        USER_SELECT_MODAL: {
            BUTTON_CLOSE: '[data-tid="admin-user-select-modal-button-close"]',
            BUTTON_CONFIRM: '[data-tid="admin-user-select-modal-button-confirm"]',
            BUTTON_SEARCH: '[data-tid="admin-user-select-modal-button-search"]',
            INPUT: '[data-tid="admin-user-select-modal-input"]',
            PAGINATION: '[data-tid="admin-user-select-modal-pagination"]',
            TABLE_LIST: '[data-tid="admin-user-select-modal-table-list"]',
        },
    },

    // 기능(features) 영역 셀렉터 (tid/features/*.json 기반)
    FEATURES: {
        AI: {
            BUTTON_APPLY: '[data-tid="ai-button-apply"]',
            BUTTON_CLOSE: '[data-tid="ai-button-close"]',
            BUTTON_DESELECT_ALL: '[data-tid="ai-button-deselect-all"]',
            BUTTON_SELECT_ALL: '[data-tid="ai-button-select-all"]',
            CHECKBOX: '[data-tid="ai-checkbox"]',
        },
        AUTODOC: {
            BUTTON: '[data-tid="autodoc-button"]',
            BUTTON_1: '[data-tid="autodoc-button1"]',
            BUTTON_AI_AUTO_LABELING: '[data-tid="autodoc-button-ai-auto-labeling"]',
            BUTTON_AUTO_REVIEW: '[data-tid="autodoc-button-auto-review"]',
            BUTTON_CHECKLIST_SUGGEST: '[data-tid="autodoc-button-checklist-suggest"]',
            BUTTON_CLICK_MINUS: '[data-tid="autodoc-button-click-minus"]',
            BUTTON_CLOSE: '[data-tid="autodoc-button-close"]',
            BUTTON_COMPARE: '[data-tid="autodoc-button-compare"]',
            BUTTON_DOWNLOAD: '[data-tid="autodoc-button-download"]',
            BUTTON_DRAFT_SAVE: '[data-tid="autodoc-button-draft-save"]',
            BUTTON_EDIT: '[data-tid="autodoc-button-edit"]',
            BUTTON_END_SESSION: '[data-tid="autodoc-button-end-session"]',
            BUTTON_LIST: '[data-tid="autodoc-button-list"]',
            BUTTON_LOAD: '[data-tid="autodoc-button-load"]',
            BUTTON_PREVIEW: '[data-tid="autodoc-button-preview"]',
            BUTTON_RESET_SESSION: '[data-tid="autodoc-button-reset-session"]',
            BUTTON_SAVE: '[data-tid="autodoc-button-save"]',
            BUTTON_SEARCH: '[data-tid="autodoc-button-search"]',
            BUTTON_SELECT_ASSOCIATE: '[data-tid="autodoc-button-select-associate"]',
            BUTTON_SEND: '[data-tid="autodoc-button-send"]',
            BUTTON_SUBMIT: '[data-tid="autodoc-button-submit"]',
            BUTTON_TOGGLE_INPUT: '[data-tid="autodoc-button-toggle-input"]',
            BUTTON_TOGGLE_INPUT_1: '[data-tid="autodoc-button-toggle-input1"]',
            CHECKBOX: '[data-tid="autodoc-checkbox"]',
            DATEPICKER: '[data-tid="autodoc-datepicker"]',
            DATEPICKER_END: '[data-tid="autodoc-datepicker-end"]',
            EDITOR: '[data-tid="autodoc-editor"]',
            INPUT: '[data-tid="autodoc-input"]',
            INPUT_1: '[data-tid="autodoc-input1"]',
            PAGINATION: '[data-tid="autodoc-pagination"]',
            RADIO: '[data-tid="autodoc-radio"]',
            SELECT: '[data-tid="autodoc-select"]',
            SWITCH_EDITOR_EDIT_MODE: '[data-tid="autodoc-switch-editor-edit-mode"]',
            SWITCH_EDITOR_TRACKING_MODE: '[data-tid="autodoc-switch-editor-tracking-mode"]',
            SWITCH_WRITING_EDIT_MODE: '[data-tid="autodoc-switch-writing-edit-mode"]',
            SWITCH_WRITING_TRACKING_MODE: '[data-tid="autodoc-switch-writing-tracking-mode"]',
            TABLE_LIST: '[data-tid="autodoc-table-list"]',
            TEXTAREA: '[data-tid="autodoc-textarea"]',
        },
        AUTODOC_TOOL: {
            BUTTON: '[data-tid="autodoc-tool-button"]',
            BUTTON_1: '[data-tid="autodoc-tool-button1"]',
            BUTTON_2: '[data-tid="autodoc-tool-button2"]',
            BUTTON_ADD_SECTION: '[data-tid="autodoc-tool-button-add-section"]',
            BUTTON_ADD_TOP_INPUT_SECTION: '[data-tid="autodoc-tool-button-add-top-input-section"]',
            BUTTON_ADD_TOP_OUTPUT_SECTION: '[data-tid="autodoc-tool-button-add-top-output-section"]',
            BUTTON_CLOSE: '[data-tid="autodoc-tool-button-close"]',
            BUTTON_DOCUMENT_HISTORY: '[data-tid="autodoc-tool-button-document-history"]',
            BUTTON_LABELING: '[data-tid="autodoc-tool-button-labeling"]',
            BUTTON_LIST: '[data-tid="autodoc-tool-button-list"]',
            BUTTON_LOAD: '[data-tid="autodoc-tool-button-load"]',
            BUTTON_PREVIEW: '[data-tid="autodoc-tool-button-preview"]',
            BUTTON_REMOVE_SECTION: '[data-tid="autodoc-tool-button-remove-section"]',
            BUTTON_SAVE: '[data-tid="autodoc-tool-button-save"]',
            BUTTON_TEMP_SAVE: '[data-tid="autodoc-tool-button-temp-save"]',
            CHECKBOX: '[data-tid="autodoc-tool-checkbox"]',
            CHECKBOX_1: '[data-tid="autodoc-tool-checkbox1"]',
            INPUT: '[data-tid="autodoc-tool-input"]',
            INPUT_1: '[data-tid="autodoc-tool-input1"]',
            INPUT_2: '[data-tid="autodoc-tool-input2"]',
            INPUT_3: '[data-tid="autodoc-tool-input3"]',
            INPUT_4: '[data-tid="autodoc-tool-input4"]',
            INPUT_5: '[data-tid="autodoc-tool-input5"]',
            INPUT_6: '[data-tid="autodoc-tool-input6"]',
            INPUT_7: '[data-tid="autodoc-tool-input7"]',
            INPUT_8: '[data-tid="autodoc-tool-input8"]',
            INPUT_9: '[data-tid="autodoc-tool-input9"]',
            INPUT_10: '[data-tid="autodoc-tool-input10"]',
            INPUT_11: '[data-tid="autodoc-tool-input11"]',
            INPUT_12: '[data-tid="autodoc-tool-input12"]',
            INPUT_13: '[data-tid="autodoc-tool-input13"]',
            INPUT_14: '[data-tid="autodoc-tool-input14"]',
            INPUT_15: '[data-tid="autodoc-tool-input15"]',
            INPUT_16: '[data-tid="autodoc-tool-input16"]',
            INPUT_17: '[data-tid="autodoc-tool-input17"]',
            INPUT_18: '[data-tid="autodoc-tool-input18"]',
            INPUT_19: '[data-tid="autodoc-tool-input19"]',
            INPUT_20: '[data-tid="autodoc-tool-input20"]',
            PAGINATION: '[data-tid="autodoc-tool-pagination"]',
            RADIO_AI_REQUIRED_FALSE: '[data-tid="autodoc-tool-radio-ai-required-false"]',
            RADIO_AI_REQUIRED_TRUE: '[data-tid="autodoc-tool-radio-ai-required-true"]',
            RADIO_FALSE: '[data-tid="autodoc-tool-radio-false"]',
            RADIO_FALSE_1: '[data-tid="autodoc-tool-radio-false1"]',
            RADIO_TRUE: '[data-tid="autodoc-tool-radio-true"]',
            RADIO_TRUE_1: '[data-tid="autodoc-tool-radio-true1"]',
            SELECT: '[data-tid="autodoc-tool-select"]',
            SELECT_1: '[data-tid="autodoc-tool-select1"]',
            SELECT_CALENDAR_LEFT_LENGTH: '[data-tid="autodoc-tool-select-calendar-left-length"]',
            SELECT_CASE_COUNT: '[data-tid="autodoc-tool-select-case-count"]',
            SELECT_CASE_TYPE: '[data-tid="autodoc-tool-select-case-type"]',
            SELECT_CHECKBOX_COUNT: '[data-tid="autodoc-tool-select-checkbox-count"]',
            SELECT_DIRECTION: '[data-tid="autodoc-tool-select-direction"]',
            SELECT_RADIO_COUNT: '[data-tid="autodoc-tool-select-radio-count"]',
            SELECT_RADIO_DIRECTION: '[data-tid="autodoc-tool-select-radio-direction"]',
            SELECT_SELECT_COUNT: '[data-tid="autodoc-tool-select-select-count"]',
            SWITCH_EDIT_MODE_TOGGLE: '[data-tid="autodoc-tool-switch-edit-mode-toggle"]',
            SWITCH_TRACKING_TOGGLE: '[data-tid="autodoc-tool-switch-tracking-toggle"]',
            TABLE_LIST: '[data-tid="autodoc-tool-table-list"]',
        },
        LOGIN: {
            BUTTON_SUBMIT: '[data-tid="login-button-submit"]',
            INPUT_EMAIL: '[data-tid="login-input-email"]',
            INPUT_PASSWORD: '[data-tid="login-input-password"]',
        },
        NOTICE: {
            BUTTON_CLOSE: '[data-tid="notice-button-close"]',
            BUTTON_LIST: '[data-tid="notice-button-list"]',
            BUTTON_SUBMIT: '[data-tid="notice-button-submit"]',
            BUTTON_VIEW_HISTORY: '[data-tid="notice-button-view-history"]',
            EDITOR: '[data-tid="notice-editor"]',
            EDITOR_CONTENT: '[data-tid="notice-editor-content"]',
            INPUT_TITLE: '[data-tid="notice-input-title"]',
            PAGINATION: '[data-tid="notice-pagination"]',
            RADIO_IS_VISIBLE: '[data-tid="notice-radio-is-visible"]',
            RADIO_VISIBILITY_N: '[data-tid="notice-radio-visibility-n"]',
            TABLE_LIST: '[data-tid="notice-table-list"]',
        },
        PRIVACY: {
            EDITOR: '[data-tid="privacy-editor"]',
            SELECT: '[data-tid="privacy-select"]',
        },
        QNA: {
            PAGINATION: '[data-tid="qna-pagination"]',
            TABLE_LIST: '[data-tid="qna-table-list"]',
        },
        SIGNUP: {
            BUTTON_SUBMIT: '[data-tid="signup-button-submit"]',
            INPUT_CONFIRM_PASSWORD: '[data-tid="signup-input-confirm-password"]',
            INPUT_EMAIL: '[data-tid="signup-input-email"]',
            INPUT_NAME: '[data-tid="signup-input-name"]',
            INPUT_PASSWORD: '[data-tid="signup-input-password"]',
        },
        TERMS: {
            BUTTON_DOWNLOAD: '[data-tid="terms-button-download"]',
            EDITOR: '[data-tid="terms-editor"]',
        },
    },

    // 웹(web) 영역 셀렉터 (tid/web/*.json 기반)
    WEB: {
        AUTODOC: {
            BUTTON: '[data-tid="web-autodoc-button"]',
            BUTTON_AI_LABEL: '[data-tid="web-autodoc-button-ai-label"]',
            BUTTON_APPLY_LABELS: '[data-tid="web-autodoc-button-apply-labels"]',
            BUTTON_BACK: '[data-tid="web-autodoc-button-back"]',
            BUTTON_BACK_1: '[data-tid="web-autodoc-button-back1"]',
            BUTTON_CLEAR_ALL: '[data-tid="web-autodoc-button-clear-all"]',
            BUTTON_CLOSE_RESULT: '[data-tid="web-autodoc-button-close-result"]',
            BUTTON_CREATE_WRITING: '[data-tid="web-autodoc-button-create-writing"]',
            BUTTON_OPEN_EDITOR_CHAT: '[data-tid="web-autodoc-button-open-editor-chat"]',
            BUTTON_REFRESH: '[data-tid="web-autodoc-button-refresh"]',
            BUTTON_SAVE: '[data-tid="web-autodoc-button-save"]',
            BUTTON_SAVE_LABELS: '[data-tid="web-autodoc-button-save-labels"]',
            BUTTON_TOGGLE_CHAT: '[data-tid="web-autodoc-button-toggle-chat"]',
            BUTTON_TOGGLE_CHAT_1: '[data-tid="web-autodoc-button-toggle-chat1"]',
            BUTTON_TOGGLE_CHAT_WIDTH: '[data-tid="web-autodoc-button-toggle-chat-width"]',
            BUTTON_TOGGLE_INPUT: '[data-tid="web-autodoc-button-toggle-input"]',
            BUTTON_TOGGLE_INPUT_1: '[data-tid="web-autodoc-button-toggle-input1"]',
            EDITOR: '[data-tid="web-autodoc-editor"]',
            INPUT_SEARCH: '[data-tid="web-autodoc-input-search"]',
            PAGINATION: '[data-tid="web-autodoc-pagination"]',
            SWITCH_EDITORCHAT_EDIT_MODE: '[data-tid="web-autodoc-switch-editorchat-edit-mode"]',
            TABLE_LIST: '[data-tid="web-autodoc-table-list"]',
        },
        DRIVE: {
            BUTTON_SEARCH: '[data-tid="web-drive-button-search"]',
            DATEPICKER: '[data-tid="web-drive-datepicker"]',
            DATEPICKER_START: '[data-tid="web-drive-datepicker-start"]',
            INPUT: '[data-tid="web-drive-input"]',
            PAGINATION: '[data-tid="web-drive-pagination"]',
            SELECT_CATEGORY: '[data-tid="web-drive-select-category"]',
            TABLE_LIST: '[data-tid="web-drive-table-list"]',
        },
        NAVBAR: {
            BUTTON_LOGOUT: '[data-tid="web-navbar-button-logout"]',
            BUTTON_NEWS_CLICK: '[data-tid="web-navbar-button-news-click"]',
            BUTTON_TOGGLE_LOCALE: '[data-tid="web-navbar-button-toggle-locale"]',
            INPUT: '[data-tid="web-navbar-input"]',
        },
        NOTICE: {
            INPUT_SEARCH: '[data-tid="web-notice-input-search"]',
        },
        QNA: {
            BUTTON_CANCEL: '[data-tid="web-qna-button-cancel"]',
            BUTTON_CLICK_CANCEL: '[data-tid="web-qna-button-click-cancel"]',
            BUTTON_CLICK_GO_TO_LIST: '[data-tid="web-qna-button-click-go-to-list"]',
            BUTTON_CLICK_SUBMIT: '[data-tid="web-qna-button-click-submit"]',
            BUTTON_CREATE_QNA: '[data-tid="web-qna-button-create-qna"]',
            EDITOR: '[data-tid="web-qna-editor"]',
            EDITOR_1: '[data-tid="web-qna-editor1"]',
            INPUT: '[data-tid="web-qna-input"]',
            INPUT_SEARCH: '[data-tid="web-qna-input-search"]',
            SELECT_STATUS: '[data-tid="web-qna-select-status"]',
        },
        SEARCH: {
            BUTTON_DOWNLOAD: '[data-tid="web-search-button-download"]',
            BUTTON_FILTER_SEARCH: '[data-tid="web-search-button-filter-search"]',
            INPUT: '[data-tid="web-search-input"]',
            INPUT_1: '[data-tid="web-search-input1"]',
            PAGINATION: '[data-tid="web-search-pagination"]',
            SELECT: '[data-tid="web-search-select"]',
        },
    }
};