// 로그인 등 공통 셀렉터 (k6 browser 스크립트용)
export const SELECTORS = {
    // 공통 셀렉터 (여러 화면에서 재사용)
    COMMON: {
        LOGOUT: '[data-tid="cd71514a"], [data-tid="2d4ec066"]', // admin/web navbar 로그아웃
        TABLE: 'tbody tr:first-child', // 테이블 첫 번째 행
        TABLE2: 'tbody tr:nth-child(2)', // 테이블 두 번째 행
        PAGE_FIRST: 'button[aria-label="첫 페이지로 이동"]',
        PAGE_LAST: 'button[aria-label="마지막 페이지로 이동"]',
        SEARCH: 'button[id="search-btn"]', // 검색 버튼
        PRIVACY: '//a[text()="개인정보 처리방침"]', // 개인정보처리방침
        TERMS: '//a[text()="이용약관"]', // 이용약관
    },

    // 관리자(admin) 영역 셀렉터 (tid/admin/*.json 기반)
    ADMIN: {
        ADMIN: {
            BUTTON: '[data-tid="366ca271"]',
        },
        AI_CHAT_LOG: {
            BUTTON_DELETE: '[data-tid="3f7b1c92"]',
            BUTTON_LIST: '[data-tid="149a4e27"]',
            BUTTON_REGISTER: '[data-tid="6ca05f83"]',
            CHECKBOX: '[data-tid="c4b27674"]',
            CHECKBOX_1: '[data-tid="fe83c919"]',
            INPUT_SEARCH: '[data-tid="acbb58cd"]',
            PAGINATION: '[data-tid="a7503fc1"]',
            TABLE_LIST: '[data-tid="012e8237"]',
        },
        AI_EXTERNAL_DATA: {
            BUTTON_CLOSE: '[data-tid="44bf55a3"]',
            BUTTON_DELETE: '[data-tid="1194c087"]',
            BUTTON_EXTRACT_TEXT: '[data-tid="f0a34ccd"]',
            BUTTON_GO_BACK: '[data-tid="e6c77fb4"]',
            BUTTON_LIST: '[data-tid="52408535"]',
            BUTTON_PREVIEW: '[data-tid="f3dd3c7f"]',
            BUTTON_REGISTER: '[data-tid="4cd2d7e9"]',
            BUTTON_SUBMIT: '[data-tid="fe0d3ee0"]',
            BUTTON_VIEW: '[data-tid="989d544f"]',
            CHECKBOX: '[data-tid="bd2bfd34"]',
            CHECKBOX_1: '[data-tid="4962a2c9"]',
            INPUT_CATEGORY: '[data-tid="894f039b"]',
            INPUT_SEARCH: '[data-tid="6489b212"]',
            INPUT_URL: '[data-tid="14041541"]',
            PAGINATION: '[data-tid="a5c86077"]',
            SWITCH: '[data-tid="9c54c685"]',
            TABLE_LIST: '[data-tid="c3881784"]',
        },
        AI_PRESET_CHAT: {
            BUTTON_AI_DRAFT: '[data-tid="23aacfca"]',
            BUTTON_CANCEL: '[data-tid="41afe01c"]',
            BUTTON_CLOSE: '[data-tid="fefde07b"]',
            BUTTON_REGISTER: '[data-tid="392eafb7"]',
            BUTTON_SAVE: '[data-tid="3e51bc6d"]',
            BUTTON_SUBMIT: '[data-tid="e232a4f3"]',
            INPUT: '[data-tid="90d6473d"]',
            INPUT_SEARCH: '[data-tid="8b8a8ce6"]',
            PAGINATION: '[data-tid="4a171fd2"]',
            TEXTAREA: '[data-tid="54130b95"]',
        },
        AI_PROMPT_DETAIL_FORM: {
            BUTTON_ACTIVATE: '[data-tid="44bb769b"]',
            BUTTON_CANCEL: '[data-tid="d0520ab5"]',
            BUTTON_SUBMIT: '[data-tid="0bff0056"]',
            TEXTAREA_CONTENT: '[data-tid="d771406e"]',
        },
        AI_PROMPTS_TABLE: {
            BUTTON: '[data-tid="62a23652"]',
            BUTTON_1: '[data-tid="8a10fb4a"]',
            BUTTON_NEXT: '[data-tid="b7411f5f"]',
            BUTTON_PREVIOUS: '[data-tid="86af6267"]',
            TABLE_LIST: '[data-tid="f7d36c48"]',
        },
        AUTODOC: {
            BUTTON: '[data-tid="dbbfbd14"]',
            BUTTON_1: '[data-tid="3b7b41f3"]',
            BUTTON_CATEGORY_MANAGEMENT: '[data-tid="13e1aa9b"]',
            BUTTON_CLOSE: '[data-tid="27921ca1"]',
            BUTTON_REFRESH: '[data-tid="60a8949e"]',
            BUTTON_REGISTER: '[data-tid="22618dd9"]',
            BUTTON_REGISTER_CATEGORY: '[data-tid="2e45a1b0"]',
            BUTTON_SAVE: '[data-tid="4f28c73b"]',
            BUTTON_TOGGLE_CHAT: '[data-tid="3dc4ea89"]',
            BUTTON_TOGGLE_CHAT_1: '[data-tid="f109bc5c"]',
            BUTTON_UPDATE_RECOMMEND: '[data-tid="d74f2b21"]',
            INPUT: '[data-tid="36f4af45"]',
            INPUT_SEARCH: '[data-tid="45dca3a2"]',
            PAGINATION: '[data-tid="cfd66500"]',
            SELECT: '[data-tid="256d8a4e"]',
            SELECT_SELECTED_CATEGORY: '[data-tid="0578db5c"]',
            TABLE_LIST: '[data-tid="eca215d6"]',
        },
        DASHBOARD: {
            BUTTON_SEARCH: '[data-tid="f277b3cc"]', //통계 검색 버튼
            EXCEL: '[data-tid="af3387a9"]', // 엑셀 다운로드 버튼
            DATEPICKER: '[data-tid="98f34024"]', // 조회 일자 datepicker
            PAGINATION: '[data-tid="314da712"]',
            SELECT: '[data-tid="4492d4fd"]', // 조회 단위 combobox
            SELECT_1: '[data-tid="eb0a0d09"]',
            SELECT_2: '[data-tid="e05af5d2"]',
            SELECT_3: '[data-tid="c75ecffa"]',
            SELECT_4: '[data-tid="887f0043"]',
            SELECT_5: '[data-tid="f83968fb"]',
            SELECT_6: '[data-tid="373b4038"]',
            SELECT_7: '[data-tid="01fe55a8"]',
            SELECT_CATEGORY: '[data-tid="1ee325dd"]', // 구분 combobox
            SELECT_DATA_SELECT: '[data-tid="33e4f23d"]', // 데이터 선택 combobox
            SELECT_QUERY_UNIT: '[data-tid="c7498be0"]', // 조회 일자 : 년 combobox
            SELECT_QUERY_UNIT_1: '[data-tid="01f2efab"]', // 조회 일자 : 분기, 반기 combobox
            TABLE_LIST: '[data-tid="5a7867e6"]', // 통계 결과 테이블
        },
        DOCUMENT_UPDATE_REPORT: {
            BUTTON: '[data-tid="4e792fcd"]',
            BUTTON_1: '[data-tid="fc1cef3b"]',
            BUTTON_CLOSE: '[data-tid="b4149e3f"]',
            BUTTON_CONFIRM: '[data-tid="03ee3fef"]',
            BUTTON_HISTORY_CLICK: '[data-tid="84b2562e"]',
            BUTTON_VIEW_ORIGINAL: '[data-tid="05c075a0"]',
            CHECKBOX: '[data-tid="5abe87ac"]',
            CHECKBOX_1: '[data-tid="e74d49a8"]',
            DATEPICKER: '[data-tid="f351da96"]',
            PAGINATION: '[data-tid="6b8f4aad"]',
            // DATEPICKER: '[data-tid="0381c19b"]', 
            // RADIO: '[data-tid="dd026057"]',
        },
        FILTERING: {
            BUTTON_CLOSE: '[data-tid="e7bdee8d"]',
            BUTTON_REGISTER_CLICK: '[data-tid="2a54997f"]',
            BUTTON_SUBMIT: '[data-tid="19827f46"]',
            INPUT: '[data-tid="3dd7e6ee"]',
            INPUT_1: '[data-tid="d087a4ab"]',
            INPUT_SEARCH: '[data-tid="b0025887"]',
            PAGINATION: '[data-tid="f97a8cc8"]',
            SWITCH: '[data-tid="7fa86f02"]',
            TABLE_LIST: '[data-tid="c2232874"]',
        },
        IP_MANAGEMENT: {
            INPUT_SEARCH: '[data-tid="0b2e4c74"]',
            TABLE_LIST: '[data-tid="294c4fa0"]',
        },
        LOG: {
            BUTTON_DOWNLOAD: '[data-tid="048c2905"]',
        },
        MEMBERS: {
            BUTTON: '[data-tid="617f9c52"]',
            BUTTON_1: '[data-tid="a89bd461"]',
            BUTTON_GO_TO_LIST: '[data-tid="dd30a91a"]',
            BUTTON_SAVE: '[data-tid="e9cbe3b4"]',
            BUTTON_SELECT_TRANSFEREE: '[data-tid="ab36031b"]',
            BUTTON_SELECT_TRANSFEROR: '[data-tid="4bbb8318"]',
        },
        MEMBERS_TABLE: {
            BUTTON_HANDOVER_CLICK: '[data-tid="bb3ff6dc"]',
            INPUT_SEARCH: '[data-tid="9db08d0b"]',
            PAGINATION: '[data-tid="d7ba95d3"]',
            SELECT_APPROVAL_STATUS: '[data-tid="f696847c"]',
            SELECT_ROLE: '[data-tid="6d21b201"]',
            TABLE_LIST: '[data-tid="f6c688df"]',
        },
        NAVBAR: {
            BUTTON_LOGOUT: '[data-tid="cd71514a"]',
            BUTTON_TOGGLE_LOCALE: '[data-tid="9666e261"]',
            OPTION_EN: '[data-tid="b2a3203c"]',
            OPTION_KO: '[data-tid="7b72b2dc"]',
        },
        NOTICE: {
            REGISTER: '[data-tid="2cb75815"]',
            INPUT_SEARCH: '[data-tid="36307578"]',
        },
        PENDING_APPROVAL: {
            BUTTON_CHECK_APPROVAL: '[data-tid="2e835444"]',
            // BUTTON_CHECK_APPROVAL: '[data-tid="c8bd6a5e"]',
        },
        QNA: {
            BUTTON_LIST: '[data-tid="7086abaf"]',
            BUTTON_SAVE: '[data-tid="b978a42b"]',
            EDITOR: '[data-tid="0a023e18"]',
            EDITOR_1: '[data-tid="0b3fdea9"]',
            INPUT_SEARCH: '[data-tid="81fac2bb"]',
            SELECT_ANSWER_STATUS: '[data-tid="6ff86c86"]',
        },
        TERMS: {
            BUTTON_LIST: '[data-tid="6a669db8"]',
            BUTTON_REGISTER: '[data-tid="3663722c"]',
            BUTTON_SEARCH: '[data-tid="51ecb794"]',
            BUTTON_SUBMIT: '[data-tid="c0dd15c3"]',
            DATEPICKER: '[data-tid="ec3a4672"]',
            DATEPICKER_REVISION_DATE: '[data-tid="07cd528a"]',
            DATEPICKER_START: '[data-tid="8ef13b06"]',
            EDITOR_CONTENT: '[data-tid="fc0b4da1"]',
            PAGINATION: '[data-tid="fde34758"]',
            RADIO_IS_VISIBLE: '[data-tid="67e82df4"]',
            RADIO_VISIBILITY_N: '[data-tid="d4e2ca7c"]',
            TABLE_LIST: '[data-tid="a9077e7d"]',
        },
        USER_ACTIVITY_TABLE: {
            BUTTON: '[data-tid="07169478"]',
            INPUT_SEARCH: '[data-tid="b00e402f"]',
            PAGINATION: '[data-tid="e7863e33"]',
            SELECT_EVENT: '[data-tid="79fa1ec3"]',
            SELECT_STATUS: '[data-tid="cbcd5952"]',
            TABLE_LIST: '[data-tid="86fc58c2"]',
        },
        USER_DETAIL_PANEL: {
            BUTTON_AUTO_APPROVE: '[data-tid="7a06cc9d"]',
            BUTTON_CLOSE: '[data-tid="febd70ee"]',
            BUTTON_SAVE: '[data-tid="7b9d2778"]',
            CHECKBOX: '[data-tid="2e4e2ed1"]',
            RADIO: '[data-tid="3551efc8"]',
            RADIO_1: '[data-tid="cfc3fcf4"]',
            RADIO_2: '[data-tid="8cabcca7"]',
        },
        USER_SELECT_MODAL: {
            BUTTON_CLOSE: '[data-tid="50857ab5"]',
            BUTTON_CONFIRM: '[data-tid="57d7e8f9"]',
            BUTTON_SEARCH: '[data-tid="5f970210"]',
            INPUT: '[data-tid="e5a47665"]',
            PAGINATION: '[data-tid="052ec5d5"]',
            TABLE_LIST: '[data-tid="98b64d4f"]',
            // RADIO: '[data-tid="e564149f"]',
        },
    },

    // 기능(features) 영역 셀렉터 (tid/features/*.json 기반)
    FEATURES: {
        AI: {
            BUTTON_APPLY: '[data-tid="056c68a1"]',
            BUTTON_CLOSE: '[data-tid="14ce4a76"]',
            BUTTON_DESELECT_ALL: '[data-tid="017bfcb9"]',
            BUTTON_SELECT_ALL: '[data-tid="d23529b3"]',
            CHECKBOX: '[data-tid="fd19aa56"]',
        },
        AUTODOC: {
            BUTTON: '[data-tid="9b406691"]',
            BUTTON_1: '[data-tid="0e5b22de"]',
            BUTTON_AI_AUTO_LABELING: '[data-tid="262aaa79"]',
            BUTTON_AUTO_REVIEW: '[data-tid="44d75fde"]',
            BUTTON_CHECKLIST_SUGGEST: '[data-tid="9741e28a"]',
            BUTTON_CLICK_MINUS: '[data-tid="7cfd001c"]',
            BUTTON_CLOSE: '[data-tid="d0b2f414"]',
            BUTTON_COMPARE: '[data-tid="d1958383"]',
            BUTTON_DOWNLOAD: '[data-tid="052b684f"]',
            BUTTON_DOWNLOAD_1: '[data-tid="2540d31f"]',
            BUTTON_DRAFT_SAVE: '[data-tid="6a6ff793"]',
            BUTTON_EDIT: '[data-tid="fce3552b"]',
            BUTTON_END_SESSION: '[data-tid="25174a66"]',
            BUTTON_LIST: '[data-tid="6a5a5f88"]',
            BUTTON_LOAD: '[data-tid="986e1002"]',
            BUTTON_PREVIEW: '[data-tid="44e636e5"]',
            BUTTON_RESET_SESSION: '[data-tid="26f6ca32"]',
            BUTTON_ROLLBACK: '[data-tid="560f8ca9"]',
            BUTTON_SAVE: '[data-tid="fe5d3e00"]',
            BUTTON_SEARCH: '[data-tid="b270a62b"]',
            BUTTON_SELECT_ASSOCIATE: '[data-tid="98d82c8b"]',
            BUTTON_SEND: '[data-tid="f7363da4"]',
            BUTTON_TOGGLE_INPUT: '[data-tid="69336987"]',
            BUTTON_TOGGLE_INPUT_1: '[data-tid="05683d16"]',
            CHECKBOX: '[data-tid="713b2405"]',
            DATEPICKER: '[data-tid="245db5db"]',
            DATEPICKER_END: '[data-tid="fae5ecd4"]',
            EDITOR: '[data-tid="0b65f1ca"]',
            INPUT: '[data-tid="8201c07d"]',
            INPUT_1: '[data-tid="5c887d48"]',
            PAGINATION: '[data-tid="9c2ae47d"]',
            RADIO: '[data-tid="795fe8d5"]',
            SELECT: '[data-tid="ef9b26b2"]',
            SWITCH_EDITOR_EDIT_MODE: '[data-tid="0dddf491"]',
            SWITCH_EDITOR_TRACKING_MODE: '[data-tid="7cfb4b5e"]',
            SWITCH_WRITING_EDIT_MODE: '[data-tid="aaeda6af"]',
            SWITCH_WRITING_TRACKING_MODE: '[data-tid="c3e02243"]',
            TABLE_LIST: '[data-tid="1bfb2cd9"]',
            TEXTAREA: '[data-tid="9e8179c7"]',
        },
        AUTODOC_TOOL: {
            BUTTON: '[data-tid="32d95696"]',
            BUTTON_1: '[data-tid="73db1dc4"]',
            BUTTON_2: '[data-tid="7c037789"]',
            BUTTON_ADD_SECTION: '[data-tid="5d13decd"]',
            BUTTON_ADD_TOP_INPUT_SECTION: '[data-tid="232521c1"]',
            BUTTON_ADD_TOP_OUTPUT_SECTION: '[data-tid="86789775"]',
            BUTTON_CLOSE: '[data-tid="03f645fb"]',
            BUTTON_DOCUMENT_HISTORY: '[data-tid="7d3be345"]',
            BUTTON_LABELING: '[data-tid="7122164d"]',
            BUTTON_LIST: '[data-tid="310255d7"]',
            BUTTON_LOAD: '[data-tid="af286e56"]',
            BUTTON_PREVIEW: '[data-tid="0feae937"]',
            BUTTON_REMOVE_SECTION: '[data-tid="d2c3534b"]',
            BUTTON_SAVE: '[data-tid="41434785"]',
            BUTTON_TEMP_SAVE: '[data-tid="1982f354"]',
            CHECKBOX: '[data-tid="730b57be"]',
            CHECKBOX_1: '[data-tid="d2a3ed49"]',
            INPUT: '[data-tid="68ad1f20"]',
            INPUT_1: '[data-tid="87a1f318"]',
            INPUT_2: '[data-tid="b37a28eb"]',
            INPUT_3: '[data-tid="4a6a7cde"]',
            INPUT_4: '[data-tid="f2770080"]',
            INPUT_5: '[data-tid="9d1639e3"]',
            INPUT_6: '[data-tid="2a1fa3da"]',
            INPUT_7: '[data-tid="2667cd73"]',
            INPUT_8: '[data-tid="2d12436c"]',
            INPUT_9: '[data-tid="07904c48"]',
            INPUT_10: '[data-tid="701e4b79"]',
            INPUT_11: '[data-tid="f9e7cf12"]',
            INPUT_12: '[data-tid="0d68bc7c"]',
            INPUT_13: '[data-tid="365cc39d"]',
            INPUT_14: '[data-tid="d392dad0"]',
            INPUT_15: '[data-tid="a5c5973a"]',
            INPUT_16: '[data-tid="4431a08b"]',
            INPUT_17: '[data-tid="7c52eb79"]',
            INPUT_18: '[data-tid="e70aedf0"]',
            INPUT_19: '[data-tid="9b6da902"]',
            INPUT_20: '[data-tid="cf5d63b9"]',
            PAGINATION: '[data-tid="fc8693a5"]',
            RADIO_AI_REQUIRED_FALSE: '[data-tid="d8d92a60"]',
            RADIO_AI_REQUIRED_TRUE: '[data-tid="d2413c02"]',
            RADIO_FALSE: '[data-tid="dd8363c4"]',
            RADIO_FALSE_1: '[data-tid="c4525354"]',
            RADIO_TRUE: '[data-tid="0aeeff58"]',
            RADIO_TRUE_1: '[data-tid="e8c85485"]',
            SELECT: '[data-tid="99b3ba0e"]',
            SELECT_1: '[data-tid="7e32f4c9"]',
            SELECT_CALENDAR_LEFT_LENGTH: '[data-tid="2952de3e"]',
            SELECT_CASE_COUNT: '[data-tid="819074bb"]',
            SELECT_CASE_TYPE: '[data-tid="72dea5eb"]',
            SELECT_CHECKBOX_COUNT: '[data-tid="7cf5be7f"]',
            SELECT_DIRECTION: '[data-tid="eeff38c5"]',
            SELECT_RADIO_COUNT: '[data-tid="b49bef9b"]',
            SELECT_RADIO_DIRECTION: '[data-tid="970e1e5a"]',
            SELECT_SELECT_COUNT: '[data-tid="ab202d55"]',
            SWITCH_EDIT_MODE_TOGGLE: '[data-tid="0eb10959"]',
            SWITCH_TRACKING_TOGGLE: '[data-tid="af40751c"]',
            TABLE_LIST: '[data-tid="727bbd30"]',
        },
        LOGIN: {
            BUTTON_SUBMIT: '[data-tid="551e89ef"]',
            INPUT_EMAIL: '[data-tid="9377b001"]',
            INPUT_PASSWORD: '[data-tid="871633f4"]',
        },
        NOTICE: {
            BUTTON_CLOSE: '[data-tid="ed6daf3d"]',
            BUTTON_LIST: '[data-tid="e16d1a8a"]',
            BUTTON_SUBMIT: '[data-tid="071981a5"]',
            BUTTON_VIEW_HISTORY: '[data-tid="94272a6a"]',
            EDITOR: '[data-tid="760b729d"]',
            EDITOR_CONTENT: '[data-tid="25531ba0"]',
            INPUT_TITLE: '[data-tid="764744f9"]',
            PAGINATION: '[data-tid="8c0def75"]',
            RADIO_IS_VISIBLE: '[data-tid="3ce3c364"]',
            RADIO_VISIBILITY_N: '[data-tid="0b3d81b9"]',
            TABLE_LIST: '[data-tid="f207522c"]',
        },
        PRIVACY: {
            EDITOR: '[data-tid="33ce0686"]',
            SELECT: '[data-tid="ffe47cf6"]',
        },
        QNA: {
            PAGINATION: '[data-tid="44b5a358"]',
            TABLE_LIST: '[data-tid="29ee02e1"]',
        },
        SIGNUP: {
            BUTTON_SUBMIT: '[data-tid="dd559663"]',
            INPUT_CONFIRM_PASSWORD: '[data-tid="b492ad24"]',
            INPUT_EMAIL: '[data-tid="ae516ace"]',
            INPUT_NAME: '[data-tid="88856139"]',
            INPUT_PASSWORD: '[data-tid="bfd04cea"]',
        },
        TERMS: {
            BUTTON_DOWNLOAD: '[data-tid="09520f53"]',
            EDITOR: '[data-tid="304653a2"]',
        },
    },

    // 웹(web) 영역 셀렉터 (tid/web/*.json 기반)
    WEB: {
        AUTODOC: {
            BUTTON: '[data-tid="18ba2a81"]',
            BUTTON_AI_LABEL: '[data-tid="f2568b8b"]',
            BUTTON_APPLY_LABELS: '[data-tid="9c95e995"]',
            BUTTON_BACK: '[data-tid="2e75173f"]',
            BUTTON_BACK_1: '[data-tid="445077c2"]',
            BUTTON_CLEAR_ALL: '[data-tid="dfedde78"]',
            BUTTON_CLOSE_RESULT: '[data-tid="ed1f305c"]',
            BUTTON_CREATE_WRITING: '[data-tid="4757c363"]',
            BUTTON_OPEN_EDITOR_CHAT: '[data-tid="593c41f9"]',
            BUTTON_REFRESH: '[data-tid="8a5ca284"]',
            BUTTON_SAVE: '[data-tid="187d6d1e"]',
            BUTTON_SAVE_LABELS: '[data-tid="059e7c5e"]',
            BUTTON_TOGGLE_CHAT: '[data-tid="7af0ede6"]',
            BUTTON_TOGGLE_CHAT_1: '[data-tid="3ee80a72"]',
            BUTTON_TOGGLE_CHAT_WIDTH: '[data-tid="ef42e23a"]',
            BUTTON_TOGGLE_INPUT: '[data-tid="6d034191"]',
            BUTTON_TOGGLE_INPUT_1: '[data-tid="cd4a6c4d"]',
            EDITOR: '[data-tid="ad8d3171"]',
            INPUT_SEARCH: '[data-tid="ab71486b"]',
            PAGINATION: '[data-tid="55c81982"]',
            SWITCH_EDITORCHAT_EDIT_MODE: '[data-tid="27bfc648"]',
            TABLE_LIST: '[data-tid="5ac7ce45"]',
        },
        DRIVE: {
            BUTTON_SEARCH: '[data-tid="97dea766"]',
            DATEPICKER: '[data-tid="6e9de10f"]',
            DATEPICKER_START: '[data-tid="569db2b1"]',
            INPUT: '[data-tid="fe2d46a4"]',
            PAGINATION: '[data-tid="13e35b5b"]',
            SELECT_CATEGORY: '[data-tid="ae14d270"]',
            TABLE_LIST: '[data-tid="a9b90254"]',
        },
        NAVBAR: {
            BUTTON_LOGOUT: '[data-tid="2d4ec066"]',
            BUTTON_NEWS_CLICK: '[data-tid="d21c61b1"]',
            BUTTON_TOGGLE_LOCALE: '[data-tid="e04f4bad"]',
            INPUT: '[data-tid="98d55629"]',
        },
        NOTICE: {
            INPUT_SEARCH: '[data-tid="323d56ca"]',
        },
        QNA: {
            BUTTON_CANCEL: '[data-tid="aa2cdc94"]',
            BUTTON_CLICK_CANCEL: '[data-tid="b8d260a1"]',
            BUTTON_CLICK_GO_TO_LIST: '[data-tid="a7e5b571"]',
            BUTTON_CLICK_SUBMIT: '[data-tid="c55cda92"]',
            BUTTON_CREATE_QNA: '[data-tid="21a1fe0f"]',
            EDITOR: '[data-tid="4eba3384"]',
            EDITOR_1: '[data-tid="6a608f18"]',
            INPUT: '[data-tid="1ce34671"]',
            INPUT_SEARCH: '[data-tid="bf62ae10"]',
            SELECT_STATUS: '[data-tid="ec391e86"]',
        },
        SEARCH: {
            BUTTON_DOWNLOAD: '[data-tid="818900a9"]',
            BUTTON_FILTER_SEARCH: '[data-tid="491ea10f"]',
            DATEPICKER: '[data-tid="7112fff6"]',
            DATEPICKER_START: '[data-tid="18e46b25"]',
            INPUT: '[data-tid="b41097b3"]',
            INPUT_1: '[data-tid="8576e9f9"]',
            PAGINATION: '[data-tid="dbdc79a5"]',
            SELECT: '[data-tid="0d9bb54c"]',
        },
    }
};
