-- Seed: ApiEndpoints from lawform api.md (670 records)
INSERT INTO `ApiEndpoints` (`method`, `path`, `description`, `tags`, `auth_required`, `project_key`, `created_at`, `updated_at`) VALUES
('GET', '/api/admin/admin_permission/', '관리자 권한 목록', '["admin", "admin_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/admin_permission/:id', '관리자 권한 상세', '["admin", "admin_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/admin_permission/:id', '관리자 권한 수정', '["admin", "admin_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/admin_permission/:id', '관리자 권한 삭제', '["admin", "admin_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/banner/update/dev_id', '배너 dev_id 수정', '["admin", "banner"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/banner/find/dev_id/:dev_id', 'dev_id로 배너 조회', '["admin", "banner"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/banner/group/:group_id', 'group_id로 배너 조회', '["admin", "banner"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/banner/create/', '배너 생성', '["admin", "banner"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/banner/update/', '배너 수정', '["admin", "banner"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/banner/delete/:id', '배너 삭제', '["admin", "banner"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/blog/create', '블로그 생성', '["admin", "blog"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/blog/detail/:id', '블로그 상세', '["admin", "blog"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/blog/update', '블로그 수정', '["admin", "blog"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/blog/list', '블로그 목록', '["admin", "blog"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/cfs_file/', 'CFS 파일 생성', '["admin", "cfs_file"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/coupon_v2/', '쿠폰 목록', '["admin", "coupon_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/coupon_v2/:id', '쿠폰 상세', '["admin", "coupon_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/coupon_v2/create', '쿠폰 생성', '["admin", "coupon_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/coupon_v2/update', '쿠폰 수정', '["admin", "coupon_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/coupon_v2/delete', '쿠폰 삭제', '["admin", "coupon_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/document_sample/create', '샘플 문서 지정', '["admin", "document_sample"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/documents/', '문서 전체 조회', '["admin", "documents"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/documents/find', 'documents 테이블 조회', '["admin", "documents"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/documents/create', '문서 생성', '["admin", "documents"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/documents/update', '문서 수정', '["admin", "documents"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/documents/duplicate', '문서 복제', '["admin", "documents"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/documents_contact/:document_id', '문서 인적정보 설정 조회', '["admin", "documents_contact"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/documents_contact/delete', '문서 인적정보 설정 삭제', '["admin", "documents_contact"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/documents_contact/create', '문서 인적정보 설정 저장', '["admin", "documents_contact"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/documents_info/list', '문서 정보 목록', '["admin", "documents_info"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/documents_info/:document_id', '문서 상세 정보', '["admin", "documents_info"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/documents_info/docs_info', '문서 docs_info 업데이트', '["admin", "documents_info"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/documents_template/list', '문서 템플릿 목록', '["admin", "documents_template"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/documents_template/', '문서 템플릿 생성', '["admin", "documents_template"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/documents_template/:id', '문서 템플릿 상세', '["admin", "documents_template"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/email_template/testsend', '이메일 테스트 전송', '["admin", "email_template"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/email_template/:id', '이메일 템플릿 상세', '["admin", "email_template"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/email_template/', '이메일 템플릿 목록', '["admin", "email_template"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/email_template/update/devid', 'dev_id로 이메일 템플릿 수정', '["admin", "email_template"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/esign/', '전자서명 목록', '["admin", "esign"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/faq_category/', 'FAQ 대카테고리 목록', '["admin", "faq_category"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/faq_category/:id', 'FAQ 대카테고리 상세', '["admin", "faq_category"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/faq_category/', 'FAQ 대카테고리 등록', '["admin", "faq_category"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/faq_category/', 'FAQ 대카테고리 수정', '["admin", "faq_category"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/faq_category/:id', 'FAQ 대카테고리 삭제', '["admin", "faq_category"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/faq_subcategory/', 'FAQ 소카테고리 목록', '["admin", "faq_subcategory"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/faq_subcategory/:id', 'FAQ 소카테고리 상세', '["admin", "faq_subcategory"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/faq_subcategory/', 'FAQ 소카테고리 등록', '["admin", "faq_subcategory"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/faq_subcategory/', 'FAQ 소카테고리 수정', '["admin", "faq_subcategory"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/faq_subcategory/:id', 'FAQ 소카테고리 삭제', '["admin", "faq_subcategory"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/faq/', 'FAQ 목록', '["admin", "faq"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/faq/:id', 'FAQ 상세', '["admin", "faq"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/faq/', 'FAQ 등록', '["admin", "faq"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/faq/', 'FAQ 수정', '["admin", "faq"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/faq/:id', 'FAQ 삭제', '["admin", "faq"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/inquiry/update', '문의 수정', '["admin", "inquiry"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/law_information/initialize', '법령 초기 데이터 적재', '["admin", "law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/lawdoc/', '변호사첨삭 목록', '["admin", "lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/login/force', '관리자 강제 로그인', '["admin", "login"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/login/email', '관리자 이메일 로그인', '["admin", "login"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/magazine_v2/', '매거진 목록', '["admin", "magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/magazine_v2/find', '매거진 전체 목록', '["admin", "magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/magazine_v2/:id', '매거진 상세', '["admin", "magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/magazine_v2/create', '매거진 등록', '["admin", "magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/magazine_v2/update', '매거진 수정', '["admin", "magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/magazine_v2/update/recommended', '추천 매거진 설정', '["admin", "magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/magazine_v2/remove', '매거진 삭제', '["admin", "magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/multi_team/member', '팀 멤버 등록', '["admin", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/multi_team/', '기업/부서/팀 생성', '["admin", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/multi_team/upload/structure', '조직도 엑셀 업로드', '["admin", "multi_team"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/multi_team/upload/members', '멤버 엑셀 업로드', '["admin", "multi_team"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/multi_team/member', '팀 멤버 권한 업데이트', '["admin", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/multi_team/member/cancel', '팀 멤버 취소', '["admin", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/multi_team/', '멀티팀 수정', '["admin", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/multi_team/member/:delete_user_id/:multi_team_id', '팀 멤버 삭제', '["admin", "multi_team"]', 0, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/multi_team/:multi_team_id', '멀티팀 삭제', '["admin", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/news_board', '뉴스 생성', '["admin", "news_board"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/news_board', '뉴스 수정', '["admin", "news_board"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/news_board', '뉴스 삭제', '["admin", "news_board"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/notice/', '공지사항 목록', '["admin", "notice"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/notice/:id', '공지사항 상세', '["admin", "notice"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/notice/', '공지사항 등록', '["admin", "notice"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/notice/', '공지사항 수정', '["admin", "notice"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/notice/:id', '공지사항 삭제', '["admin", "notice"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/notification_template/', '알림 템플릿 목록', '["admin", "notification_template"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/notification_template/:id', '알림 템플릿 상세', '["admin", "notification_template"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/notification_template/', '알림 템플릿 생성', '["admin", "notification_template"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/notification_template/', '알림 템플릿 수정', '["admin", "notification_template"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/notification_template/:id', '알림 템플릿 삭제', '["admin", "notification_template"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/notify/github_action_failed', 'Github Action 실패 알림', '["admin", "notify"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/notify/github_action_deploy', 'Github Action 배포 알림', '["admin", "notify"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/notify/attorney_register', '변호사 계정 신청 알림', '["admin", "notify"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/permission/', '권한 목록', '["admin", "permission"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/preliminary_startup_request/', '예비창업 신청 목록', '["admin", "preliminary_startup_request"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/preliminary_startup_request/:id', '예비창업 신청 상세', '["admin", "preliminary_startup_request"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/preliminary_startup_request/:id', '예비창업 신청서 수정', '["admin", "preliminary_startup_request"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/purchase/', '구매/환불 목록', '["admin", "purchase"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/push_queue/', '푸시 큐 목록', '["admin", "push_queue_/_push_template"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/push_template/', '푸시 템플릿 목록', '["admin", "push_queue_/_push_template"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/push_template/:id', '푸시 템플릿 상세', '["admin", "push_queue_/_push_template"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/push_template/', '푸시 템플릿 등록', '["admin", "push_queue_/_push_template"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/push_template/', '푸시 템플릿 수정', '["admin", "push_queue_/_push_template"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/recommendation_board', '추천 게시판 수정', '["admin", "recommendation_board"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/rurl/', '단축 URL 목록', '["admin", "rurl"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/rurl/:id', '단축 URL 상세', '["admin", "rurl"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/rurl/', '단축 URL 생성', '["admin", "rurl"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/rurl/:id', '단축 URL 수정', '["admin", "rurl"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/rurl/:id', '단축 URL 삭제', '["admin", "rurl"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/sms_template/', 'SMS 템플릿 목록', '["admin", "sms_template"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/sms_template/:dev_id', 'SMS 템플릿 상세', '["admin", "sms_template"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/sms_template/', 'SMS 템플릿 수정', '["admin", "sms_template"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/sms_template/testsend/:dev_id', 'SMS 템플릿 테스트 전송', '["admin", "sms_template"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/startup/list', '스타트업 목록', '["admin", "startup"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/startup/:id', '스타트업 상세', '["admin", "startup"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/startup/create', '스타트업 생성', '["admin", "startup"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/startup/update', '스타트업 수정', '["admin", "startup"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/team/create', '팀 생성', '["admin", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/team/find/:id', '팀 상세', '["admin", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/team/list', '팀 목록', '["admin", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/team/member/list', '팀 멤버 목록', '["admin", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/team/update/permission', '팀 권한 업데이트', '["admin", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/theme/', '테마 목록', '["admin", "theme_/_theme_sub"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/theme/detail/:theme_id', '테마 상세', '["admin", "theme_/_theme_sub"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/theme/create', '테마 등록', '["admin", "theme_/_theme_sub"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/theme/update', '테마 수정', '["admin", "theme_/_theme_sub"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/theme_sub/:document_id', '하위 테마 조회', '["admin", "theme_/_theme_sub"]', 0, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/theme_sub/remove/:id', '하위 테마 삭제', '["admin", "theme_/_theme_sub"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/user/', '회원 목록', '["admin", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/admin/user/:user_id', '회원 탈퇴 처리', '["admin", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/user/drive_filter', '이용권 필터 회원 목록', '["admin", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/user/drive_csv', '이용권 필터 회원 CSV', '["admin", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/user_favorite/', '문서 즐겨찾기 목록', '["admin", "user_favorite_/_user_login_/_user_money_log_/_user_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/user_login/list', '회원 로그인 기록', '["admin", "user_favorite_/_user_login_/_user_money_log_/_user_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/user_money_log/create', '포인트 기록 생성', '["admin", "user_favorite_/_user_login_/_user_money_log_/_user_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/user_money_log/', '포인트 사용 기록', '["admin", "user_favorite_/_user_login_/_user_money_log_/_user_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/user_permission/', '이용권 목록', '["admin", "user_favorite_/_user_login_/_user_money_log_/_user_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/user_permission/:id', '이용권 상세', '["admin", "user_favorite_/_user_login_/_user_money_log_/_user_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/user_permission/update', '이용권 수정', '["admin", "user_favorite_/_user_login_/_user_money_log_/_user_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/user_permission/update/cloud_action', '이용권 클라우드 액션 수정', '["admin", "user_favorite_/_user_login_/_user_money_log_/_user_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/user_permission/update/duration_date', '이용권 기간 수정', '["admin", "user_favorite_/_user_login_/_user_money_log_/_user_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/user_signup_path/', '가입 경로 목록', '["admin", "user_signup_path_/_writing_preview_/_writing_temp"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/user_signup_path/create', '가입 경로 생성', '["admin", "user_signup_path_/_writing_preview_/_writing_temp"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/admin/user_signup_path/update', '가입 경로 수정', '["admin", "user_signup_path_/_writing_preview_/_writing_temp"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/admin/writing_preview/group_list', '작성 미리보기 그룹 목록', '["admin", "user_signup_path_/_writing_preview_/_writing_temp"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/admin/writing_temp/create', '임시 작성 문서 생성', '["admin", "user_signup_path_/_writing_preview_/_writing_temp"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/advice/cron/deadline', '마감 임박 자문 크론', '["lawform", "advice_(법률_자문)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/advice/cron/over_deadline', '마감 초과 자문 크론', '["lawform", "advice_(법률_자문)"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/advice/create/draft', '자문 초안 생성', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/advice/list', '자문 목록', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/advice/counts', '자문 상태별 수', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/advice/statistics', '자문 통계', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/advice/:id', '자문 상세', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice/update/is_editor_used_disable', '편집기 사용 안함', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/advice/history/list', '계약서 변경내역', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice/update/:id', '자문 수정', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice/update/progress_status/:id/review_request', '자문 검토 요청', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice/update/progress_status/:id/advice_reviewer_to_requester', '요청자에게 보내기', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice/update/progress_status/:id/requester_to_advice_reviewer', '자문 담당자에게 보내기', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice/update/progress_status/:id/cancel', '자문 취소', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice/update/progress_status/:id/complete', '자문 완료', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice/update/progress_status/:id/pause', '자문 중단', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/advice/delete/draft', '자문 초안 삭제', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice/update/progress_status/recipient_resent', '재수신', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/advice/excel', '엑셀 다운로드', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/advice/file/download', '첨부파일 다운로드', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice/update/watermark/:advice_id', '워터마크 업데이트', '["lawform", "advice_(법률_자문)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice_approval_user/update/legal_advice_users', '자문 담당자 배정', '["lawform", "advice_approval_user"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice_approval_user/update/approval_users/approved', '결재 승인/반려', '["lawform", "advice_approval_user"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice_approval_user/:advice_id/referrer', '참조자 업데이트', '["lawform", "advice_approval_user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/advice_attachment/upload/', '자문 첨부파일 업로드', '["lawform", "advice_attachment"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/advice_attachment/download/', '자문 첨부파일 다운로드', '["lawform", "advice_attachment"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice_attachment/remove', '자문 첨부파일 삭제', '["lawform", "advice_attachment"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/advice_category/list', '카테고리 목록', '["lawform", "advice_category"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/advice_category/', '카테고리 생성', '["lawform", "advice_category"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/advice_category/:id', '카테고리 삭제', '["lawform", "advice_category"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/advice_log/create', '자문 로그 생성', '["lawform", "advice_log_/_advice_log_attachment"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/advice_log/update/:advice_id/:advice_log_id', '자문 로그 수정', '["lawform", "advice_log_/_advice_log_attachment"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/advice_log/list/', '자문 로그 목록', '["lawform", "advice_log_/_advice_log_attachment"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/advice_log/remove', '자문 로그 삭제', '["lawform", "advice_log_/_advice_log_attachment"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/advice_log_attachment/download', '로그 첨부파일 다운로드', '["lawform", "advice_log_/_advice_log_attachment"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/article/', '게시글 목록', '["lawform", "article_/_article_comment"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/article/:id', '게시글 상세', '["lawform", "article_/_article_comment"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/article/', '게시글 생성', '["lawform", "article_/_article_comment"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/article/', '게시글 수정', '["lawform", "article_/_article_comment"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/article/heart_count', '게시글 좋아요', '["lawform", "article_/_article_comment"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/article/:id', '게시글 삭제', '["lawform", "article_/_article_comment"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/article_comment/', '댓글 생성', '["lawform", "article_/_article_comment"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/article_comment/', '댓글 수정', '["lawform", "article_/_article_comment"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/article_comment/heart_count', '댓글 좋아요', '["lawform", "article_/_article_comment"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/article_comment/:id', '댓글 삭제', '["lawform", "article_/_article_comment"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/autodoc/:id', '자동작성 문서 상세', '["lawform", "autodoc_(자동작성)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/autodoc/', '자동작성 문서 목록', '["lawform", "autodoc_(자동작성)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/autodoc/create', '자동작성 문서 생성', '["lawform", "autodoc_(자동작성)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/autodoc/duplicate', '자동작성 문서 복제', '["lawform", "autodoc_(자동작성)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/autodoc/duplicate/v2', '자동작성 문서 복제 v2', '["lawform", "autodoc_(자동작성)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/autodoc/email/send', 'PDF 이메일 공유', '["lawform", "autodoc_(자동작성)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/autodoc/send/email/v2', 'PDF 이메일 공유 v2', '["lawform", "autodoc_(자동작성)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/autodoc/update/editormode', '편집기 모드 전환', '["lawform", "autodoc_(자동작성)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/autodoc/save/editorhtml', '편집기 내용 저장', '["lawform", "autodoc_(자동작성)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/autodoc/update/editorhtml/v2', '편집기 내용 저장 v2', '["lawform", "autodoc_(자동작성)"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/autodoc/update/binddata', 'bind data 업데이트', '["lawform", "autodoc_(자동작성)"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/autodoc/generate/pdf', 'PDF 생성', '["lawform", "autodoc_(자동작성)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/blog/list', '블로그 목록', '["lawform", "blog"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/blog/detail/:id', '블로그 상세', '["lawform", "blog"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/blog/recommend', '추천 블로그', '["lawform", "blog"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/blog/update/view-count/:id', '블로그 조회수 업데이트', '["lawform", "blog"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/business_active_log/', '활동 로그 생성', '["lawform", "business_active_log"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/business_active_log/list/:clm_id', '활동 로그 목록', '["lawform", "business_active_log"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/business_active_log/clm/:id', 'CLM 활동 로그 상세', '["lawform", "business_active_log"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/business_email_message/detail', '이메일 상세', '["lawform", "business_email_message"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/business_email_message/create', '이메일 답장 기록 생성', '["lawform", "business_email_message"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/business_email_message/attachment/download', '이메일 첨부파일 다운로드', '["lawform", "business_email_message"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/business_email_message/update/message_key', '이메일 메시지 키 업데이트', '["lawform", "business_email_message"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/business_email_message/create/testcase', '테스트 케이스 메일 생성', '["lawform", "business_email_message"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/business_inquiry/', '비즈니스 도입 문의', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/business_internal_notice', '내부 공지사항 목록', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/business_internal_notice/latest', '내부 공지사항 최근', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/business_internal_notice/:id', '내부 공지사항 상세', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/business_internal_notice', '내부 공지사항 생성', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/business_internal_notice/:id', '내부 공지사항 수정', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/business_internal_notice/:id', '내부 공지사항 삭제', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/business_notice/', '비즈니스 공지사항 목록', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/business_notice/:id', '비즈니스 공지사항 상세', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/business_partner_team/', '파트너 팀 목록', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/business_partner_team/', '파트너 팀 생성', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/business_partner_team/:id', '파트너 팀 삭제', '["lawform", "business_inquiry_/_internal_notice_/_notice_/_partner_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/cfs/drive', '마이로폼 드라이브 조회', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/cfs/', 'CFS 목록', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/cfs/guest', 'CFS 목록 (guest_id)', '["lawform", "cfs_(cloud_file_system)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/cfs/:id', 'CFS 상세', '["lawform", "cfs_(cloud_file_system)"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/find/share', 'CFS 공유 상세', '["lawform", "cfs_(cloud_file_system)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/cfs/html/:clm_id', 'CFS HTML (CLM)', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/cfs/cfs_html/:cfs_id', 'CFS HTML', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/cfs/html/advice/:advice_id', 'CFS HTML (자문)', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/create/autodoc', '자동작성 CFS 생성', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/create/esign', '전자서명 CFS 생성', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/create/folder', 'CFS 폴더 생성', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/create/file', 'CFS 파일 생성', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/create/link', 'CFS 링크 생성', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/remove', 'CFS 삭제', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/cfs/update', 'CFS 업데이트', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/breadcrumb', 'CFS 브레드크럼', '["lawform", "cfs_(cloud_file_system)"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/move', 'CFS 폴더 이동', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/cfs/folder/rename', 'CFS 폴더 이름 변경', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/doc/download', '워드 파일 다운로드', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/pdf/download', 'PDF 다운로드', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/create/standard_contract', '표준계약서 CFS 생성', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs/file/download', 'CFS 파일 다운로드', '["lawform", "cfs_(cloud_file_system)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs_collaborator/create/invite', '협업자 초대', '["lawform", "cfs_collaborator"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/cfs_collaborator/remove/:cfs_id/:cfs_collaborator_id/:remove_id', '협업자 삭제', '["lawform", "cfs_collaborator"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/cfs_collaborator/update/access', '협업자 접근 권한 변경', '["lawform", "cfs_collaborator"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/cfs_collaborator/update/owner', '소유자 변경', '["lawform", "cfs_collaborator"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs_collaborator/request/permission', '접근 권한 요청', '["lawform", "cfs_collaborator"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/cfs_collaborator/request/permission/approve/:cfs_id/:owner_collaborator_id/:requester_user_id/:checksum', '접근 권한 요청 승인', '["lawform", "cfs_collaborator"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/cfs_collaborator/file/access/:cfs_file_id/:cfs_id/:cfs_collaborator_id', '파일 접근 권한 확인', '["lawform", "cfs_collaborator"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/cfs_collaborator/token', '협업자 토큰 생성', '["lawform", "cfs_collaborator"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm/create', 'CLM 생성', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm/create/plain', '문서 지정 없이 CLM 생성', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm/create/seal', '인감증명 신청', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm/create/separately', '별도 등록 CLM', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm/create/standard', '표준계약서 CLM 생성', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm/', 'CLM 목록', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm/review_status', 'CLM 대시보드 통계', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm/counts', 'CLM 진행 현황', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm/:id', 'CLM 상세', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm/:clmId/cfsFileHistory', '파일 변경 이력', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm/excel', 'CLM 엑셀 다운로드', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm/draft/remove', 'CLM draft 삭제', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/draft', 'CLM draft 업데이트', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/legal_user_id', '법무 담당자 변경', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/change/cfs', '계약서 문서 교체', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/cancel/', 'CLM 취소', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/progress_status/legal_review', '법무 검토 중으로 변경', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/progress_status/legalAction', '법무 액션 처리', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/progress_status/financial_review', '재무 검토 중으로 변경', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/progress_status/financial_review_complete', '재무 검토 완료', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/progress_status/final_review', '최종 결재 요청', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/progress_status/review/cancel', '검토 신청 취소', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/progress_status/rollback', '진행 단계 되돌리기', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/progress_status/recipient_resent', '수신자 재발송', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/auto_extend_status', '자동연장 상태 업데이트', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/pause', 'CLM 일시중지', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/legal_review_approval/request', '법무 검토 완료 승인 요청', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/legal_review_approval', '법무 검토 완료 승인', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm/update/watermark/:clm_id', '워터마크 업데이트', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/clm/cfsFileHistory', '파일 변경 이력 삭제', '["lawform", "clm_(계약_관리)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm_approval_flow/', '결재선 목록', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm_approval_flow/', '결재선 생성', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm_approval_flow/', '결재선 수정', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm_approval_flow/upsert', '결재선 upsert', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/clm_approval_flow/:id', '결재선 삭제', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm_approval_user/list/', '결재자 목록', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm_approval_user/create/', '결재자 추가', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm_approval_user/submit', '결재 상신', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm_approval_user/update/approved', '결재 승인', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm_approval_user/update/legal_users', '법무 검토 담당자 변경', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm_attachment/create/', '첨부파일 업로드', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm_attachment/download', '첨부파일 다운로드', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm_attachment/remove', '첨부파일 삭제', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm_category/', '카테고리 목록', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm_category/', '카테고리 생성', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm_category/', '카테고리 수정', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/clm_category/:type/:id', '카테고리 삭제', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm_customer/list/', '계약 상대방 목록', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm_customer/create/', '계약 상대방 추가', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm_customer/remove', '계약 상대방 삭제', '["lawform", "clm_approval_flow_/_approval_user_/_attachment_/_category_/_customer"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm_log/list', '업무 일지 목록', '["lawform", "clm_log_/_clm_notification_/_clm_thirdparty_approval"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm_log/create', '업무 일지 생성', '["lawform", "clm_log_/_clm_notification_/_clm_thirdparty_approval"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm_log/update/:clm_log_id', '업무 일지 수정', '["lawform", "clm_log_/_clm_notification_/_clm_thirdparty_approval"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/clm_log/remove', '업무 일지 삭제', '["lawform", "clm_log_/_clm_notification_/_clm_thirdparty_approval"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm_notification/', '알림 목록', '["lawform", "clm_log_/_clm_notification_/_clm_thirdparty_approval"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm_notification/read', '알림 읽음 처리', '["lawform", "clm_log_/_clm_notification_/_clm_thirdparty_approval"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/clm_thirdparty_approval/', '서드파티 기안 목록', '["lawform", "clm_log_/_clm_notification_/_clm_thirdparty_approval"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/clm_thirdparty_approval/', '서드파티 기안 생성', '["lawform", "clm_log_/_clm_notification_/_clm_thirdparty_approval"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/comment/', '댓글 목록', '["lawform", "comment_/_coupon_v2_/_curation_bookmark"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/comment/create', '댓글 생성', '["lawform", "comment_/_coupon_v2_/_curation_bookmark"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/comment/update/content', '댓글 수정', '["lawform", "comment_/_coupon_v2_/_curation_bookmark"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/comment/remove/:id', '댓글 삭제', '["lawform", "comment_/_coupon_v2_/_curation_bookmark"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/coupon_v2/register', '쿠폰 등록', '["lawform", "comment_/_coupon_v2_/_curation_bookmark"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/coupon_v2/woorievent', '우리은행 이벤트 쿠폰', '["lawform", "comment_/_coupon_v2_/_curation_bookmark"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/curation_bookmark/create', '큐레이션 북마크 생성', '["lawform", "comment_/_coupon_v2_/_curation_bookmark"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/curation_bookmark/remove/:id', '큐레이션 북마크 삭제', '["lawform", "comment_/_coupon_v2_/_curation_bookmark"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/v2/document/find/category', '문서 카테고리 목록', '["lawform", "document_/_document_compare_/_document_contact_/_document_sample_/_documents_info"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/v2/document/find/theme', '문서 테마 목록', '["lawform", "document_/_document_compare_/_document_contact_/_document_sample_/_documents_info"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/v2/document/ranking', '인기 문서', '["lawform", "document_/_document_compare_/_document_contact_/_document_sample_/_documents_info"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/document_compare/compare', '문서 비교', '["lawform", "document_/_document_compare_/_document_contact_/_document_sample_/_documents_info"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/documents_contact/:document_id', '문서 인적정보 설정', '["lawform", "document_/_document_compare_/_document_contact_/_document_sample_/_documents_info"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/document_sample/find/:document_id', '샘플 문서 단건', '["lawform", "document_/_document_compare_/_document_contact_/_document_sample_/_documents_info"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/document_sample/list', '샘플 문서 목록', '["lawform", "document_/_document_compare_/_document_contact_/_document_sample_/_documents_info"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/documents_info/', '문서 정보 목록', '["lawform", "document_/_document_compare_/_document_contact_/_document_sample_/_documents_info"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/documents_info/:document_id', '문서 상세 정보', '["lawform", "document_/_document_compare_/_document_contact_/_document_sample_/_documents_info"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/diningbrands/download/contract', '계약서 다운로드', '["lawform", "diningbrands_/_education_/_events"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/diningbrands/check/approval', '기안 내역 확인', '["lawform", "diningbrands_/_education_/_events"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/diningbrands/approval', '그룹웨어 기안 상신', '["lawform", "diningbrands_/_education_/_events"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/education/', '교육 섹션 목록', '["lawform", "diningbrands_/_education_/_events"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/education/:id', '교육 상세', '["lawform", "diningbrands_/_education_/_events"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/events/', '이벤트 목록', '["lawform", "diningbrands_/_education_/_events"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/events/:id', '이벤트 상세', '["lawform", "diningbrands_/_education_/_events"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/events/', '이벤트 생성', '["lawform", "diningbrands_/_education_/_events"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/events/', '이벤트 수정', '["lawform", "diningbrands_/_education_/_events"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/events/:id', '이벤트 삭제', '["lawform", "diningbrands_/_education_/_events"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/v2/esign/signer/:id', '서명자 정보 조회', '["lawform", "esign_(전자서명)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/v2/esign/signer_enc/:id', '서명자 정보 조회 (암호화)', '["lawform", "esign_(전자서명)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/v2/esign/signer_token/:token', '토큰으로 서명자 정보 조회', '["lawform", "esign_(전자서명)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/v2/esign/', '전자서명 목록', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/v2/esign/possible/documents', '전자서명 가능 문서', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/v2/esign/pending/signer/', '본인 서명 대기 목록', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/v2/esign/:id', '전자서명 단건', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/v2/esign/', '전자서명 생성', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/v2/esign/clm', 'CLM 전자서명 생성', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/v2/esign/register/complete', '전자서명 등록 완료', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/v2/esign/signer/sign/complete/esign/:id', '서명자 서명 완료 (esign 방식)', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/v2/esign/signer/sign/complete', '서명자 서명 완료', '["lawform", "esign_(전자서명)"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/v2/esign/resend/invitation', '참여 메시지 재발송', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/v2/esign/generate/pdf/:id', '전자서명 PDF', '["lawform", "esign_(전자서명)"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/v2/esign/generate/certificate/:id', '인증서 생성', '["lawform", "esign_(전자서명)"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/v2/esign/buy/action', '전자서명 구매 액션', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/v2/esign/upload/attachment', '첨부파일 업로드', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/v2/esign/', '전자서명 업데이트', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/v2/esign/deadline', '마감일 업데이트', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/v2/esign/progress_status', '진행 상태 업데이트', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/v2/esign/cancel', '서명 취소', '["lawform", "esign_(전자서명)"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/v2/esign/bulk_cancel', '서명 일괄 취소', '["lawform", "esign_(전자서명)"]', 0, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/v2/esign/:id', '전자서명 삭제', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/v2/esign/attachment/:id', '첨부파일 삭제', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/v2/esign/signer/sign', '사인박스 삭제', '["lawform", "esign_(전자서명)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/faq/', 'FAQ 목록', '["lawform", "faq_/_faq_category_/_faq_subcategory"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/faq/external', '외부 FAQ', '["lawform", "faq_/_faq_category_/_faq_subcategory"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/faq/:id', 'FAQ 상세', '["lawform", "faq_/_faq_category_/_faq_subcategory"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/faq/', 'FAQ 생성', '["lawform", "faq_/_faq_category_/_faq_subcategory"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/faq/', 'FAQ 수정', '["lawform", "faq_/_faq_category_/_faq_subcategory"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/faq/:id', 'FAQ 삭제', '["lawform", "faq_/_faq_category_/_faq_subcategory"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/faq_category/', 'FAQ 대카테고리 목록', '["lawform", "faq_/_faq_category_/_faq_subcategory"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/faq_category/:id', 'FAQ 대카테고리 상세', '["lawform", "faq_/_faq_category_/_faq_subcategory"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/faq_subcategory/', 'FAQ 소카테고리 목록', '["lawform", "faq_/_faq_category_/_faq_subcategory"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/faq_subcategory/:id', 'FAQ 소카테고리 상세', '["lawform", "faq_/_faq_category_/_faq_subcategory"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/inquiry/', '문의 목록', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/inquiry/:id', '문의 상세', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/inquiry/create', '문의 생성', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/kwork/github/action/failed', 'GitHub 빌드 실패 알림', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/kwork/github/action/deploy', 'GitHub 배포 알림', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/law_information/list', '법령 목록', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/law_information/detail/:id', '법령 상세', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/law_information/date/list', '날짜별 법령 목록', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/law_information/nearest_enforcement', '가장 가까운 시행일 법령', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/lawdoc/', '변호사첨삭 목록', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/lawdoc/:id', '변호사첨삭 상세', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/lawdoc/create', '변호사첨삭 등록', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/lawdoc/update/lawyer_html', '변호사 수정 HTML', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/lawdoc/update/accept_review', '검토 요청 수락', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/lawdoc/update/complete_review', '검토 완료', '["lawform", "inquiry_/_kwork_/_law_information_/_lawdoc"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation/list', '송무 목록', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation/statistics', '담당자별 통계', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation/:id', '송무 상세', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation/cron/coming_command_schedule', '크론: 기일 알림', '["lawform", "litigation_(송무)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation/cron/delivery_of_response_schedule', '크론: 답변서 송달 알림', '["lawform", "litigation_(송무)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation/cron/auto_complete', '크론: 자동 종결', '["lawform", "litigation_(송무)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation/cron/appeal', '크론: 항소 알림', '["lawform", "litigation_(송무)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation/cron/generate', '크론: 법원 스크랩 큐 생성', '["lawform", "litigation_(송무)"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation/cron/court-scrap', '크론: 법원 스크랩 실행', '["lawform", "litigation_(송무)"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/litigation/excel', '송무 엑셀 다운로드', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/litigation/create/draft', '송무 draft 생성', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/litigation/update/:id', '송무 수정', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/litigation/update/progress_status/:id/wait_designation', '송무 등록', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/litigation/update/progress_status/:id/pause', '송무 중단', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/litigation/update/progress_status/:id/complete', '송무 종결', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/litigation_approval_user/update/legal_users', '송무 담당자 배정', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/litigation_attachment/upload/', '송무 첨부파일 업로드', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/litigation_log/create', '송무 일지 생성', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation_log/list', '송무 일지 목록', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/litigation_log/update/:id', '송무 일지 수정', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/litigation_schedule/create', '송무 일정 생성', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation_schedule/list/', '송무 일정 목록', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/litigation_schedule/calendar', '송무 캘린더', '["lawform", "litigation_(송무)"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/login/email', '이메일 로그인', '["lawform", "login_/_logo_/_magazine_v2"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/login/otp', 'OTP 로그인', '["lawform", "login_/_logo_/_magazine_v2"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/login/google', '구글 로그인', '["lawform", "login_/_logo_/_magazine_v2"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/login/dining', '다이닝브랜즈 SSO', '["lawform", "login_/_logo_/_magazine_v2"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/logo/', '로고 조회', '["lawform", "login_/_logo_/_magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/logo/', '로고 생성', '["lawform", "login_/_logo_/_magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/logo/', '로고 수정', '["lawform", "login_/_logo_/_magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/logo/:id', '로고 삭제', '["lawform", "login_/_logo_/_magazine_v2"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/magazine_v2/', '매거진 목록', '["lawform", "login_/_logo_/_magazine_v2"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/magazine_v2/:id', '매거진 상세', '["lawform", "login_/_logo_/_magazine_v2"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/magazine_v2/top/list', '매거진 TOP 목록', '["lawform", "login_/_logo_/_magazine_v2"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/magazine_v2/update/heart_count', '매거진 좋아요', '["lawform", "login_/_logo_/_magazine_v2"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/multi_team/invite/member', '멤버 초대', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/multi_team/member/count', '팀 인원수', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/multi_team/low/company/list', '하위 기업 목록', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/multi_team/all/company/list', '상하위 기업 목록', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/multi_team/tree/list', '기업 트리 구조', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/multi_team/list/member', '팀 멤버 조회', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/multi_team/list/team', '기업 팀 조회', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/multi_team/detail/member/:detail_user_id', '멤버 상세', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/multi_team/detail/member/:detail_user_id/clm', '멤버 CLM 문서', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/multi_team/member/permission', '멤버 권한 업데이트', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/multi_team/remove/member/:remove_user_id', '멤버 제외', '["lawform", "multi_team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/notice/', '공지사항 목록', '["lawform", "notice_/_pdf_/_permission"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/notice/:id', '공지사항 상세', '["lawform", "notice_/_pdf_/_permission"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/pdf/team/autodoc/:type', '자동작성 PDF 생성', '["lawform", "notice_/_pdf_/_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/pdf/team/esign', '전자서명 PDF 생성', '["lawform", "notice_/_pdf_/_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/pdf/tlimit/:type/:start/:end/:writing_id/:hash', 'TLimit PDF', '["lawform", "notice_/_pdf_/_permission"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/pdf/permission/:type/:item_id/:action', '권한 검증 PDF 다운로드', '["lawform", "notice_/_pdf_/_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/pdf/html', 'HTML -> PDF 변환', '["lawform", "notice_/_pdf_/_permission"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/permission/give', '이용권 지급', '["lawform", "notice_/_pdf_/_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/permission/check', '이용권 확인', '["lawform", "notice_/_pdf_/_permission"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/polaris/advice/update/:id', 'Advice 수정', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/polaris/comparison/', '문서 비교 요청', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/polaris/comparison/', '문서 비교 결과 (polling)', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/polaris/cfs/get', '편집기 데이터 조회', '["lawform", "polaris"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/polaris/cfs/save', '편집기 데이터 저장', '["lawform", "polaris"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/polaris/cfs/history/list', '히스토리 목록', '["lawform", "polaris"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/polaris/cfs/download/file', 'CFS 파일 다운로드', '["lawform", "polaris"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/polaris/cfs/create/file', 'CFS 파일 생성', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/polaris/clm/create', 'CLM 생성', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/polaris/clm/update/change/cfs', 'CLM 계약서 교체', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/polaris/esign/', 'Esign 생성', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/polaris/esign/clm', 'CLM Esign 생성', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/polaris/lawdoc/list', '변호사첨삭 목록', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/polaris/lawdoc/create', '변호사첨삭 등록', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/polaris/team_standard_contract/list', '표준계약서 목록', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/polaris/team_standard_contract/create/', '표준계약서 생성', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/polaris/watermark/create', '워터마크 생성', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/polaris/watermark/list', '워터마크 목록', '["lawform", "polaris"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/press/', '보도자료 목록', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/press/', '보도자료 생성', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/press/', '보도자료 수정', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/press/:id', '보도자료 삭제', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/project/list', '프로젝트 목록', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/project/', '프로젝트 생성', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/project/', '프로젝트 수정', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/project/log', '프로젝트 로그 생성', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/project_clm/:id', '프로젝트 CLM 삭제', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/purchase/', '결제 신청', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/purchase/update/fe_log', '결제 완료 (FE)', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/purchase/update/be_log', '결제 완료 (BE)', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/purchase/toss/confirm', '토스 결제 승인', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/pusher/auth', 'Pusher 인증', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/pusher/webhook', 'Pusher 웹훅', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/quiz/today', '오늘의 퀴즈', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/quiz/submit', '퀴즈 정답 제출', '["lawform", "press_/_project_/_purchase_/_pusher_/_quiz"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/register/email', '이메일 회원가입', '["lawform", "register_/_rurl_/_search"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/register/kakaosync', '카카오 회원가입', '["lawform", "register_/_rurl_/_search"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/register/naver', '네이버 회원가입', '["lawform", "register_/_rurl_/_search"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/register/google', '구글 회원가입', '["lawform", "register_/_rurl_/_search"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/register/clm/invited', 'CLM 초대 가입', '["lawform", "register_/_rurl_/_search"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/register/email/duplicate/check', '이메일 중복 확인', '["lawform", "register_/_rurl_/_search"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/register/trial', '시험 사용 계정 생성', '["lawform", "register_/_rurl_/_search"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/rurl/code', '단축 URL 조회', '["lawform", "register_/_rurl_/_search"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/search/', '검색', '["lawform", "register_/_rurl_/_search"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/search/', '통합 검색', '["lawform", "register_/_rurl_/_search"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/search_v2/', '통합 검색 V2', '["lawform", "register_/_rurl_/_search"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/shareholder_meeting/', '주주총회 목록', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/shareholder_meeting/:id', '주주총회 상세', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/shareholder_meeting/', '주주총회 생성', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/shareholder_meeting/progress', '주주총회 진행', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/shareholder_meeting/:id', '주주총회 삭제', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/sso/vessl-ai', 'Okta SAML ACS', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/stamps/', '직인 목록', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/stamps/', '직인 생성', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 1, 'LAWFORM', NOW(), NOW());

INSERT INTO `ApiEndpoints` (`method`, `path`, `description`, `tags`, `auth_required`, `project_key`, `created_at`, `updated_at`) VALUES
('DELETE', '/api/stamps/:id', '직인 삭제', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/startup/list', '스타트업 목록', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/startup/:id', '스타트업 상세', '["lawform", "shareholder_meeting_/_sso_/_stamps_/_startup"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/statistics/individual', '개인 현황', '["lawform", "statistics"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/statistics/department-team', '부서 현황', '["lawform", "statistics"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/statistics/clm-trend', '계약 체결 추이', '["lawform", "statistics"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/statistics/count-by-type/:type', '유형별 건수', '["lawform", "statistics"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/statistics/upcoming-schedule/:type', '다가오는 일정', '["lawform", "statistics"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/statistics_banners_click/redirect_id/:id', '배너 클릭 (리다이렉트)', '["lawform", "statistics"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/statistics_banners_click/create', '배너 클릭 기록', '["lawform", "statistics"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/statistics_tracker/create', '페이지 방문 기록', '["lawform", "statistics"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/team/:id', '팀 상세', '["lawform", "team"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/team/create', '팀 생성', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/team/remove/master', '팀 삭제', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/team/', '팀 수정', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/team/invite/member', '멤버 초대', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/team/update/member', '멤버 정보 수정', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/team/list/members', '멤버 목록', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/team/detail/member/:detail_user_id', '멤버 상세', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/team/detail/member/:detail_user_id/clm', '멤버 CLM 문서', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/team/remove/member/:remove_user_id', '멤버 제거', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/team/logo', '팀 로고 등록', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/team/login_option', '팀 로그인 설정', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/team_flex/', 'Team Flex 조회', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/team_flex/', 'Team Flex 생성/수정', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/team_member_category/list', '멤버 카테고리 목록', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/team_member_category/create', '멤버 카테고리 생성', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/team_organization/', '조직도 목록', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/team_organization/', '조직도 생성', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/team_organization/update/tree', '조직도 위치 이동', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/team_organization/', '조직도 삭제', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/team_standard_contract/list', '표준계약서 목록', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/team_standard_contract/create/', '표준계약서 생성', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/team_watermark/create', '팀 워터마크 생성', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/team_watermark/list', '팀 워터마크 목록', '["lawform", "team"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user/update/two_fa/otp', 'OTP 2FA 설정', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user/update/two_fa/sms', 'SMS 2FA 설정', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user/business/notification', 'CLM 알림 설정 조회', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user/business/notification', 'CLM 알림 설정 수정', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user/', '회원 정보 수정', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user/update/password', '비밀번호 변경', '["lawform", "user"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user/update/business', '비즈니스 정보 수정', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user/update/user_to_lawyer', '변호사 전환', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user/update/profile_img', '프로필 사진 업데이트', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user/mobile_number', '휴대폰 번호 저장', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user/change_team', '팀 전환', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user/business_number', '사업자번호 인증', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user/send/auth_code', '인증 코드 발송', '["lawform", "user"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user/check/auth_code', '인증 코드 확인', '["lawform", "user"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user/locale', '언어 설정 변경', '["lawform", "user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user_bookmark/', '북마크 등록', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_bookmark/', '북마크 목록', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/user_bookmark/:magazine_id', '북마크 삭제', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_contact/', '인적정보 목록', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user_contact/', '인적정보 등록', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user_contact/my', '본인 인적정보 등록', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_contents/', '맞춤 컨텐츠 조회', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_coupon_log_v2/', '쿠폰 목록', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user_coupon_log_v2/use', '쿠폰 사용', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_favorite/', '즐겨찾기 목록', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user_favorite/create', '즐겨찾기 등록', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/user_favorite/delete/:id', '즐겨찾기 삭제', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user_law_information/upsert', '법률 정보 생성/수정', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_law_information/list', '법률 정보 목록', '["lawform", "user_bookmark_/_contact_/_contents_/_coupon_/_favorite_/_law_information"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_login/', '로그인 세션 목록', '["lawform", "user_login_/_permission_/_education_/_event_/_signup_path"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user_login/remote_logout', '원격 로그아웃', '["lawform", "user_login_/_permission_/_education_/_event_/_signup_path"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/user_login/logout', '로그아웃 시간 기록', '["lawform", "user_login_/_permission_/_education_/_event_/_signup_path"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_permission/count', '이용권 수', '["lawform", "user_login_/_permission_/_education_/_event_/_signup_path"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_permission_log/', '이용권 사용 로그', '["lawform", "user_login_/_permission_/_education_/_event_/_signup_path"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_education/:education_id', '교육 상세', '["lawform", "user_login_/_permission_/_education_/_event_/_signup_path"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/user_education/quiz', '교육 퀴즈 제출', '["lawform", "user_login_/_permission_/_education_/_event_/_signup_path"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/user_signup_path/', '회원가입 경로 목록', '["lawform", "user_login_/_permission_/_education_/_event_/_signup_path"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/writing/', '자동작성 문서 수', '["lawform", "writing_관련"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/writing_bulk_document/list', '대량 문서 목록', '["lawform", "writing_관련"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/writing_bulk_document/create', '대량 문서 생성', '["lawform", "writing_관련"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/writing_bulk_document/', '대량 문서 삭제', '["lawform", "writing_관련"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/writing_bulk_meta_info/', 'Bulk Meta Info 목록', '["lawform", "writing_관련"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/writing_bulk_meta_info/upload', '사용자 데이터 Excel 업로드', '["lawform", "writing_관련"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/writing_logo/', '자동작성 로고 수정', '["lawform", "writing_관련"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/writing_preview/', '자동작성 미리보기', '["lawform", "writing_관련"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/writing_saved_log/', '자동작성 저장 로그', '["lawform", "writing_관련"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/writing_temp/list', '임시저장 문서 목록', '["lawform", "writing_관련"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/webhook/action/slack', 'Slack Action 처리', '["lawform", "webhook_/_waypoint"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/waypoint_progress/create', '웨이포인트 진행 상황 생성', '["lawform", "webhook_/_waypoint"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/thirdparty/autodoc/update/binddata', 'bind data 업데이트', '["thirdparty", "autodoc"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/thirdparty/autodoc/', '자동작성문서 업데이트', '["thirdparty", "autodoc"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/autodoc/doc/download', '워드파일 다운로드', '["thirdparty", "autodoc"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/autodoc/update/editor_mode', '편집기 모드 전환', '["thirdparty", "autodoc"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/banner/group/:group_id', 'group_id로 배너 조회', '["thirdparty", "banner_/_cfs_/_cfs_collaborator_/_cfs_meta"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/cfs/list', 'CFS 목록', '["thirdparty", "banner_/_cfs_/_cfs_collaborator_/_cfs_meta"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/cfs/detail', 'CFS 상세', '["thirdparty", "banner_/_cfs_/_cfs_collaborator_/_cfs_meta"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/cfs/autodoc/create', '자동작성 문서 생성', '["thirdparty", "banner_/_cfs_/_cfs_collaborator_/_cfs_meta"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/cfs/esign/create', '전자서명 생성', '["thirdparty", "banner_/_cfs_/_cfs_collaborator_/_cfs_meta"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/cfs/folder/create', 'CFS 폴더 생성', '["thirdparty", "banner_/_cfs_/_cfs_collaborator_/_cfs_meta"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/thirdparty/cfs/remove', 'CFS 삭제', '["thirdparty", "banner_/_cfs_/_cfs_collaborator_/_cfs_meta"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/cfs_collaborator/create/invite', '협업자 초대', '["thirdparty", "banner_/_cfs_/_cfs_collaborator_/_cfs_meta"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/thirdparty/cfs_collaborator/remove/:cfs_id/:remove_id', '협업자 삭제', '["thirdparty", "banner_/_cfs_/_cfs_collaborator_/_cfs_meta"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/cfs_meta/', 'CFS 메타 목록', '["thirdparty", "banner_/_cfs_/_cfs_collaborator_/_cfs_meta"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/cfs_poison_pill/list', '독소조항 조회', '["thirdparty", "cfs_poison_pill_/_cfs_request"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/thirdparty/cfs_poison_pill/', '독소조항 삭제', '["thirdparty", "cfs_poison_pill_/_cfs_request"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/thirdparty/cfs_poison_pill/poison_pill_review', '독소조항 재평가', '["thirdparty", "cfs_poison_pill_/_cfs_request"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/cfs_request/', 'CFS 요청 생성', '["thirdparty", "cfs_poison_pill_/_cfs_request"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/cfs_request/', 'CFS 요청 목록', '["thirdparty", "cfs_poison_pill_/_cfs_request"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/thirdparty/cfs_request/', 'CFS 요청 수정', '["thirdparty", "cfs_poison_pill_/_cfs_request"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/cims/login', 'CIMS 로그인', '["thirdparty", "cims"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/cims/send/auth_code', 'CIMS 인증번호 전송', '["thirdparty", "cims"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/cims/check/auth_code', 'CIMS 인증번호 확인', '["thirdparty", "cims"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/cims/user/list', 'CIMS 유저 목록', '["thirdparty", "cims"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/cims/activity/log/list', 'CIMS 활동 로그', '["thirdparty", "cims"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/cims/login/statistics', 'CIMS 로그인 통계', '["thirdparty", "cims"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/document/list', '문서 목록', '["thirdparty", "document_/_esign_/_gld"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/document/search', '문서 검색', '["thirdparty", "document_/_esign_/_gld"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/esign/register/complete', '전자서명 최종요청', '["thirdparty", "document_/_esign_/_gld"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/thirdparty/esign/update/signer/sign', '서명 업데이트', '["thirdparty", "document_/_esign_/_gld"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/esign/send/auth_code', '전자서명 인증번호 전송', '["thirdparty", "document_/_esign_/_gld"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/thirdparty/esign/cancel', '전자서명 거절', '["thirdparty", "document_/_esign_/_gld"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/esign/generate/pdf/:id', '전자서명 PDF 생성', '["thirdparty", "document_/_esign_/_gld"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/esign/progress', '전자서명 진행상태', '["thirdparty", "document_/_esign_/_gld"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/gld_document/', 'GLD bind data 결과', '["thirdparty", "document_/_esign_/_gld"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/gld_thread/', 'GLD 스레드 목록', '["thirdparty", "document_/_esign_/_gld"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/gld_thread/', 'GLD 스레드 생성', '["thirdparty", "document_/_esign_/_gld"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/gld_thread_message/', 'GLD 스레드 메시지 생성', '["thirdparty", "document_/_esign_/_gld"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/magazine/list', '매거진 목록', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/magazine/detail/:id', '매거진 상세', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/pdf/generate', 'PDF 생성', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/recommend/list', 'AI 추천 문서', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/register/signup', '회원가입 (암호화)', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/register/login', '로그인', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/register/kakaosync', '카카오 로그인', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/register/google', '구글 로그인', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/user/detail', '내 정보 조회', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/user/sso', 'SSO 세션 키 생성', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/user/token', '토큰 변환', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/thirdparty/user/update', '유저 정보 업데이트', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/thirdparty/user/quit', '유저 탈퇴', '["thirdparty", "magazine_/_pdf_/_recommend_/_register_/_user"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/user_qna/list', '1대1 문의 목록', '["thirdparty", "user_qna_/_user_history_/_writing_log"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/thirdparty/user_qna/create', '1대1 문의 등록', '["thirdparty", "user_qna_/_user_history_/_writing_log"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/user_history/list', '활동내역 목록', '["thirdparty", "user_qna_/_user_history_/_writing_log"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/writing_editor_log/', '편집기 저장 로그 목록', '["thirdparty", "user_qna_/_user_history_/_writing_log"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/thirdparty/writing_saved_log/', '저장 로그 목록', '["thirdparty", "user_qna_/_user_history_/_writing_log"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ai/azure/chat', 'Azure AI 채팅', '["ai"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ai/azure/checklist', 'Azure AI 체크리스트', '["ai"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ai/azure/comparison', 'Azure AI 문서 비교', '["ai"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/ai/azure/comparison', '문서 비교 결과 (polling)', '["ai"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ai/chat/create_room', '채팅방 생성', '["ai"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ai/chat/create_message', '채팅 메시지 생성', '["ai"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ai/chat/ask', 'AI 질문', '["ai"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ai/checklist/create', '체크리스트 생성', '["ai"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/gld/ai_gld_thread_message_create', 'GLD 스레드 메시지 AI 생성', '["ai"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/gld/ai_gld_thread_message_file_create', 'GLD 스레드 메시지 파일 AI 생성', '["ai"]', 0, 'LAWFORM', NOW(), NOW()),
('GET', '/api/ai/log/find', 'AI 로그 목록', '["ai"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/ai/meta/find', 'AI 메타 목록', '["ai"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/ai/setting/find/current', '현재 AI 설정', '["ai"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ai/setting/create', 'AI 설정 생성', '["ai"]', 0, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ims/curation/create', '큐레이션 생성', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/ims/curation/update', '큐레이션 수정', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/ims/curation/list', '큐레이션 목록', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/api/ims/curation/:id', '큐레이션 상세', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/ims/document/update', '문서 업데이트', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ims/document_ai_question/create', '문서 AI 질문 생성', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/ims/document_ai_question/update', '문서 AI 질문 수정', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('DELETE', '/api/ims/document_ai_question/remove/:id', '문서 AI 질문 삭제', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ims/ims/create', 'IMS 등록', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/ims/ims/update', 'IMS 수정', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/ims/ims/connect_user/:id', 'IMS 회원 연결', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ims/ims_consult/create', 'IMS 상담내용 등록', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ims/ims_memos/create', 'IMS 메모 등록', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('POST', '/api/ims/upload/ai_test_c', 'AI 문서 테스트 업로드', '["ims"]', 0, 'LAWFORM', NOW(), NOW()),
('PUT', '/api/ims/user/update_business', '유저 기업정보 업데이트', '["ims"]', 1, 'LAWFORM', NOW(), NOW()),
('GET', '/aws/lb', 'AWS Load Balancer 헬스체크', '["aws"]', 0, 'LAWFORM', NOW(), NOW());